/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "2 2.93 16.68 14.14",
	svg: (
		<path d="M11.732 4.59a.88.88 0 0 1 .623-1.077l2.043-.548a.88.88 0 0 1 1.077.622l3.168 11.823a.88.88 0 0 1-.623 1.078l-2.043.547a.88.88 0 0 1-1.077-.622zM7 3.88A.88.88 0 0 1 7.88 3h2.115a.88.88 0 0 1 .88.88v12.24a.88.88 0 0 1-.88.88H7.88a.88.88 0 0 1-.88-.88zm-5 0A.88.88 0 0 1 2.88 3h2.115a.88.88 0 0 1 .88.88v12.24a.88.88 0 0 1-.88.88H2.88a.88.88 0 0 1-.88-.88z" />
	),
}

export const bookshelfFillIcon: LoadedIconFunction<"fill"> = createIcon(
	"bookshelfFill",
	iconDefinition,
	"fill",
)
