/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "1.47 2.08 13.09 11.65",
	svg: (
		<path d="M1.476 3.504c0-.678.55-1.228 1.228-1.229h1.893c.22 0 .425.059.603.16.179-.101.384-.16.604-.16h1.892c.372 0 .704.166.929.427q.108-.054.23-.087l1.828-.49a1.23 1.23 0 0 1 1.504.87l2.327 8.685a1.23 1.23 0 0 1-.868 1.506l-1.829.489a1.23 1.23 0 0 1-1.505-.87L8.926 7.627v4.87c0 .679-.55 1.23-1.229 1.23H5.804a1.2 1.2 0 0 1-.604-.16 1.2 1.2 0 0 1-.603.16H2.704a1.23 1.23 0 0 1-1.228-1.23zm10.039 8.958 1.787-.479-2.317-8.645-1.787.478zm-3.84.014v-8.95h-1.85v8.95zm-3.1 0v-8.95h-1.85v8.95z" />
	),
}

export const bookshelfSmallIcon: LoadedIconFunction<"small"> = createIcon(
	"bookshelfSmall",
	iconDefinition,
	"small",
)
