/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "1.77 3.17 12.46 9.66",
	svg: (
		<>
			<path d="M8.656 4.425H3.601A.575.575 0 0 0 3.025 5v6c0 .318.258.575.576.575h8.8a.576.576 0 0 0 .575-.575V8.744h1.25V11a1.826 1.826 0 0 1-1.826 1.825H3.6A1.826 1.826 0 0 1 1.775 11V5c0-1.008.819-1.825 1.827-1.825h5.055z" />
			<path d="M7.658 8.65a.4.4 0 0 1 .4.4v1.3a.4.4 0 0 1-.4.4H4.244a.4.4 0 0 1-.4-.4v-1.3a.4.4 0 0 1 .4-.4zM13.6 3.175a.63.63 0 0 1 .626.625v3.346a.626.626 0 0 1-1.25 0V5.31L9.612 8.672a.625.625 0 0 1-.883-.884l3.363-3.363h-1.838a.625.625 0 0 1 0-1.25z" />
		</>
	),
}

export const cornerPeekExpandSmallIcon: LoadedIconFunction<"small"> =
	createIcon("cornerPeekExpandSmall", iconDefinition, "small")
