/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import type { IconGroup } from "../../iconUtils"
import { createIconGroup } from "../../iconUtils"

export const arrowUTurnUpRightIconGroup: IconGroup<
	"default" | "small" | "fill" | "fillSmall"
> = createIconGroup(
	"arrowUTurnUpRight",
	{
		default: {
			loader: () =>
				import(
					/* webpackChunkName: "icon-arrowUTurnUpRight" */
					"./default.icon"
				),
		},
		small: {
			loader: () =>
				import(
					/* webpackChunkName: "icon-arrowUTurnUpRight" */
					"./small.icon"
				),
		},
		fill: {
			loader: () =>
				import(
					/* webpackChunkName: "icon-arrowUTurnUpRight" */
					"./fill.icon"
				),
		},
		fillSmall: {
			loader: () =>
				import(
					/* webpackChunkName: "icon-arrowUTurnUpRight" */
					"./fillSmall.icon"
				),
		},
	},
	["uturn", "right", "reverse", "direction", "turn", "redo", "repeat"],
)
