/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "0.87 4.12 18.25 11.75",
	svg: (
		<path d="M3.25 4.125a.625.625 0 0 1 0 1.25H3a.875.875 0 0 0-.875.875v7.5c0 .483.392.875.875.875h.25a.625.625 0 0 1 0 1.25H3A2.125 2.125 0 0 1 .875 13.75v-7.5c0-1.174.951-2.125 2.125-2.125zm13.75 0c1.174 0 2.125.951 2.125 2.125v7.5A2.125 2.125 0 0 1 17 15.875H7a2.125 2.125 0 0 1-2.125-2.125v-7.5c0-1.174.951-2.125 2.125-2.125z" />
	),
}

export const rectangleOnRectangleParallelFillIcon: LoadedIconFunction<"fill"> =
	createIcon("rectangleOnRectangleParallelFill", iconDefinition, "fill")
