/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "1.25 1.3 13.51 13.66",
	svg: (
		<path d="M3 1.307a1.75 1.75 0 0 0-1.75 1.75v5.886c0 .966.784 1.75 1.75 1.75h10a1.75 1.75 0 0 0 1.75-1.75V3.057A1.75 1.75 0 0 0 13 1.307zm.32 2.613a.52.52 0 1 1 1.04 0 .52.52 0 0 1-1.04 0m2.6.52a.52.52 0 1 1 0-1.04.52.52 0 0 1 0 1.04m1.56-.52a.52.52 0 1 1 1.04 0 .52.52 0 0 1-1.04 0m2.6.52a.52.52 0 1 1 0-1.04.52.52 0 0 1 0 1.04m1.56-.52a.52.52 0 1 1 1.04 0 .52.52 0 0 1-1.04 0m-7.8 2.6a.52.52 0 1 1 0-1.04.52.52 0 0 1 0 1.04M5.4 6a.52.52 0 1 1 1.04 0A.52.52 0 0 1 5.4 6m2.6.52a.52.52 0 1 1 0-1.04.52.52 0 0 1 0 1.04M9.56 6a.52.52 0 1 1 1.04 0 .52.52 0 0 1-1.04 0m2.6.52a.52.52 0 1 1 0-1.04.52.52 0 0 1 0 1.04M3.32 8.08a.52.52 0 1 1 1.04 0 .52.52 0 0 1-1.04 0m2.563.539a.55.55 0 0 1 0-1.1h4.2a.55.55 0 0 1 0 1.1zm5.757-.539a.52.52 0 1 1 1.04 0 .52.52 0 0 1-1.04 0m-.412 4.752a.5.5 0 1 0-.584-.812l-2.536 1.822-2.536-1.822a.5.5 0 1 0-.584.812l2.828 2.032a.5.5 0 0 0 .584 0z" />
	),
}

export const keyboardDownFillSmallIcon: LoadedIconFunction<"fillSmall"> =
	createIcon("keyboardDownFillSmall", iconDefinition, "fillSmall")
