/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "1.28 3.52 17.42 12.96",
	svg: (
		<>
			<path d="M12.786 8.665a.625.625 0 1 0-1.072-.643L9.46 11.778l-1.235-1.441a.625.625 0 0 0-.95.813l1.8 2.1a.625.625 0 0 0 1.01-.085z" />
			<path d="M10.45 3.525a6.48 6.48 0 0 0-6.384 5.39 3.856 3.856 0 0 0 1.056 7.56H15.2a3.494 3.494 0 0 0 1.725-6.532 6.475 6.475 0 0 0-6.475-6.418M5.25 9.49a5.226 5.226 0 0 1 10.417.803l-.024.443.41.17a2.245 2.245 0 0 1-.854 4.319H5.13a2.605 2.605 0 0 1-.405-5.178l.479-.075z" />
		</>
	),
}

export const cloudCheckIcon: LoadedIconFunction<"default"> = createIcon(
	"cloudCheck",
	iconDefinition,
	"default",
)
