/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "3.12 1.25 15.63 15.63",
	svg: (
		<>
			<path d="M16.25 6.25a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5" />
			<path d="M5.25 3.125h7.302a3.8 3.8 0 0 0 0 1.25H5.25a.875.875 0 0 0-.875.875v9.5c0 .483.392.875.875.875h9.5a.875.875 0 0 0 .875-.875V7.448a3.8 3.8 0 0 0 1.25 0v7.302a2.125 2.125 0 0 1-2.125 2.125h-9.5a2.125 2.125 0 0 1-2.125-2.125v-9.5c0-1.174.951-2.125 2.125-2.125" />
		</>
	),
}

export const markUnreadIcon: LoadedIconFunction<"default"> = createIcon(
	"markUnread",
	iconDefinition,
	"default",
)
