/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "2.37 0.92 12.71 12.7",
	svg: (
		<>
			<path d="M13 .925a2.075 2.075 0 1 0 0 4.15 2.075 2.075 0 0 0 0-4.15" />
			<path d="M4.25 2.375c-1.036 0-1.875.84-1.875 1.875v7.5c0 1.036.84 1.875 1.875 1.875h7.5c1.036 0 1.875-.84 1.875-1.875V5.962l-.088.016a3 3 0 0 1-1.074 0l-.088-.016v5.788c0 .345-.28.625-.625.625h-7.5a.625.625 0 0 1-.625-.625v-7.5c0-.345.28-.625.625-.625h5.788l-.016-.088a3 3 0 0 1 0-1.074l.016-.088z" />
		</>
	),
}

export const markUnreadSmallIcon: LoadedIconFunction<"small"> = createIcon(
	"markUnreadSmall",
	iconDefinition,
	"small",
)
