/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "3.7 1.41 8.6 12.78",
	svg: (
		<path d="M9.635 1.955a.5.5 0 0 0-.905-.328l-4.935 6.84a.5.5 0 0 0 .405.793h2.478l-.32 4.4a.5.5 0 0 0 .903.33l4.944-6.833a.5.5 0 0 0-.405-.793H9.32z" />
	),
}

export const lightningFillSmallIcon: LoadedIconFunction<"fillSmall"> =
	createIcon("lightningFillSmall", iconDefinition, "fillSmall")
