/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "3.62 1.34 8.75 12.93",
	svg: (
		<path d="M9.332 1.38a.575.575 0 0 0-.662.204l-4.936 6.84a.575.575 0 0 0 .466.911h2.398l-.315 4.32a.575.575 0 0 0 1.039.378l4.944-6.832a.575.575 0 0 0-.466-.912H9.401l.309-4.328a.575.575 0 0 0-.378-.582M7.216 8.185H5.324l3.095-4.289-.209 2.927a.575.575 0 0 0 .574.616h1.89l-3.097 4.28.212-2.917a.575.575 0 0 0-.573-.617" />
	),
}

export const lightningSmallIcon: LoadedIconFunction<"small"> = createIcon(
	"lightningSmall",
	iconDefinition,
	"small",
)
