/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "2.61 4.5 14.73 11.01",
	svg: (
		<path d="M7.12 4.875a.625.625 0 1 0 0 1.25h9.6a.625.625 0 1 0 0-1.25zm0 4.5a.625.625 0 1 0 0 1.25h9.6a.625.625 0 1 0 0-1.25zM6.495 14.5c0-.345.28-.625.625-.625h9.6a.625.625 0 1 1 0 1.25h-9.6a.625.625 0 0 1-.625-.625m-2.875-8a1 1 0 1 0 0-2 1 1 0 0 0 0 2m1 3.5a1 1 0 1 1-2 0 1 1 0 0 1 2 0m-1 5.5a1 1 0 1 0 0-2 1 1 0 0 0 0 2" />
	),
}

export const bulletedListIcon: LoadedIconFunction<"default"> = createIcon(
	"bulletedList",
	iconDefinition,
	"default",
)
