/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "0.2 4.86 15.62 6.8",
	svg: (
		<path
			fillRule="evenodd"
			d="M11.765 4.87c1.143.062 2.126.762 2.644 1.77h.791l.126.013a.626.626 0 0 1 0 1.225l-.126.013h-.42q.02.184.02.375l-.004.174c-.086 1.797-1.484 3.225-3.195 3.225l-.166-.004c-1.635-.088-2.948-1.482-3.03-3.22L8.4 8.265q0-.372.072-.721a1.1 1.1 0 0 0-.947 0q.074.35.076.72l-.005.175c-.086 1.797-1.484 3.225-3.196 3.225l-.165-.004c-1.636-.088-2.948-1.482-3.03-3.22L1.2 8.265q0-.19.02-.375H.8a.626.626 0 0 1 0-1.25h.788C2.13 5.583 3.187 4.865 4.4 4.865l.164.005c1.044.056 1.955.644 2.5 1.514a2.35 2.35 0 0 1 1.87 0c.573-.916 1.554-1.519 2.667-1.519zM4.4 6.115c-1.006 0-1.95.89-1.95 2.15s.944 2.15 1.95 2.15 1.95-.89 1.95-2.15-.943-2.15-1.95-2.15m7.2 0c-1.006 0-1.95.89-1.95 2.15s.944 2.15 1.95 2.15 1.95-.89 1.95-2.15-.943-2.15-1.95-2.15"
			clipRule="evenodd"
		/>
	),
}

export const eyeglassesSmallIcon: LoadedIconFunction<"small"> = createIcon(
	"eyeglassesSmall",
	iconDefinition,
	"small",
)
