/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "1.95 2.22 12.08 10.61",
	svg: (
		<path d="M8.756 2.655a.875.875 0 0 0-1.512 0L2.079 11.51a.875.875 0 0 0 .756 1.316h10.33a.875.875 0 0 0 .755-1.316zm3.756 8.92H3.488L8 3.84z" />
	),
}

export const arrowCaretUpSmallIcon: LoadedIconFunction<"small"> = createIcon(
	"arrowCaretUpSmall",
	iconDefinition,
	"small",
)
