/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "3.23 3.23 13.54 13.53",
	svg: (
		<path d="M4.485 8.86V5.369l4.073 4.073a.625.625 0 0 0 .884-.884L5.369 4.485h3.49a.625.625 0 1 0 0-1.25h-5a.625.625 0 0 0-.624.625v5a.625.625 0 0 0 1.25 0m10.146 6.655-4.07-4.07a.625.625 0 0 1 .884-.884l4.07 4.07V11.14a.625.625 0 1 1 1.25 0v5c0 .345-.28.625-.625.625h-5a.625.625 0 1 1 0-1.25z" />
	),
}

export const arrowExpandDiagonalIcon: LoadedIconFunction<"default"> =
	createIcon("arrowExpandDiagonal", iconDefinition, "default")
