/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "2.33 2.33 11.33 11.33",
	svg: (
		<path d="M3.838 7.088v-2.19L6.669 7.73A.75.75 0 0 0 7.73 6.67L4.9 3.837h2.189a.75.75 0 0 0 0-1.5h-4a.75.75 0 0 0-.75.75v4a.75.75 0 1 0 1.5 0m7.262 5.075-2.829-2.83a.75.75 0 0 1 1.06-1.06l2.83 2.83v-2.19a.75.75 0 0 1 1.5 0v4a.75.75 0 0 1-.75.75h-4a.75.75 0 0 1 0-1.5z" />
	),
}

export const arrowExpandDiagonalFillSmallIcon: LoadedIconFunction<"fillSmall"> =
	createIcon("arrowExpandDiagonalFillSmall", iconDefinition, "fillSmall")
