/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "2.74 4.12 14.52 12.76",
	svg: (
		<path d="M2.899 5.817a1.125 1.125 0 0 1 .972-1.692H16.13c.868 0 1.409.942.971 1.692l-6.13 10.508a1.125 1.125 0 0 1-1.943 0zm1.19-.442L10 15.51l5.912-10.135z" />
	),
}

export const arrowCaretDownIcon: LoadedIconFunction<"default"> = createIcon(
	"arrowCaretDown",
	iconDefinition,
	"default",
)
