/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "1.45 3.05 13.1 10.24",
	directional: true,
	svg: (
		<path d="M6.25 11.99a.75.75 0 1 1-1.06 1.06L1.67 9.53a.75.75 0 0 1 0-1.06l3.52-3.52a.75.75 0 0 1 1.06 1.06L4.01 8.25h7.19a1.85 1.85 0 1 0 0-3.7h-1.136a.75.75 0 0 1 0-1.5H11.2a3.35 3.35 0 1 1 0 6.7H4.01z" />
	),
}

export const arrowUTurnDownLeftFillSmallIcon: LoadedIconFunction<"fillSmall"> =
	createIcon("arrowUTurnDownLeftFillSmall", iconDefinition, "fillSmall")
