/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "1.87 3.87 16.26 12.66",
	directional: true,
	svg: (
		<path d="M7.769 15.031A.875.875 0 1 1 6.53 16.27l-4.4-4.4a.875.875 0 0 1 0-1.238l4.4-4.4A.875.875 0 0 1 7.77 7.47l-2.907 2.906H14a2.375 2.375 0 1 0 0-4.75h-1.42a.875.875 0 1 1 0-1.75H14a4.125 4.125 0 1 1 0 8.25H4.862z" />
	),
}

export const arrowUTurnDownLeftFillIcon: LoadedIconFunction<"fill"> =
	createIcon("arrowUTurnDownLeftFill", iconDefinition, "fill")
