/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "1.57 3.17 12.86 9.98",
	directional: true,
	svg: (
		<path d="M10.064 3.175a.625.625 0 1 0 0 1.25H11.2a1.975 1.975 0 1 1 0 3.95H3.71l2.452-2.453a.625.625 0 0 0-.884-.884l-3.52 3.52a.625.625 0 0 0 0 .884l3.52 3.52a.625.625 0 0 0 .884-.884L3.71 9.625h7.49a3.225 3.225 0 1 0 0-6.45z" />
	),
}

export const arrowUTurnDownLeftSmallIcon: LoadedIconFunction<"small"> =
	createIcon("arrowUTurnDownLeftSmall", iconDefinition, "small")
