/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "2.37 2.37 11.26 11.26",
	svg: (
		<path d="M4.667 2.375a2.292 2.292 0 0 0 0 4.583h1.042v2.084H4.667a2.292 2.292 0 1 0 2.291 2.291v-1.041h2.083v1.041a2.292 2.292 0 1 0 2.292-2.291h-1.041V6.958h1.041a2.292 2.292 0 1 0-2.292-2.291v1.041H6.958V4.667a2.29 2.29 0 0 0-2.291-2.292M3.625 4.667a1.042 1.042 0 1 1 2.083 0v1.041H4.667a1.04 1.04 0 0 1-1.042-1.041m6.666 0a1.042 1.042 0 1 1 1.042 1.041h-1.042zM6.958 9.042V6.958h2.084v2.084zm-3.333 2.291c0-.575.466-1.041 1.042-1.041h1.041v1.041a1.042 1.042 0 1 1-2.083 0m6.666 0v-1.041h1.042a1.042 1.042 0 1 1-1.042 1.041" />
	),
}

export const commandSmallIcon: LoadedIconFunction<"small"> = createIcon(
	"commandSmall",
	iconDefinition,
	"small",
)
