/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "1.77 3.63 12.45 9.2",
	svg: (
		<path d="M14.225 5.26c0-1.448-1.75-2.173-2.774-1.15l-3.34 3.34a.375.375 0 0 1-.53 0l-1-.998a1.625 1.625 0 0 0-2.298 0L2.251 8.484a1.63 1.63 0 0 0-.476 1.149V11.2c0 .898.728 1.625 1.625 1.625h9.2c.898 0 1.625-.727 1.625-1.625zm-1.89-.266a.375.375 0 0 1 .64.266v5.94a.375.375 0 0 1-.375.375H3.4a.375.375 0 0 1-.375-.375V9.633c0-.1.04-.195.11-.265l2.032-2.032a.375.375 0 0 1 .53 0l1 .999a1.625 1.625 0 0 0 2.297 0z" />
	),
}

export const graphAreaSmallIcon: LoadedIconFunction<"small"> = createIcon(
	"graphAreaSmall",
	iconDefinition,
	"small",
)
