/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "2.57 2.19 10.85 11.61",
	svg: (
		<path d="m4.145 2.657-.227-.265a.55.55 0 1 0-.836.716l1.15 1.342H3.126a.55.55 0 0 0 0 1.1h.6l.294 6.472A1.863 1.863 0 0 0 5.88 13.8h4.242a1.86 1.86 0 0 0 1.489-.743l.472.551a.55.55 0 0 0 .843-.707L9.813 9.27v2.105a.5.5 0 0 1-1 0V8.103l-4.66-5.437zm2.543 3.718a.5.5 0 0 1 .5.5v4.5a.5.5 0 0 1-1 0v-4.5a.5.5 0 0 1 .5-.5M9.813 7.58v-.705a.5.5 0 0 0-.881-.323L7.13 4.45H9.7v-.825a.325.325 0 0 0-.325-.325h-2.75a.325.325 0 0 0-.303.207l-.735-.858c.26-.276.629-.449 1.038-.449h2.75c.787 0 1.425.638 1.425 1.425v.825h2.075a.55.55 0 1 1 0 1.1h-.6l-.211 4.656z" />
	),
}

export const trashSlashFillSmallIcon: LoadedIconFunction<"fillSmall"> =
	createIcon("trashSlashFillSmall", iconDefinition, "fillSmall")
