/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "3.12 3.12 16.77 16.82",
	svg: (
		<>
			<path d="M13.93 11.894a1.313 1.313 0 0 1 2.274 0l3.507 6.075a1.313 1.313 0 0 1-1.137 1.968H11.56a1.313 1.313 0 0 1-1.137-1.968zm1.062 5.423a.625.625 0 1 0 0 1.25.625.625 0 0 0 0-1.25m0-3.662a.55.55 0 0 0-.55.55v1.875a.55.55 0 0 0 1.1 0v-1.875a.55.55 0 0 0-.55-.55" />
			<path d="M3.75 3.125c.345 0 .625.28.625.625v5.098l3.017-2.64.097-.07a.626.626 0 0 1 .756.098l3.035 3.036 3.485-3.484H12.75a.626.626 0 0 1 0-1.25h3.5c.345 0 .625.28.625.624l.001 3.501a.626.626 0 0 1-1.252 0V6.697L11.723 10.6a.625.625 0 0 1-.884 0L7.774 7.533l-3.399 2.975v4.242c0 .483.392.875.875.875h4.981l-.721 1.25H5.25a2.125 2.125 0 0 1-2.125-2.125v-11c0-.345.28-.625.625-.625" />
		</>
	),
}

export const chartLineUptrendWarningIcon: LoadedIconFunction<"default"> =
	createIcon("chartLineUptrendWarning", iconDefinition, "default")
