/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "2.37 1.09 15.25 17.81",
	svg: (
		<path d="M10.442 1.278a.625.625 0 0 0-.884 0l-2.5 2.5a.625.625 0 1 0 .884.884L9.4 3.204v3.52a.625.625 0 0 0 1.25 0v-3.47l1.408 1.408a.625.625 0 1 0 .884-.884zM9.35 13.275v3.466l-1.408-1.408a.625.625 0 1 0-.884.884l2.5 2.5c.244.244.64.244.884 0l2.5-2.5a.625.625 0 0 0-.884-.884L10.6 16.791v-3.516a.625.625 0 1 0-1.25 0M4.5 6.125H8v1.25H4.5a.875.875 0 0 0-.875.875v3.5c0 .483.392.875.875.875H8v1.25H4.5a2.125 2.125 0 0 1-2.125-2.125v-3.5c0-1.174.951-2.125 2.125-2.125m11 6.5H12v1.25h3.5a2.125 2.125 0 0 0 2.125-2.125v-3.5A2.125 2.125 0 0 0 15.5 6.125H12v1.25h3.5c.483 0 .875.392.875.875v3.5a.875.875 0 0 1-.875.875" />
	),
}

export const rectangleExpandVerticalIcon: LoadedIconFunction<"default"> =
	createIcon("rectangleExpandVertical", iconDefinition, "default")
