/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "2.12 0.84 15.75 18.31",
	svg: (
		<path d="M9.381 1.101a.875.875 0 0 1 1.238 0l2.5 2.5A.875.875 0 0 1 11.88 4.84l-.981-.982v2.868a.875.875 0 1 1-1.75 0V3.808l-1.031 1.03A.875.875 0 1 1 6.88 3.602zM7.5 5.875h-3A2.375 2.375 0 0 0 2.125 8.25v3.5A2.375 2.375 0 0 0 4.5 14.125h3v-1.75h-3a.625.625 0 0 1-.625-.625v-3.5c0-.345.28-.625.625-.625h3zm5 6.5h3c.345 0 .625-.28.625-.625v-3.5a.625.625 0 0 0-.625-.625h-3v-1.75h3a2.375 2.375 0 0 1 2.375 2.375v3.5a2.375 2.375 0 0 1-2.375 2.375h-3zm-3.119 6.519-2.5-2.5a.875.875 0 1 1 1.238-1.238l.981.982v-2.863a.875.875 0 0 1 1.75 0v2.912l1.031-1.03a.875.875 0 1 1 1.238 1.237l-2.5 2.5a.875.875 0 0 1-1.238 0" />
	),
}

export const rectangleExpandVerticalFillIcon: LoadedIconFunction<"fill"> =
	createIcon("rectangleExpandVerticalFill", iconDefinition, "fill")
