/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "3.54 2.24 8.92 11.51",
	svg: (
		<path d="M3.591 2.729a.75.75 0 0 1 .7-.479h7.419a.75.75 0 0 1 0 1.5H6.226l4.054 3.696a.75.75 0 0 1 0 1.108L6.226 12.25h5.484a.75.75 0 0 1 0 1.5H4.29a.75.75 0 0 1-.505-1.304L8.661 8 3.785 3.554a.75.75 0 0 1-.194-.825" />
	),
}

export const sumFillSmallIcon: LoadedIconFunction<"fillSmall"> = createIcon(
	"sumFillSmall",
	iconDefinition,
	"fillSmall",
)
