/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "3 7.2 10.01 1.61",
	svg: (
		<path d="M3.8 7.2a.8.8 0 1 1 0 1.6.8.8 0 0 1 0-1.6m2.8 0a.8.8 0 1 1 0 1.601.8.8 0 0 1 0-1.6M9.4 7.2a.8.8 0 1 1 0 1.6.8.8 0 0 1 0-1.6m2.8 0a.8.8 0 1 1 0 1.6.8.8 0 0 1 0-1.6" />
	),
}

export const dottedLineHorizontalSmallIcon: LoadedIconFunction<"small"> =
	createIcon("dottedLineHorizontalSmall", iconDefinition, "small")
