/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "2.08 2.72 15.83 14.57",
	svg: (
		<path d="m4.897 3.086-.122-.143a.625.625 0 0 0-.95.814l2.127 2.481-.268.25H2.712a.625.625 0 0 0-.625.626v6c0 .345.28.625.625.625h2.972l3.523 3.29c.619.58 1.63.14 1.63-.707v-4.385l4.389 5.12a.625.625 0 0 0 1.04-.67L4.99 3.228a.6.6 0 0 1-.092-.143m1.46 4.484.41-.382 2.82 3.29v5.196l-3.23-3.017a.63.63 0 0 0-.426-.168H3.337v-4.75H5.93c.158 0 .31-.06.426-.169m10.257 7.3a9.34 9.34 0 0 0-.389-10.114.625.625 0 0 0-1.024.717 8.1 8.1 0 0 1 .546 8.385zm-2.175-2.537a5.31 5.31 0 0 0-.746-5.619.625.625 0 0 0-.96.8 4.06 4.06 0 0 1 .779 3.737zM10.837 8.13V3.906c0-.847-1.011-1.286-1.63-.708L7.764 4.545l.814.95 1.009-.942v2.12z" />
	),
}

export const volumeOffIcon: LoadedIconFunction<"default"> = createIcon(
	"volumeOff",
	iconDefinition,
	"default",
)
