/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "1.62 2.19 12.76 11.69",
	svg: (
		<path d="m4.146 2.658-.228-.266a.55.55 0 1 0-.836.716l1.61 1.879-.164.154H2.17a.55.55 0 0 0-.55.55v4.8c0 .304.246.55.55.55h2.358l2.803 2.62a.825.825 0 0 0 1.389-.603V9.685l3.362 3.923a.55.55 0 0 0 .842-.708L4.152 2.666zm9.268 9.123a7.53 7.53 0 0 0-.394-8.005.55.55 0 0 0-.9.63 6.43 6.43 0 0 1 .523 6.476zm-1.753-2.045a4.3 4.3 0 0 0-.67-4.397.55.55 0 0 0-.844.704c.645.774.869 1.777.672 2.71zM8.72 6.304v-3.18a.825.825 0 0 0-1.389-.603l-1.03.962z" />
	),
}

export const volumeOffFillSmallIcon: LoadedIconFunction<"fillSmall"> =
	createIcon("volumeOffFillSmall", iconDefinition, "fillSmall")
