/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "1.41 0.95 13.17 14.11",
	svg: (
		<path d="M12.947 4.43c.903 0 1.636.733 1.636 1.637v3.867c0 .904-.733 1.636-1.636 1.636h-3.23v2.23a1.25 1.25 0 0 1-2.135.884l-5.8-5.8a1.25 1.25 0 0 1 0-1.767l5.8-5.8a1.25 1.25 0 0 1 2.134.884V4.43zm0 5.89a.39.39 0 0 0 .379-.309l.007-.077V6.067l-.008-.078a.39.39 0 0 0-.3-.301l-.078-.008h-4.4a.08.08 0 0 1-.074-.049L8.466 5.6V2.2L2.666 8l5.8 5.8v-3.4a.08.08 0 0 1 .08-.08z" />
	),
}

export const arrowShapeLeftSmallIcon: LoadedIconFunction<"small"> = createIcon(
	"arrowShapeLeftSmall",
	iconDefinition,
	"small",
)
