/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "1.95 1.45 16.59 16.01",
	svg: (
		<>
			<path d="M3.465 6.889a2.865 2.865 0 0 1 4.962-2.865l.244.422a.55.55 0 1 0 .952-.55l-.244-.422a3.965 3.965 0 1 0-6.867 3.965l.244.422a.55.55 0 1 0 .953-.55z" />
			<path d="M11.557 5.959a1.75 1.75 0 0 1 1.96.142 1.748 1.748 0 0 1 2.871.23l1.367 2.366a5.84 5.84 0 0 1-8.956 7.27l-4.044-3.624a1.672 1.672 0 0 1 1.64-2.831L4.593 6.39a1.75 1.75 0 1 1 3.03-1.749l1.14 1.975a1.75 1.75 0 0 1 2.29-.22c.134-.172.303-.322.504-.437M6.54 5.266a.5.5 0 0 0-.865.5l3.216 5.57a.625.625 0 0 1-.915.813L6.12 10.76a.42.42 0 0 0-.532.651l4.044 3.624a4.591 4.591 0 0 0 7.04-5.714l-1.367-2.367a.498.498 0 1 0-.864.5l.067.118a.625.625 0 1 1-1.082.625l-.563-.974a.5.5 0 0 0-.865.5l.113.194a.625.625 0 1 1-1.083.625l-.562-.974a.5.5 0 0 0-.865.5l.562.974a.625.625 0 1 1-1.082.625z" />
		</>
	),
}

export const handTapIcon: LoadedIconFunction<"default"> = createIcon(
	"handTap",
	iconDefinition,
	"default",
)
