/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "1.7 1.33 12.45 11.98",
	svg: (
		<>
			<path d="M2.98 5.544a2.156 2.156 0 0 1 3.734-2.156l.19.329a.5.5 0 0 0 .866-.5l-.19-.329a3.156 3.156 0 0 0-5.466 3.156l.19.329a.5.5 0 1 0 .866-.5z" />
			<path d="m4.245 9.46 3.145 2.82a4.057 4.057 0 0 0 6.22-5.05l-1.062-1.84a.874.874 0 1 0-1.514.875l-.385-.666a.875.875 0 0 0-1.515.874l-.35-.606a.875.875 0 0 0-1.515.875L5.73 4.075a.875.875 0 0 0-1.515.874l2.502 4.333-1.443-1.08a.813.813 0 0 0-1.03 1.258" />
		</>
	),
}

export const handTapFillSmallIcon: LoadedIconFunction<"fillSmall"> = createIcon(
	"handTapFillSmall",
	iconDefinition,
	"fillSmall",
)
