/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "2.68 3.77 14.63 14.4",
	svg: (
		<path d="m13.047 12.502-1.76 1.876c-.293.375-.576.938-.846 1.475-.179.356-.352.7-.519.972l-.36.741c-.322.527-.976.741-1.551.527a1.287 1.287 0 0 1-.77-1.56l.507-1.775c.099-.342.241-.63.384-.917.138-.278.276-.556.376-.887a.404.404 0 0 0-.39-.517H4.023a1.22 1.22 0 0 1-1.218-1.218c0-.42.224-.78.555-.995a1.18 1.18 0 0 1-.672-1.072c0-.536.34-.975.818-1.141a1.21 1.21 0 0 1-.458-.936 1.21 1.21 0 0 1 1.21-1.219 1.22 1.22 0 0 1 .868-2.077h4.309c.721 0 1.423.166 2.066.488v.01l1.424.487h.122zm1.219-7.738v7.088h2.071a.975.975 0 0 0 .976-.975V5.74a.975.975 0 0 0-.976-.975z" />
	),
}

export const handThumbsDownFillIcon: LoadedIconFunction<"fill"> = createIcon(
	"handThumbsDownFill",
	iconDefinition,
	"fill",
)
