/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import type { IconGroup } from "../../iconUtils"
import { createIconGroup } from "../../iconUtils"

export const curlyBracesIconGroup: IconGroup<
	"default" | "small" | "fill" | "fillSmall"
> = createIconGroup(
	"curlyBraces",
	{
		default: {
			loader: () =>
				import(
					/* webpackChunkName: "icon-curlyBraces" */
					"./default.icon"
				),
		},
		small: {
			loader: () =>
				import(
					/* webpackChunkName: "icon-curlyBraces" */
					"./small.icon"
				),
		},
		fill: {
			loader: () =>
				import(
					/* webpackChunkName: "icon-curlyBraces" */
					"./fill.icon"
				),
		},
		fillSmall: {
			loader: () =>
				import(
					/* webpackChunkName: "icon-curlyBraces" */
					"./fillSmall.icon"
				),
		},
	},
	[
		"braces",
		"code",
		"curly",
		"curly braces",
		"development",
		"syntax",
		"webhooks",
	],
)
