/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "0.1 1.75 14.15 12.51",
	svg: (
		<>
			<path d="M1.97 11.12a.75.75 0 0 0 1.06 0l1.65-1.65a.75.75 0 0 0-1.06-1.06l-.37.37V8a4.75 4.75 0 1 1 1.501 3.465.75.75 0 0 0-1.026 1.095A6.25 6.25 0 1 0 1.75 8v.779l-.37-.37A.75.75 0 0 0 .32 9.47z" />
			<path d="M7.9 4.75a.75.75 0 0 1 .75.75V8a.75.75 0 1 1-1.5 0V5.5a.75.75 0 0 1 .75-.75m0 6.35a.8.8 0 1 0 0-1.6.8.8 0 0 0 0 1.6" />
		</>
	),
}

export const exclamationMarkCircleArrowFillSmallIcon: LoadedIconFunction<"fillSmall"> =
	createIcon("exclamationMarkCircleArrowFillSmall", iconDefinition, "fillSmall")
