/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "0.22 1.87 13.91 12.26",
	svg: (
		<>
			<path d="M8 1.875A6.125 6.125 0 0 0 1.875 8v1.08l-.583-.582a.625.625 0 0 0-.884.884l1.65 1.65c.244.243.64.243.884 0l1.65-1.65a.625.625 0 1 0-.884-.884l-.583.583V8a4.875 4.875 0 1 1 1.54 3.557.625.625 0 0 0-.854.911A6.125 6.125 0 1 0 8 1.875" />
			<path d="M7.9 4.875a.625.625 0 0 0-.625.625V8a.625.625 0 0 0 1.25 0V5.5a.625.625 0 0 0-.625-.625m0 4.7a.725.725 0 1 0 0 1.45.725.725 0 0 0 0-1.45" />
		</>
	),
}

export const exclamationMarkCircleArrowSmallIcon: LoadedIconFunction<"small"> =
	createIcon("exclamationMarkCircleArrowSmall", iconDefinition, "small")
