/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import type { IconGroup } from "../../iconUtils"
import { createIconGroup } from "../../iconUtils"

export const arrowLeftRightIconGroup: IconGroup<
	"default" | "small" | "fill" | "fillSmall"
> = createIconGroup(
	"arrowLeftRight",
	{
		default: {
			loader: () =>
				import(
					/* webpackChunkName: "icon-arrowLeftRight" */
					"./default.icon"
				),
		},
		small: {
			loader: () =>
				import(
					/* webpackChunkName: "icon-arrowLeftRight" */
					"./small.icon"
				),
		},
		fill: {
			loader: () =>
				import(
					/* webpackChunkName: "icon-arrowLeftRight" */
					"./fill.icon"
				),
		},
		fillSmall: {
			loader: () =>
				import(
					/* webpackChunkName: "icon-arrowLeftRight" */
					"./fillSmall.icon"
				),
		},
	},
	[
		"arrows",
		"sort",
		"arrange",
		"organize",
		"order",
		"categorize",
		"switch",
		"swap",
	],
)
