/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "0.97 3.37 14.21 9.26",
	svg: (
		<path d="M.975 5.2c0-1.008.817-1.825 1.825-1.825H10c.918 0 1.678.678 1.806 1.561v6.128A1.825 1.825 0 0 1 10 12.625H2.8A1.825 1.825 0 0 1 .975 10.8zm11.931 5.61 1.32.8a.625.625 0 0 0 .95-.535v-6.15a.625.625 0 0 0-.95-.535l-1.32.8z" />
	),
}

export const videoCameraFillSmallIcon: LoadedIconFunction<"fillSmall"> =
	createIcon("videoCameraFillSmall", iconDefinition, "fillSmall")
