/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "2.12 3.37 13.55 12.3",
	svg: (
		<>
			<path d="M4 3.375c-1.036 0-1.875.84-1.875 1.875v5.5c0 1.036.84 1.875 1.875 1.875h4.731l.001-.074q.01-.564.167-1.08l.03-.096h-.304V9.958h1.15l.022-.023a3.87 3.87 0 0 1 1.828-1.08l.569-.147H8.625V7.292h4v1.44l.073.001q.566.017 1.08.182l.097.03V5.25c0-1.036-.84-1.875-1.875-1.875zM3.375 5.25c0-.345.28-.625.625-.625h3.375v1.417h-4zm5.25.792V4.625H12c.345 0 .625.28.625.625v.792zm-5.25 2.666V7.292h4v1.416zm0 2.042v-.792h4v1.417H4a.625.625 0 0 1-.625-.625" />
			<path d="M12.6 9.525a3.075 3.075 0 1 0 0 6.15 3.075 3.075 0 0 0 0-6.15M10.55 12.6a.525.525 0 1 1 1.05 0 .525.525 0 0 1-1.05 0m1.525 0a.525.525 0 1 1 1.05 0 .525.525 0 0 1-1.05 0m1.525 0a.525.525 0 1 1 1.05 0 .525.525 0 0 1-1.05 0" />
		</>
	),
}

export const tableCellsBadgeEllipsisSmallIcon: LoadedIconFunction<"small"> =
	createIcon("tableCellsBadgeEllipsisSmall", iconDefinition, "small")
