/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "3.12 2.87 13.75 14.25",
	svg: (
		<path d="M3.75 2.875a.625.625 0 1 0 0 1.25h9.5a.625.625 0 1 0 0-1.25zm0 9.75a.625.625 0 1 0 0 1.25h9.5a.625.625 0 1 0 0-1.25zM3.125 16.5c0-.345.28-.625.625-.625h6a.625.625 0 1 1 0 1.25h-6a.625.625 0 0 1-.625-.625M4.442 6.125c-.727 0-1.317.59-1.317 1.317v1.866c0 .727.59 1.317 1.317 1.317h11.116c.727 0 1.317-.59 1.317-1.317V7.442c0-.727-.59-1.317-1.317-1.317zm-.067 1.317c0-.037.03-.067.067-.067h11.116c.037 0 .067.03.067.067v1.866c0 .037-.03.067-.067.067H4.442a.067.067 0 0 1-.067-.067z" />
	),
}

export const inlineBlockSingleIcon: LoadedIconFunction<"default"> = createIcon(
	"inlineBlockSingle",
	iconDefinition,
	"default",
)
