/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "2.37 2.17 11.25 11.65",
	svg: (
		<path d="M3 2.175a.625.625 0 1 0 0 1.25h7.6a.625.625 0 1 0 0-1.25zm.5 2.6c-.621 0-1.125.504-1.125 1.125v1.6c0 .621.504 1.125 1.125 1.125h9c.621 0 1.125-.504 1.125-1.125V5.9c0-.621-.504-1.125-1.125-1.125zm.125 2.6v-1.35h8.75v1.35zM3 9.975a.625.625 0 0 0 0 1.25h7.6a.625.625 0 1 0 0-1.25zm0 2.6a.625.625 0 0 0 0 1.25h4.8a.625.625 0 1 0 0-1.25z" />
	),
}

export const inlineBlockSingleSmallIcon: LoadedIconFunction<"small"> =
	createIcon("inlineBlockSingleSmall", iconDefinition, "small")
