/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "2.37 2.37 11.25 11.26",
	svg: (
		<>
			<path d="M11.4 2.375c-.566 0-1.025.46-1.025 1.025v9.2c0 .567.459 1.026 1.025 1.026h1.2c.566 0 1.025-.46 1.025-1.025V3.4c0-.567-.459-1.026-1.025-1.026zm-8 5.2c-.566 0-1.025.46-1.025 1.025v4c0 .567.459 1.026 1.025 1.026h1.2c.566 0 1.025-.46 1.025-1.025v-4c0-.567-.459-1.026-1.025-1.026z" />
			<path d="M11.4 2.375c-.566 0-1.025.46-1.025 1.025v9.2c0 .567.459 1.026 1.025 1.026h1.2c.566 0 1.025-.46 1.025-1.025V3.4c0-.567-.459-1.026-1.025-1.026zm-4 2.801c-.566 0-1.025.459-1.025 1.025v6.4c0 .566.459 1.024 1.025 1.024h1.2c.566 0 1.025-.458 1.025-1.024V6.2c0-.566-.459-1.025-1.025-1.025z" />
		</>
	),
}

export const chartBarXAxisCumulativeFillSmallIcon: LoadedIconFunction<"fillSmall"> =
	createIcon("chartBarXAxisCumulativeFillSmall", iconDefinition, "fillSmall")
