/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import type { IconGroup } from "../../iconUtils"
import { createIconGroup } from "../../iconUtils"

export const chartBarXAxisCumulativeIconGroup: IconGroup<
	"default" | "small" | "fill" | "fillSmall"
> = createIconGroup(
	"chartBarXAxisCumulative",
	{
		default: {
			loader: () =>
				import(
					/* webpackChunkName: "icon-chartBarXAxisCumulative" */
					"./default.icon"
				),
		},
		small: {
			loader: () =>
				import(
					/* webpackChunkName: "icon-chartBarXAxisCumulative" */
					"./small.icon"
				),
		},
		fill: {
			loader: () =>
				import(
					/* webpackChunkName: "icon-chartBarXAxisCumulative" */
					"./fill.icon"
				),
		},
		fillSmall: {
			loader: () =>
				import(
					/* webpackChunkName: "icon-chartBarXAxisCumulative" */
					"./fillSmall.icon"
				),
		},
	},
	["chart", "bar chart", "sum", "summation", "cumulative", "additive"],
)
