/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "3.12 3.12 15.78 15.67",
	svg: (
		<>
			<path d="M16.328 11.844a1.79 1.79 0 0 1 1.788 1.789v.882a1 1 0 0 1 .788.977v2.295a1 1 0 0 1-1 1H14.75a1 1 0 0 1-1-1v-2.295a1 1 0 0 1 .79-.977v-.882a1.79 1.79 0 0 1 1.788-1.79m0 4.108a.644.644 0 1 0-.001 1.289.644.644 0 0 0 0-1.289m0-3.108a.79.79 0 0 0-.789.789v.86h1.577v-.86a.79.79 0 0 0-.788-.79M5.75 5.625c.621 0 1.125.504 1.125 1.125v9c0 .621-.504 1.125-1.125 1.125h-1.5a1.125 1.125 0 0 1-1.125-1.125v-9c0-.621.504-1.125 1.125-1.125zm5 4c.621 0 1.125.504 1.125 1.125v5c0 .621-.504 1.125-1.125 1.125h-1.5a1.125 1.125 0 0 1-1.125-1.125v-5c0-.621.504-1.125 1.125-1.125z" />
			<path d="M15.75 3.125c.621 0 1.125.504 1.125 1.125v6.852a3 3 0 0 0-.282-.045l-.265-.013a2.59 2.59 0 0 0-2.589 2.589v.432a1.76 1.76 0 0 0-.614.78V4.25c0-.621.504-1.125 1.125-1.125z" />
		</>
	),
}

export const chartBarXAxisLockFillIcon: LoadedIconFunction<"fill"> = createIcon(
	"chartBarXAxisLockFill",
	iconDefinition,
	"fill",
)
