/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "3.17 1.77 9.66 12.46",
	svg: (
		<path d="M11 1.774c1.007 0 1.824.82 1.824 1.827v8.8A1.825 1.825 0 0 1 11 14.224H5A1.825 1.825 0 0 1 3.174 12.4V3.6c0-1.007.818-1.825 1.826-1.826zm-.828 3.79a.626.626 0 0 0-.859.214L7.36 9.035 6.324 7.826a.625.625 0 0 0-.949.814l1.6 1.867a.625.625 0 0 0 1.01-.085l2.4-4a.625.625 0 0 0-.213-.858" />
	),
}

export const rectangleTallCheckFillSmallIcon: LoadedIconFunction<"fillSmall"> =
	createIcon("rectangleTallCheckFillSmall", iconDefinition, "fillSmall")
