/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "2.19 3.04 11.61 11.55",
	svg: (
		<path d="M13.8 4.85a1.8 1.8 0 0 0-1.8-1.8H4a1.8 1.8 0 0 0-1.8 1.8v5.5a1.8 1.8 0 0 0 1.8 1.8h.54v1.897a.55.55 0 0 0 .898.427l2.86-2.324H12a1.8 1.8 0 0 0 1.8-1.8zM4.75 7.56h1.813a.44.44 0 0 1 0 .88H4.75a.44.44 0 0 1 0-.88M7.498 8a.44.44 0 0 1 .44-.44h3.312a.44.44 0 0 1 0 .88H7.938a.44.44 0 0 1-.44-.44M4.75 9.16h.703a.44.44 0 0 1 0 .88H4.75a.44.44 0 0 1 0-.88m5.26.44a.44.44 0 0 1 .44-.44h.8a.44.44 0 0 1 0 .88h-.8a.44.44 0 0 1-.44-.44m-3.229-.44H9.11a.44.44 0 0 1 0 .88H6.78a.44.44 0 0 1 0-.88" />
	),
}

export const captionsBubbleFillSmallIcon: LoadedIconFunction<"fillSmall"> =
	createIcon("captionsBubbleFillSmall", iconDefinition, "fillSmall")
