/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "-0.01 4.12 17.63 14.63",
	svg: (
		<>
			<path d="M2.375 6.25c0-1.174.951-2.125 2.125-2.125h11c1.174 0 2.125.951 2.125 2.125V7.5H2.375zm2.883-.441a.625.625 0 1 0-1.25 0 .625.625 0 0 0 1.25 0m1.375.625a.625.625 0 1 0 0-1.25.625.625 0 0 0 0 1.25m2.625-.625a.625.625 0 1 0-1.25 0 .625.625 0 0 0 1.25 0M2.375 8.6v2.292a4.506 4.506 0 0 1 5.582 4.983H15.5a2.125 2.125 0 0 0 2.125-2.125V8.6z" />
			<path d="M6.944 15.875Q7 15.57 7 15.25a3.5 3.5 0 1 0-.056.625M.875 15.25c0-.345.28-.625.625-.625h1.375V13.25a.625.625 0 1 1 1.25 0v1.375H5.5a.625.625 0 1 1 0 1.25H4.125v1.375a.625.625 0 1 1-1.25 0v-1.375H1.5a.625.625 0 0 1-.625-.625" />
		</>
	),
}

export const browserAddFillIcon: LoadedIconFunction<"fill"> = createIcon(
	"browserAddFill",
	iconDefinition,
	"fill",
)
