/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "3.12 3.12 13.76 13.75",
	svg: (
		<path d="M3.75 12.5c.345 0 .625.28.625.625v1.625c0 .483.392.875.875.875h1.625a.625.625 0 1 1 0 1.25H5.25a2.125 2.125 0 0 1-2.125-2.125v-1.625c0-.345.28-.625.625-.625m12.5 0c.345 0 .625.28.625.625v1.625a2.125 2.125 0 0 1-2.125 2.125h-1.625a.625.625 0 1 1 0-1.25h1.625a.875.875 0 0 0 .875-.875v-1.625c0-.345.28-.625.625-.625M12.5 7.375c.621 0 1.125.504 1.125 1.125v3c0 .621-.504 1.125-1.125 1.125h-5A1.125 1.125 0 0 1 6.375 11.5v-3c0-.621.504-1.125 1.125-1.125zm-4.875 4h4.75v-2.75h-4.75zm-.75-8.25a.625.625 0 1 1 0 1.25H5.25a.875.875 0 0 0-.875.875v1.625a.625.625 0 1 1-1.25 0V5.25c0-1.174.951-2.125 2.125-2.125zm7.875 0c1.174 0 2.125.951 2.125 2.125v1.625a.625.625 0 1 1-1.25 0V5.25a.875.875 0 0 0-.875-.875h-1.625a.625.625 0 1 1 0-1.25z" />
	),
}

export const cardExpandIcon: LoadedIconFunction<"default"> = createIcon(
	"cardExpand",
	iconDefinition,
	"default",
)
