/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "2.37 2.37 11.25 11.25",
	svg: (
		<path d="M3 9.875c.345 0 .625.28.625.625v1c0 .483.392.875.875.875h1a.625.625 0 1 1 0 1.25h-1A2.125 2.125 0 0 1 2.375 11.5v-1c0-.345.28-.625.625-.625m10 0c.345 0 .625.28.625.625v1a2.125 2.125 0 0 1-2.125 2.125h-1a.625.625 0 1 1 0-1.25h1a.875.875 0 0 0 .875-.875v-1c0-.345.28-.625.625-.625m-3.1-4.1c.621 0 1.125.504 1.125 1.125v2.2c0 .621-.504 1.125-1.125 1.126H6.1A1.125 1.125 0 0 1 4.977 9.1V6.9c0-.622.503-1.126 1.125-1.126zm-3.674 3.2h3.55v-1.95h-3.55zm-.726-6.6a.625.625 0 1 1 0 1.25h-1a.875.875 0 0 0-.875.875v1a.625.625 0 1 1-1.25 0v-1c0-1.174.951-2.125 2.125-2.125zm6 0c1.174 0 2.125.951 2.125 2.125v1a.625.625 0 1 1-1.25 0v-1a.875.875 0 0 0-.875-.875h-1a.625.625 0 1 1 0-1.25z" />
	),
}

export const cardExpandSmallIcon: LoadedIconFunction<"small"> = createIcon(
	"cardExpandSmall",
	iconDefinition,
	"small",
)
