/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "0.79 6.4 14.4 3.21",
	svg: (
		<path d="M2.4 6.4a1.6 1.6 0 1 1 0 3.2 1.6 1.6 0 0 1 0-3.2m11.2 0a1.6 1.6 0 1 1 0 3.2 1.6 1.6 0 0 1 0-3.2m-7.9 1a.6.6 0 1 1 0 1.2.6.6 0 0 1 0-1.2m2.3 0a.6.6 0 1 1 0 1.2.6.6 0 0 1 0-1.2m2.3 0a.6.6 0 1 1 0 1.2.6.6 0 0 1 0-1.2" />
	),
}

export const dotsDashSmallIcon: LoadedIconFunction<"small"> = createIcon(
	"dotsDashSmall",
	iconDefinition,
	"small",
)
