/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "2.56 2.34 14.01 15.32",
	svg: (
		<path d="M13.798 2.345a2.765 2.765 0 0 1 0 5.529c-.797 0-1.513-.34-2.018-.879l-3.808 2.2a2.76 2.76 0 0 1 0 1.61l3.807 2.199a2.76 2.76 0 0 1 2.019-.879 2.765 2.765 0 1 1-2.646 1.96l-3.807-2.2c-.505.54-1.22.88-2.018.88a2.765 2.765 0 0 1 0-5.53 2.76 2.76 0 0 1 2.017.877l3.808-2.198a2.766 2.766 0 0 1 2.646-3.57" />
	),
}

export const shareAndroidFillIcon: LoadedIconFunction<"fill"> = createIcon(
	"shareAndroidFill",
	iconDefinition,
	"fill",
)
