/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "1.92 1.75 11.46 12.5",
	svg: (
		<path d="M11.038 1.751A2.337 2.337 0 1 1 9.4 5.753L6.521 7.414c.049.188.078.383.078.586q-.002.303-.077.584L9.4 10.245a2.337 2.337 0 1 1-.623 1.083L5.898 9.666a2.337 2.337 0 1 1-.001-3.333l2.88-1.663a2.3 2.3 0 0 1-.076-.582 2.337 2.337 0 0 1 2.337-2.337m0 9.074a1.087 1.087 0 1 0 0 2.175 1.087 1.087 0 0 0 0-2.175M4.262 6.913a1.087 1.087 0 1 0 0 2.175 1.087 1.087 0 0 0 0-2.175m6.776-3.912a1.087 1.087 0 1 0 0 2.174 1.087 1.087 0 0 0 0-2.174" />
	),
}

export const shareAndroidSmallIcon: LoadedIconFunction<"small"> = createIcon(
	"shareAndroidSmall",
	iconDefinition,
	"small",
)
