/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "1.97 1.97 12.46 12.46",
	svg: (
		<>
			<path d="M7.1 4.475a.625.625 0 0 0-.625.625v1.375H5.1a.625.625 0 1 0 0 1.25h1.375V9.1a.625.625 0 0 0 1.25 0V7.725H9.1a.625.625 0 0 0 0-1.25H7.725V5.1a.625.625 0 0 0-.625-.625" />
			<path d="M7.1 1.975a5.125 5.125 0 1 0 3.155 9.164l3.107 3.107a.625.625 0 1 0 .884-.884l-3.107-3.107A5.125 5.125 0 0 0 7.1 1.975M3.225 7.1a3.875 3.875 0 1 1 7.75 0 3.875 3.875 0 0 1-7.75 0" />
		</>
	),
}

export const magnifyingGlassPlusSmallIcon: LoadedIconFunction<"small"> =
	createIcon("magnifyingGlassPlusSmall", iconDefinition, "small")
