/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "0.5 0.67 15.04 18.83",
	svg: (
		<>
			<path d="M10 .675A2.875 2.875 0 0 0 7.125 3.55v3.6a2.875 2.875 0 0 0 5.75 0v-3.6A2.875 2.875 0 0 0 10 .675M8.375 3.55a1.625 1.625 0 0 1 3.25 0v3.6a1.625 1.625 0 1 1-3.25 0z" />
			<path d="M5.605 9.391a.625.625 0 1 0-1.03.71 6.58 6.58 0 0 0 4.8 2.82v1.929h-.92A4.6 4.6 0 0 1 8.6 16.1h5.451a.625.625 0 1 0 0-1.25h-3.425v-1.93a6.58 6.58 0 0 0 4.8-2.818.625.625 0 0 0-1.03-.71 5.33 5.33 0 0 1-4.393 2.308h-.004a5.33 5.33 0 0 1-4.393-2.309M4 19.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7m-1.969-4.094h1.375v-1.375a.625.625 0 0 1 1.25 0v1.375h1.375a.625.625 0 0 1 0 1.25H4.656v1.375a.625.625 0 1 1-1.25 0v-1.375H2.031a.625.625 0 1 1 0-1.25" />
		</>
	),
}

export const microphonePlusIcon: LoadedIconFunction<"default"> = createIcon(
	"microphonePlus",
	iconDefinition,
	"default",
)
