/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "0.39 0.14 11.98 15.45",
	svg: (
		<>
			<path d="M8 .15a2.3 2.3 0 0 0-2.3 2.3v2.8a2.3 2.3 0 0 0 4.6 0v-2.8A2.3 2.3 0 0 0 8 .15m-1.2 2.3a1.2 1.2 0 0 1 2.4 0v2.8a1.2 1.2 0 1 1-2.4 0z" />
			<path d="M4.634 6.957a.55.55 0 0 0-.905.625 5.19 5.19 0 0 0 3.72 2.214v1.379h-.372q.203.52.253 1.1h3.82a.55.55 0 1 0 0-1.1h-2.6V9.796a5.19 5.19 0 0 0 3.721-2.214.55.55 0 1 0-.905-.625A4.08 4.08 0 0 1 8 8.725a4.08 4.08 0 0 1-3.366-1.768M3.4 15.6a3 3 0 1 0 0-6 3 3 0 0 0 0 6m-1.667-3.5H2.9v-1.166a.5.5 0 1 1 1 0V12.1h1.166a.5.5 0 1 1 0 1H3.9v1.167a.5.5 0 0 1-1 0V13.1H1.733a.5.5 0 0 1 0-1" />
		</>
	),
}

export const microphonePlusSmallIcon: LoadedIconFunction<"small"> = createIcon(
	"microphonePlusSmall",
	iconDefinition,
	"small",
)
