/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "2.37 2.37 15.26 15.25",
	svg: (
		<>
			<path d="M6.375 8.333c0-.345.28-.625.625-.625h6a.625.625 0 1 1 0 1.25H7a.625.625 0 0 1-.625-.625M7 11.042a.625.625 0 1 0 0 1.25h6a.625.625 0 0 0 0-1.25z" />
			<path d="M2.375 10a7.625 7.625 0 1 1 15.25 0 7.625 7.625 0 0 1-15.25 0M10 3.625a6.375 6.375 0 1 0 0 12.75 6.375 6.375 0 0 0 0-12.75" />
		</>
	),
}

export const equalCircleIcon: LoadedIconFunction<"default"> = createIcon(
	"equalCircle",
	iconDefinition,
	"default",
)
