/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "2.37 2.37 15.25 15.26",
	svg: (
		<path d="M10 2.375a7.625 7.625 0 1 0 0 15.25 7.625 7.625 0 0 0 0-15.25m-3.042 8.07a.625.625 0 0 1 .884 0l1.533 1.534V6.513a.625.625 0 1 1 1.25 0v5.466l1.533-1.533a.625.625 0 1 1 .884.883l-2.6 2.6a.625.625 0 0 1-.884 0l-2.6-2.6a.625.625 0 0 1 0-.883" />
	),
}

export const arrowInCircleDownFillIcon: LoadedIconFunction<"fill"> = createIcon(
	"arrowInCircleDownFill",
	iconDefinition,
	"fill",
)
