/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "1.95 1.94 12.11 12.1",
	svg: (
		<path d="M8 1.95a6.05 6.05 0 1 0 0 12.1 6.05 6.05 0 0 0 0-12.1M5.531 8.32a.55.55 0 0 1 .778 0L7.45 9.462V5.21a.55.55 0 1 1 1.1 0v4.252l1.141-1.14a.55.55 0 0 1 .778.777l-2.08 2.08a.55.55 0 0 1-.778 0l-2.08-2.08a.55.55 0 0 1 0-.778" />
	),
}

export const arrowInCircleDownFillSmallIcon: LoadedIconFunction<"fillSmall"> =
	createIcon("arrowInCircleDownFillSmall", iconDefinition, "fillSmall")
