/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "5.37 9.37 9.25 1.25",
	svg: <path d="M6 9.375a.625.625 0 1 0 0 1.25h8a.625.625 0 1 0 0-1.25z" />,
}

export const dashIcon: LoadedIconFunction<"default"> = createIcon(
	"dash",
	iconDefinition,
	"default",
)
