/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "1.41 0.94 13.17 14.1",
	svg: (
		<path d="M3.053 11.57a1.637 1.637 0 0 1-1.636-1.637V6.066c0-.903.733-1.635 1.636-1.636h3.23V2.2a1.25 1.25 0 0 1 2.134-.884l5.8 5.8a1.25 1.25 0 0 1 0 1.768l-5.8 5.8a1.25 1.25 0 0 1-2.133-.884v-2.23zm0-5.89a.39.39 0 0 0-.379.309l-.007.077v3.867l.007.079c.031.15.15.27.301.3l.078.008h4.4a.08.08 0 0 1 .074.049l.007.031v3.4l5.8-5.8-5.8-5.8v3.4a.08.08 0 0 1-.08.08z" />
	),
}

export const arrowShapeRightSmallIcon: LoadedIconFunction<"small"> = createIcon(
	"arrowShapeRightSmall",
	iconDefinition,
	"small",
)
