/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "2.37 2.37 15.26 15.25",
	svg: (
		<>
			<path d="M10 5.125c-.95 0-1.723.393-2.245 1.044-.51.635-.75 1.474-.75 2.346s.24 1.71.75 2.346c.522.65 1.295 1.044 2.245 1.044s1.723-.394 2.245-1.044c.51-.635.75-1.474.75-2.346s-.24-1.711-.75-2.346c-.522-.65-1.294-1.044-2.245-1.044" />
			<path d="M2.375 10a7.625 7.625 0 1 1 15.25 0 7.625 7.625 0 0 1-15.25 0M10 3.625a6.375 6.375 0 0 0-4.087 11.268C6.702 13.495 8.246 12.56 10 12.56s3.298.934 4.087 2.332A6.375 6.375 0 0 0 10 3.626" />
		</>
	),
}

export const personCircleFillIcon: LoadedIconFunction<"fill"> = createIcon(
	"personCircleFill",
	iconDefinition,
	"fill",
)
