/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "1.77 2.77 12.46 11.86",
	svg: (
		<>
			<path d="M12.4 6.975c1.008 0 1.825.817 1.826 1.825v4a1.826 1.826 0 0 1-1.826 1.825H9.6A1.826 1.826 0 0 1 7.776 12.8v-4c0-1.008.818-1.825 1.826-1.825zm-2.8 1.25a.576.576 0 0 0-.575.575v4c0 .317.258.575.576.575h2.8a.576.576 0 0 0 .575-.575v-4a.576.576 0 0 0-.576-.575z" />
			<path d="M12.4 2.774c1.008 0 1.825.818 1.826 1.826v1.73a3.06 3.06 0 0 0-1.25-.55V4.6a.576.576 0 0 0-.576-.576H3.6a.576.576 0 0 0-.575.576v6c0 .317.258.575.576.575h2.924v1.25H3.601A1.825 1.825 0 0 1 1.775 10.6v-6c0-1.008.817-1.825 1.825-1.826z" />
		</>
	),
}

export const rectangleOnRectangleWideSmallIcon: LoadedIconFunction<"small"> =
	createIcon("rectangleOnRectangleWideSmall", iconDefinition, "small")
