/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import type { IconGroup } from "../../iconUtils"
import { createIconGroup } from "../../iconUtils"

export const blockLimitIconGroup: IconGroup<
	"default" | "small" | "fill" | "fillSmall"
> = createIconGroup(
	"blockLimit",
	{
		default: {
			loader: () =>
				import(
					/* webpackChunkName: "icon-blockLimit" */
					"./default.icon"
				),
		},
		small: {
			loader: () =>
				import(
					/* webpackChunkName: "icon-blockLimit" */
					"./small.icon"
				),
		},
		fill: {
			loader: () =>
				import(
					/* webpackChunkName: "icon-blockLimit" */
					"./fill.icon"
				),
		},
		fillSmall: {
			loader: () =>
				import(
					/* webpackChunkName: "icon-blockLimit" */
					"./fillSmall.icon"
				),
		},
	},
	["cube", "block", "limit", "warning", "square"],
)
