/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "2.37 1.62 15.25 16",
	svg: (
		<>
			<path d="M12.083 7.808 10.65 9.241V2.25a.625.625 0 1 0-1.25 0v6.991L7.967 7.808a.625.625 0 0 0-.884.884l2.5 2.5c.244.244.64.244.884 0l2.5-2.5a.625.625 0 0 0-.884-.884" />
			<path d="M4.5 4.875h3.9v-1.25H4.5A2.125 2.125 0 0 0 2.375 5.75v7.5c0 1.174.951 2.125 2.125 2.125H8v1H6.5a.625.625 0 1 0 0 1.25h7a.625.625 0 1 0 0-1.25H12v-1h3.5a2.125 2.125 0 0 0 2.125-2.125v-7.5A2.125 2.125 0 0 0 15.5 3.625h-3.85v1.25h3.85c.483 0 .875.392.875.875v7.5a.875.875 0 0 1-.875.875h-11a.875.875 0 0 1-.875-.875v-7.5c0-.483.392-.875.875-.875" />
		</>
	),
}

export const displayAndArrowDownIcon: LoadedIconFunction<"default"> =
	createIcon("displayAndArrowDown", iconDefinition, "default")
