/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "2.45 2.45 11.11 11.11",
	svg: (
		<path d="M2.45 4.25a1.8 1.8 0 0 1 1.8-1.8h7.5a1.8 1.8 0 0 1 1.8 1.8v.182H2.45zm0 1.182v6.318a1.8 1.8 0 0 0 1.8 1.8h7.5a1.8 1.8 0 0 0 1.8-1.8V5.432zM7.621 7.05a.568.568 0 1 1-1.136 0 .568.568 0 0 1 1.136 0m-.568 2.462a.568.568 0 1 1 0-1.136.568.568 0 0 1 0 1.136m.568 1.326a.568.568 0 1 1-1.136 0 .568.568 0 0 1 1.136 0m1.326-3.22a.568.568 0 1 1 0-1.136.568.568 0 0 1 0 1.136m.568 1.326a.568.568 0 1 1-1.136 0 .568.568 0 0 1 1.136 0m-.568 2.462a.568.568 0 1 1 0-1.136.568.568 0 0 1 0 1.136M11.41 7.05a.568.568 0 1 1-1.136 0 .568.568 0 0 1 1.136 0M5.16 9.512a.568.568 0 1 1 0-1.136.568.568 0 0 1 0 1.136m.568 1.326a.568.568 0 1 1-1.136 0 .568.568 0 0 1 1.136 0m5.114-1.326a.568.568 0 1 1 0-1.136.568.568 0 0 1 0 1.136" />
	),
}

export const viewCalendarFillSmallIcon: LoadedIconFunction<"fillSmall"> =
	createIcon("viewCalendarFillSmall", iconDefinition, "fillSmall")
