/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "2.37 4.12 15.25 14.42",
	svg: (
		<>
			<path d="M7.982 9.883a.245.245 0 0 0-.342.302l2.567 7.06c.077.214.38.217.46.005l.744-1.953 2.745 3.002a.735.735 0 1 0 1.088-.991l-2.802-3.065 1.9-.684a.245.245 0 0 0 .027-.45z" />
			<path d="M2.375 6.25c0-1.174.951-2.125 2.125-2.125h11c1.174 0 2.125.951 2.125 2.125v7.5a2.126 2.126 0 0 1-1.655 2.073l-.85-.93q.21-.114.372-.268h.008a.875.875 0 0 0 .875-.875v-7.5a.875.875 0 0 0-.875-.875h-11a.875.875 0 0 0-.875.875v7.5c0 .483.392.875.875.875h3.117l.455 1.25H4.5a2.125 2.125 0 0 1-2.125-2.125z" />
			<path d="M15.244 17.309a.735.735 0 1 1-1.088.99l-2.745-3.001-.743 1.952a.246.246 0 0 1-.461-.005l-2.567-7.06a.245.245 0 0 1 .342-.302l6.387 3.227a.245.245 0 0 1-.027.45l-1.9.683z" />
		</>
	),
}

export const buttonBlockIcon: LoadedIconFunction<"default"> = createIcon(
	"buttonBlock",
	iconDefinition,
	"default",
)
