/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "2.37 4.12 15.25 14.42",
	svg: (
		<>
			<path d="M2.375 6.25c0-1.174.951-2.125 2.125-2.125h11c1.174 0 2.125.951 2.125 2.125v7.5a2.126 2.126 0 0 1-1.655 2.073l-.85-.93c1.232-.664 1.247-2.498-.057-3.157L8.676 8.51c-1.433-.724-3.037.672-2.481 2.2l1.877 5.165H4.5a2.125 2.125 0 0 1-2.125-2.125z" />
			<path d="M10.668 17.25a.246.246 0 0 1-.461-.005l-2.567-7.06a.246.246 0 0 1 .342-.302l6.387 3.227a.245.245 0 0 1-.027.45l-1.9.683 2.802 3.065a.735.735 0 1 1-1.088.991l-2.745-3.001z" />
		</>
	),
}

export const buttonBlockFillIcon: LoadedIconFunction<"fill"> = createIcon(
	"buttonBlockFill",
	iconDefinition,
	"fill",
)
