/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "4.12 2.37 11.75 15.25",
	svg: (
		<path d="M13.75 17.625a2.125 2.125 0 0 0 2.125-2.125v-11a2.125 2.125 0 0 0-2.125-2.125h-7.5A2.125 2.125 0 0 0 4.125 4.5v11c0 1.174.951 2.125 2.125 2.125zM6.375 7.25c0-1.174.951-2.125 2.125-2.125h.25a.375.375 0 1 1 0 .75H8.5c-.745 0-1.352.593-1.374 1.333A1.375 1.375 0 1 1 8.25 9.375 1.875 1.875 0 0 1 6.375 7.5zm4 0c0-1.174.951-2.125 2.125-2.125h.25a.375.375 0 0 1 0 .75h-.25c-.745 0-1.352.593-1.374 1.333a1.375 1.375 0 1 1 1.124 2.167A1.875 1.875 0 0 1 10.375 7.5zm.175 7a.55.55 0 0 1-.55.55H7.25a.55.55 0 0 1 0-1.1H10a.55.55 0 0 1 .55.55m2.2-1.95h-5.5a.55.55 0 0 1 0-1.1h5.5a.55.55 0 1 1 0 1.1" />
	),
}

export const docWithQuotationMarksFillIcon: LoadedIconFunction<"fill"> =
	createIcon("docWithQuotationMarksFill", iconDefinition, "fill")
