/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "1.77 3.17 12.45 9.65",
	svg: (
		<>
			<path d="M8 5.45a.55.55 0 0 1 .55.55v1.45H10a.55.55 0 1 1 0 1.1H8.55V10a.55.55 0 1 1-1.1 0V8.55H6a.55.55 0 1 1 0-1.1h1.45V6A.55.55 0 0 1 8 5.45" />
			<path d="M12.4 3.175c1.007 0 1.825.817 1.825 1.825v6a1.825 1.825 0 0 1-1.825 1.825H3.6A1.826 1.826 0 0 1 1.775 11V5c0-1.008.818-1.825 1.826-1.825zm-8.8 1.25A.576.576 0 0 0 3.024 5v6c0 .317.258.575.576.575h8.8a.575.575 0 0 0 .575-.575V5a.576.576 0 0 0-.576-.575z" />
		</>
	),
}

export const rectangleWidePlusSmallIcon: LoadedIconFunction<"small"> =
	createIcon("rectangleWidePlusSmall", iconDefinition, "small")
