/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "1.91 0.78 16.18 16.85",
	svg: (
		<path d="M5.87 1.006a.625.625 0 0 1-.079.88L2.94 4.269a.625.625 0 0 1-.802-.96L4.99.927a.625.625 0 0 1 .88.079M10 2.375a7.625 7.625 0 1 0 0 15.25 7.625 7.625 0 0 0 0-15.25m.625 3.35V10c0 .345-.28.625-.625.625H6.4a.625.625 0 1 1 0-1.25h2.975v-3.65a.625.625 0 1 1 1.25 0m3.505-4.719a.625.625 0 0 0 .079.88l2.851 2.383a.625.625 0 1 0 .802-.96L15.01.927a.625.625 0 0 0-.88.079" />
	),
}

export const alarmFillIcon: LoadedIconFunction<"fill"> = createIcon(
	"alarmFill",
	iconDefinition,
	"fill",
)
