/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "1.47 0.57 13.05 13.48",
	svg: (
		<path d="M4.735.772a.55.55 0 0 1-.07.775L2.384 3.453a.55.55 0 1 1-.705-.844L3.959.703a.55.55 0 0 1 .776.07M8 1.95a6.05 6.05 0 1 0 0 12.1 6.05 6.05 0 0 0 0-12.1m.55 2.63V8a.55.55 0 0 1-.55.55H5.12a.55.55 0 1 1 0-1.1h2.33V4.58a.55.55 0 1 1 1.1 0M11.266.772a.55.55 0 0 0 .069.775l2.281 1.906a.55.55 0 0 0 .706-.844L12.04.703a.55.55 0 0 0-.774.07" />
	),
}

export const alarmFillSmallIcon: LoadedIconFunction<"fillSmall"> = createIcon(
	"alarmFillSmall",
	iconDefinition,
	"fillSmall",
)
