/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "3.97 2.68 12.5 14.37",
	svg: (
		<path d="M10.282 3.66a5.39 5.39 0 0 0-5.217-.54l-.711.305A.63.63 0 0 0 3.975 4v12.425a.625.625 0 1 0 1.25 0v-3.913l.333-.142a4.14 4.14 0 0 1 4.007.414 5.39 5.39 0 0 0 5.505.405l1.06-.53a.63.63 0 0 0 .345-.56V4a.625.625 0 0 0-.904-.558l-1.06.53c-1.36.68-2.983.56-4.229-.312" />
	),
}

export const flagFillIcon: LoadedIconFunction<"fill"> = createIcon(
	"flagFill",
	iconDefinition,
	"fill",
)
