/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "3.12 3.12 13.75 13.75",
	svg: (
		<>
			<path d="M12.876 7.982a.625.625 0 1 0-1.072-.644L9.25 11.595 7.815 9.92a.625.625 0 1 0-.95.813l2 2.334a.625.625 0 0 0 1.01-.085z" />
			<path d="M5.25 3.125A2.125 2.125 0 0 0 3.125 5.25v9.5c0 1.174.951 2.125 2.125 2.125h9.5a2.125 2.125 0 0 0 2.125-2.125v-9.5a2.125 2.125 0 0 0-2.125-2.125zM4.375 5.25c0-.483.392-.875.875-.875h9.5c.483 0 .875.392.875.875v9.5a.875.875 0 0 1-.875.875h-9.5a.875.875 0 0 1-.875-.875z" />
		</>
	),
}

export const checkmarkSquareIcon: LoadedIconFunction<"default"> = createIcon(
	"checkmarkSquare",
	iconDefinition,
	"default",
)
