/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "2.45 2.45 11.11 11.11",
	svg: (
		<path d="M2.45 4.25a1.8 1.8 0 0 1 1.8-1.8h7.5a1.8 1.8 0 0 1 1.8 1.8v7.5a1.8 1.8 0 0 1-1.8 1.8h-7.5a1.8 1.8 0 0 1-1.8-1.8zm7.872 2.133a.55.55 0 0 0-.944-.566L7.371 9.163 6.268 7.875a.55.55 0 1 0-.836.716l1.6 1.867a.55.55 0 0 0 .89-.075z" />
	),
}

export const checkmarkSquareFillSmallIcon: LoadedIconFunction<"fillSmall"> =
	createIcon("checkmarkSquareFillSmall", iconDefinition, "fillSmall")
