/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "1.25 2.37 14.63 17.63",
	svg: (
		<>
			<path d="M6.25 2.375h3.7V6.25A2.05 2.05 0 0 0 12 8.3h3.875v7.2a2.125 2.125 0 0 1-2.125 2.125H9.211q.137-.541.139-1.125a4.6 4.6 0 0 0-5.225-4.558V4.5c0-1.174.951-2.125 2.125-2.125" />
			<path d="M15.665 7.2a2.1 2.1 0 0 0-.412-.581L11.63 2.997c-.17-.17-.367-.31-.581-.412V6.25c0 .525.425.95.95.95zM1.25 16.5a3.5 3.5 0 1 0 7 0 3.5 3.5 0 0 0-7 0m2.844-1.969a.625.625 0 0 1 1.25 0v2a.625.625 0 0 1-.625.625h-2a.625.625 0 1 1 0-1.25h1.375z" />
		</>
	),
}

export const docBadgeClockFillIcon: LoadedIconFunction<"fill"> = createIcon(
	"docBadgeClockFill",
	iconDefinition,
	"fill",
)
