/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "0.99 2.2 11.56 13.8",
	svg: (
		<>
			<path d="M5.125 2.2h2.679v3.006a1.7 1.7 0 0 0 1.7 1.7h3.046v5.219c0 .925-.75 1.675-1.675 1.675H7.862q.08-.388.08-.8A3.943 3.943 0 0 0 3.45 9.095v-5.22c0-.925.75-1.675 1.675-1.675" />
			<path d="M5.677 10.512A2.99 2.99 0 0 1 7 13a3 3 0 1 1-1.323-2.488m-2.177.821V12.5H2.334a.5.5 0 0 0 0 1H4a.5.5 0 0 0 .5-.5v-1.667a.5.5 0 0 0-1 0m8.56-5.926c.145.145.261.315.344.5h-2.9a.7.7 0 0 1-.7-.7V2.328c.2.083.383.205.54.362z" />
		</>
	),
}

export const docBadgeClockFillSmallIcon: LoadedIconFunction<"fillSmall"> =
	createIcon("docBadgeClockFillSmall", iconDefinition, "fillSmall")
