/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import type { IconGroup } from "../../iconUtils"
import { createIconGroup } from "../../iconUtils"

export const docBadgeClockIconGroup: IconGroup<
	"default" | "small" | "fill" | "fillSmall"
> = createIconGroup(
	"docBadgeClock",
	{
		default: {
			loader: () =>
				import(
					/* webpackChunkName: "icon-docBadgeClock" */
					"./default.icon"
				),
		},
		small: {
			loader: () =>
				import(
					/* webpackChunkName: "icon-docBadgeClock" */
					"./small.icon"
				),
		},
		fill: {
			loader: () =>
				import(
					/* webpackChunkName: "icon-docBadgeClock" */
					"./fill.icon"
				),
		},
		fillSmall: {
			loader: () =>
				import(
					/* webpackChunkName: "icon-docBadgeClock" */
					"./fillSmall.icon"
				),
		},
	},
	[
		"IPR",
		"initial page render",
		"recent document",
		"recent page",
		"recents",
		"page history",
	],
)
