/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "3.12 3.12 15.25 15.57",
	svg: (
		<>
			<path
				fillRule="evenodd"
				d="M3.125 4.75c0-.897.728-1.625 1.625-1.625h10.5c.898 0 1.625.728 1.625 1.625v1.57c0 .676-.413 1.256-1 1.5v3.904l-1.25 2.084V7.945h-9.25v7.305c0 .207.168.375.375.375h4.329c.05.338.192.667.431.945l.261.305H5.75a1.625 1.625 0 0 1-1.625-1.625V7.82c-.587-.244-1-.824-1-1.5zm12.5 1.57V4.75a.375.375 0 0 0-.375-.375H4.75a.375.375 0 0 0-.375.375v1.57c0 .205.164.372.369.375h10.512a.375.375 0 0 0 .369-.375"
				clipRule="evenodd"
			/>
			<path d="M8 9.875a.625.625 0 1 0 0 1.25h4a.625.625 0 1 0 0-1.25zm10.282 2.697a.625.625 0 0 0-1.072-.644l-3.041 5.07-1.76-2.055a.625.625 0 1 0-.95.814l2.325 2.712a.625.625 0 0 0 1.01-.085z" />
		</>
	),
}

export const archiveBoxCheckIcon: LoadedIconFunction<"default"> = createIcon(
	"archiveBoxCheck",
	iconDefinition,
	"default",
)
