/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "2.37 4.12 15.26 11.75",
	svg: (
		<path d="M15.5 4.125c.36 0 .698.09.994.247L10 10.866 3.505 4.372c.297-.158.636-.247.995-.247zM2.375 6.25c0-.36.09-.698.247-.995L7.366 10l-4.744 4.744a2.1 2.1 0 0 1-.247-.994zm1.13 9.378c.297.158.636.247.995.247h11c.36 0 .698-.09.995-.247l-4.745-4.744-1.308 1.308a.625.625 0 0 1-.884 0L8.25 10.884zM12.634 10l4.744 4.744c.158-.296.247-.635.247-.994v-7.5c0-.36-.09-.698-.247-.994z" />
	),
}

export const envelopeFillIcon: LoadedIconFunction<"fill"> = createIcon(
	"envelopeFill",
	iconDefinition,
	"fill",
)
