/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "0.97 2.17 18.03 15.93",
	svg: (
		<>
			<path d="M17.88 11.39a.626.626 0 0 1 1.028.712 6.58 6.58 0 0 1-4.8 2.815v1.933h3.425l.126.012a.625.625 0 0 1 0 1.225l-.126.013h-8.1a.625.625 0 0 1 0-1.25h3.425v-1.933a6.58 6.58 0 0 1-4.566-2.5l-.232-.315-.061-.112a.626.626 0 0 1 1.008-.695l.082.096.187.255a5.33 5.33 0 0 0 4.208 2.053 5.33 5.33 0 0 0 4.396-2.308m-11.042-.349a1.88 1.88 0 0 0-.056 1.25H1.606a.625.625 0 0 1 0-1.25z" />
			<path d="M13.483 2.175a2.875 2.875 0 0 1 2.875 2.875v4.1a2.875 2.875 0 0 1-5.75 0v-4.1a2.875 2.875 0 0 1 2.875-2.875M9.36 8.958H1.605a.625.625 0 1 1 0-1.25H9.36zm.17-4.583c-.11.372-.17.767-.17 1.175v.075H1.605a.625.625 0 1 1 0-1.25z" />
		</>
	),
}

export const microphoneTextFillIcon: LoadedIconFunction<"fill"> = createIcon(
	"microphoneTextFill",
	iconDefinition,
	"fill",
)
