/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "1.95 3.3 16.1 14.08",
	svg: (
		<>
			<path d="M4.075 3.3A2.125 2.125 0 0 0 1.95 5.425V16.75c0 .345.28.625.625.625h2.6V13.6a.55.55 0 0 1 .55-.55h3.6a.55.55 0 0 1 .55.55v3.775H13.1V5.425A2.125 2.125 0 0 0 10.975 3.3zm1.875 4a.675.675 0 1 1 0-1.35.675.675 0 0 1 0 1.35m.675 1.575a.675.675 0 1 1-1.35 0 .675.675 0 0 1 1.35 0M5.95 11.8a.675.675 0 1 1 0-1.35.675.675 0 0 1 0 1.35m3.825-5.175a.675.675 0 1 1-1.35 0 .675.675 0 0 1 1.35 0M9.1 9.55a.675.675 0 1 1 0-1.35.675.675 0 0 1 0 1.35m.675 1.575a.675.675 0 1 1-1.35 0 .675.675 0 0 1 1.35 0" />
			<path d="M8.775 17.375h-2.5V14.15h2.5zm5.425 0v-8.45h1.725c1.174 0 2.125.951 2.125 2.125v5.7c0 .345-.28.625-.625.625zm1.82-4.675a.675.675 0 1 0 0-1.35.675.675 0 0 0 0 1.35m.675 1.575a.675.675 0 1 0-1.35 0 .675.675 0 0 0 1.35 0" />
		</>
	),
}

export const teamspaceFillIcon: LoadedIconFunction<"fill"> = createIcon(
	"teamspaceFill",
	iconDefinition,
	"fill",
)
