/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "0.97 2.72 18.06 14.56",
	svg: (
		<path d="M3.893 2.875a.626.626 0 0 1 .79-.02l.091.088.128.148.015.033.072.105 11.27 13.148a.623.623 0 0 1-1.033.68l-1.616-1.884c-1.12.408-2.338.633-3.61.633-3.757 0-7.049-1.946-8.707-4.843l-.155-.283a1.46 1.46 0 0 1 0-1.359l.155-.283c.89-1.554 2.25-2.834 3.898-3.687L3.825 3.757l-.072-.105a.626.626 0 0 1 .14-.777M7.41 7.941a3.3 3.3 0 0 0-.717 2.056l.004.17A3.307 3.307 0 0 0 9.83 13.3l.17.004c.595 0 1.151-.161 1.634-.437l-1.52-1.773a1.104 1.104 0 0 1-1.18-1.377zM10 4.194c3.878 0 7.26 2.075 8.862 5.127l.074.164c.125.332.125.7 0 1.032l-.074.163a9.3 9.3 0 0 1-2.987 3.327l-2.69-3.138a3.3 3.3 0 0 0 .116-.702l.005-.17a3.31 3.31 0 0 0-3.136-3.303L10 6.691a3 3 0 0 0-.377.022L7.682 4.447A10.7 10.7 0 0 1 10 4.194" />
	),
}

export const eyeSlashFillIcon: LoadedIconFunction<"fill"> = createIcon(
	"eyeSlashFill",
	iconDefinition,
	"fill",
)
