/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "0.7 2.19 14.6 11.6",
	svg: (
		<path d="M3.142 2.332a.55.55 0 0 1 .695-.017l.081.077.227.264.008.01 8.772 10.235.057.082a.551.551 0 0 1-.819.701l-.08-.076-1.18-1.376A8.5 8.5 0 0 1 8 12.74c-3.027 0-5.685-1.569-7.026-3.911L.848 8.6a1.29 1.29 0 0 1 0-1.199l.126-.228c.705-1.233 1.776-2.251 3.073-2.94l-.965-1.125-.063-.091a.55.55 0 0 1 .123-.685m2.77 4.078a2.6 2.6 0 0 0-.537 1.588l.014.269a2.626 2.626 0 0 0 2.343 2.343l.268.014c.453 0 .878-.118 1.25-.32L8.023 8.872 8 8.874a.875.875 0 0 1-.861-1.032zM8 3.26c3.125 0 5.857 1.673 7.153 4.141l.064.144c.11.293.11.617 0 .91l-.065.145a7.5 7.5 0 0 1-2.255 2.577L10.58 8.475q.02-.103.031-.208l.014-.269A2.626 2.626 0 0 0 8 5.372l-.077.002-1.66-1.937A8.6 8.6 0 0 1 8 3.261" />
	),
}

export const eyeSlashFillSmallIcon: LoadedIconFunction<"fillSmall"> =
	createIcon("eyeSlashFillSmall", iconDefinition, "fillSmall")
