/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "3.48 3.92 13.04 12.85",
	svg: (
		<path d="M3.483 4.55c0-.345.28-.625.625-.625h3.5a.625.625 0 1 1 0 1.25H5.617L8.86 8.42A6 6 0 0 1 10 10.007a6 6 0 0 1 1.14-1.588l3.243-3.244h-1.99a.625.625 0 1 1 0-1.25h3.5c.344 0 .624.28.624.625v3.5a.625.625 0 0 1-1.25 0V6.06l-3.243 3.244a4.78 4.78 0 0 0-1.399 3.358v4.108h-1.25v-4.108a4.78 4.78 0 0 0-1.398-3.358L4.733 6.059V8.05a.625.625 0 1 1-1.25 0z" />
	),
}

export const arrowBranchIcon: LoadedIconFunction<"default"> = createIcon(
	"arrowBranch",
	iconDefinition,
	"default",
)
