/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "3.23 3.67 13.54 13.1",
	svg: (
		<path d="M3.233 4.55c0-.483.392-.875.875-.875h3.5a.875.875 0 1 1 0 1.75H6.22l2.817 2.817c.375.375.698.792.963 1.24.266-.448.588-.865.963-1.24l2.817-2.817h-1.388a.875.875 0 1 1 0-1.75h3.5c.483 0 .875.392.875.875v3.5a.875.875 0 0 1-1.75 0V6.662L12.2 9.48a4.53 4.53 0 0 0-1.325 3.177v4.113h-1.75v-4.113A4.53 4.53 0 0 0 7.8 9.48L4.983 6.662V8.05a.875.875 0 1 1-1.75 0z" />
	),
}

export const arrowBranchFillIcon: LoadedIconFunction<"fill"> = createIcon(
	"arrowBranchFill",
	iconDefinition,
	"fill",
)
