/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "2.66 3.01 10.68 10.48",
	svg: (
		<path d="M3.286 3.015a.625.625 0 0 0-.625.625v2.8a.625.625 0 0 0 1.25 0V5.15l2.382 2.38a3.7 3.7 0 0 1 1.082 2.607v3.277c0 .042.034.075.075.075h1.1a.075.075 0 0 0 .075-.075v-3.277A3.7 3.7 0 0 1 9.707 7.53l2.382-2.382V6.44a.625.625 0 1 0 1.25 0v-2.8a.625.625 0 0 0-.625-.625h-2.8a.625.625 0 0 0 0 1.25h1.29l-2.38 2.382A5 5 0 0 0 8 7.737a5 5 0 0 0-.823-1.09L4.795 4.265h1.291a.625.625 0 0 0 0-1.25z" />
	),
}

export const arrowBranchSmallIcon: LoadedIconFunction<"small"> = createIcon(
	"arrowBranchSmall",
	iconDefinition,
	"small",
)
