/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "1.89 1.89 12.21 12.21",
	svg: (
		<>
			<path d="M10.558 6.568a.44.44 0 0 1 .553.056l.902.902a.44.44 0 0 1-.622.622l-.15-.15V8a3.24 3.24 0 0 1-5.446 2.375.44.44 0 0 1 .599-.646A2.36 2.36 0 0 0 10.36 8l-.15.15a.441.441 0 0 1-.623-.623l.902-.902zM8 4.76a3.23 3.23 0 0 1 2.205.865.44.44 0 0 1-.599.646A2.36 2.36 0 0 0 5.64 8l.15-.15a.441.441 0 0 1 .623.623l-.902.902-.069.056a.44.44 0 0 1-.553-.056l-.902-.902a.44.44 0 0 1 .622-.622l.15.15V8A3.24 3.24 0 0 1 8 4.76" />
			<path d="M8 1.9a6.1 6.1 0 1 1 0 12.202A6.1 6.1 0 0 1 8 1.9m0 1a5.1 5.1 0 1 0 0 10.2A5.1 5.1 0 0 0 8 2.9" />
		</>
	),
}

export const arrowsCircleinCircleSmallIcon: LoadedIconFunction<"small"> =
	createIcon("arrowsCircleinCircleSmall", iconDefinition, "small")
