/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "2.85 2.2 10.29 11.6",
	svg: (
		<path d="M7.875 2.218a.55.55 0 0 1 .37.043l.962.481a7.3 7.3 0 0 0 3.277.774h.11l.11.01c.25.052.437.272.437.537v4.334a4.92 4.92 0 0 1-2.984 4.523l-1.941.833a.55.55 0 0 1-.432 0l-1.941-.833a4.92 4.92 0 0 1-2.984-4.523V4.063c0-.302.245-.547.547-.547h.11a7.3 7.3 0 0 0 3.277-.774l.963-.481zm.126 7.432a.65.65 0 0 0-.639.773l.01.038.024.077.019.04a.6.6 0 0 0 .11.163l.028.03a.7.7 0 0 0 .184.122l.012.005q.057.026.12.04L8 10.95a1 1 0 0 0 .123-.013l.038-.01.08-.025.037-.018a.7.7 0 0 0 .163-.11l.03-.028a1 1 0 0 0 .072-.092.7.7 0 0 0 .095-.223l.012-.131a.65.65 0 0 0-.649-.65M8 4.95a.55.55 0 0 0-.55.55V8a.55.55 0 1 0 1.1 0V5.5A.55.55 0 0 0 8 4.95" />
	),
}

export const exclamationShieldFillSmallIcon: LoadedIconFunction<"fillSmall"> =
	createIcon("exclamationShieldFillSmall", iconDefinition, "fillSmall")
