/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "1.12 5.93 17.75 8.14",
	svg: (
		<path d="M17.125 10c0-1.99-2.349-3.05-3.84-1.732L11.32 10l1.963 1.732c1.492 1.318 3.841.258 3.841-1.732m-14.25 0c0 1.99 2.349 3.05 3.84 1.732L8.679 10 6.716 8.268C5.224 6.95 2.875 8.01 2.875 10m16 0c0 3.497-4.127 5.359-6.749 3.044L10 11.167l-2.126 1.877c-2.622 2.315-6.749.453-6.749-3.044 0-3.498 4.127-5.359 6.749-3.044L10 8.832l2.126-1.876c2.622-2.315 6.749-.454 6.749 3.044" />
	),
}

export const infinityFillIcon: LoadedIconFunction<"fill"> = createIcon(
	"infinityFill",
	iconDefinition,
	"fill",
)
