/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "2.24 2.24 11.5 11.51",
	svg: (
		<>
			<path d="M12.25 5.8a.75.75 0 0 0 1.5 0V4.6a2.35 2.35 0 0 0-2.35-2.35h-1.2a.75.75 0 0 0 0 1.5h1.2c.47 0 .85.38.85.85zm-8.5 4.4a.75.75 0 0 0-1.5 0v1.2a2.35 2.35 0 0 0 2.35 2.35h1.2a.75.75 0 0 0 0-1.5H4.6a.85.85 0 0 1-.85-.85zm5.7 2.8a.75.75 0 0 1 .75-.75h1.2c.47 0 .85-.38.85-.85v-1.2a.75.75 0 1 1 1.5 0v1.2a2.35 2.35 0 0 1-2.35 2.35h-1.2a.75.75 0 0 1-.75-.75m-5.7-7.2a.75.75 0 0 1-1.5 0V4.6A2.35 2.35 0 0 1 4.6 2.25h1.2a.75.75 0 0 1 0 1.5H4.6a.85.85 0 0 0-.85.85z" />
			<path d="M4.975 5.6c0-.787.638-1.425 1.425-1.425h3.2c.787 0 1.425.638 1.425 1.425v4.8c0 .787-.638 1.425-1.425 1.425H6.4A1.425 1.425 0 0 1 4.975 10.4zM6.4 5.425a.175.175 0 0 0-.175.175v.893H7.56V5.425zm2.04 0v1.068h1.335V5.6a.175.175 0 0 0-.175-.175zm0 1.948v1.254h1.335V7.373zm-.88 0H6.225v1.254H7.56zm0 2.134H6.225v.893c0 .097.078.175.175.175h1.16zm.88 1.068H9.6a.175.175 0 0 0 .175-.175v-.893H8.44z" />
		</>
	),
}

export const databaseEmbedFillSmallIcon: LoadedIconFunction<"fillSmall"> =
	createIcon("databaseEmbedFillSmall", iconDefinition, "fillSmall")
