/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 17 16",
	fittedViewBox: "-0.02 1.74 16.11 12.51",
	svg: (
		<path d="m3.303 8.778.523-.522a.75.75 0 0 1 1.06 1.06L3.083 11.12a.75.75 0 0 1-1.06 0L.22 9.316a.75.75 0 1 1 1.06-1.06l.523.522V8a6.25 6.25 0 0 1 9.752-5.178.75.75 0 1 1-.842 1.242A4.75 4.75 0 0 0 3.303 8zm11-1.556.523.522a.75.75 0 0 0 1.06-1.06L14.085 4.88a.75.75 0 0 0-1.061 0L11.22 6.684a.75.75 0 0 0 1.06 1.06l.523-.522V8a4.75 4.75 0 0 1-7.41 3.936.75.75 0 1 0-.841 1.242A6.25 6.25 0 0 0 14.303 8z" />
	),
}

export const arrowCircleLoopBackwardFillSmallIcon: LoadedIconFunction<"fillSmall"> =
	createIcon("arrowCircleLoopBackwardFillSmall", iconDefinition, "fillSmall")
