/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "2.48 1.98 15.03 16.04",
	svg: (
		<>
			<path d="m4.238 9.384 7.157-7.157a.865.865 0 0 1 1.224.014c.341.342.348.89.014 1.224l-7.157 7.157h2.978a.875.875 0 0 1 0 1.75h-5.09a.875.875 0 0 1-.876-.875V6.406a.875.875 0 1 1 1.75 0z" />
			<path d="M14.524 9.375h-2.978a.875.875 0 0 1 0-1.75h5.09c.484 0 .876.392.876.875v5.091a.875.875 0 0 1-1.75 0v-2.978l-7.154 7.154a.867.867 0 0 1-1.227-.011.867.867 0 0 1-.01-1.227z" />
		</>
	),
}

export const arrowDiagonalDownLeftUpRightFillIcon: LoadedIconFunction<"fill"> =
	createIcon("arrowDiagonalDownLeftUpRightFill", iconDefinition, "fill")
