/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "2.55 2.19 10.9 11.61",
	svg: (
		<path d="M7.122 2.221a.75.75 0 0 1 .608.87l-.437 2.48h2.23l.482-2.741a.75.75 0 1 1 1.477.26l-.436 2.48h1.65a.75.75 0 0 1 0 1.5H10.78l-.327 1.86h1.65a.75.75 0 0 1 0 1.5h-1.915l-.482 2.74a.75.75 0 1 1-1.478-.26l.437-2.48H6.437l-.483 2.74a.75.75 0 1 1-1.477-.26l.437-2.48h-1.61a.75.75 0 0 1 0-1.5h1.874l.328-1.86h-1.61a.75.75 0 0 1 0-1.5H5.77l.483-2.74a.75.75 0 0 1 .869-.609m1.808 6.71.328-1.86H7.03l-.328 1.86z" />
	),
}

export const numberFillSmallIcon: LoadedIconFunction<"fillSmall"> = createIcon(
	"numberFillSmall",
	iconDefinition,
	"fillSmall",
)
