/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "1.87 2.57 12.26 11.2",
	svg: (
		<path d="M6.182 4.729a2.154 2.154 0 1 1-4.307 0 2.154 2.154 0 0 1 4.307 0m.471 0a.5.5 0 0 1 .5-.5h.076a.5.5 0 0 1 0 1h-.076a.5.5 0 0 1-.5-.5m1.597 0a.5.5 0 0 1 .5-.5h.075a.5.5 0 0 1 0 1H8.75a.5.5 0 0 1-.5-.5M5.324 7.02a.5.5 0 0 1 .683.182l.038.066a.5.5 0 1 1-.865.501l-.038-.065a.5.5 0 0 1 .182-.684m5.33 0a.5.5 0 0 1 .182.684l-.038.065a.5.5 0 0 1-.865-.5l.038-.067a.5.5 0 0 1 .683-.182M6.123 8.399a.5.5 0 0 1 .683.182l.038.066a.5.5 0 1 1-.866.5l-.038-.065a.5.5 0 0 1 .183-.683m3.733 0a.5.5 0 0 1 .182.683L10 9.148a.5.5 0 1 1-.866-.501l.038-.066a.5.5 0 0 1 .684-.182m4.27-3.67a2.154 2.154 0 1 1-4.308 0 2.154 2.154 0 0 1 4.308 0m-3.972 6.892a2.154 2.154 0 1 1-4.308 0 2.154 2.154 0 0 1 4.308 0" />
	),
}

export const integrationFillSmallIcon: LoadedIconFunction<"fillSmall"> =
	createIcon("integrationFillSmall", iconDefinition, "fillSmall")
