import { IconGrid } from "./icon-grid";
import {
  addSquareRoundedIcon,
  addSquareRoundedFillIcon,
  addSquareRoundedFillSmallIcon,
  addSquareRoundedSmallIcon,
  airplaneIcon,
  alarmIcon,
  alignCenterIcon,
  alignLeftIcon,
  alignRightIcon,
  archiveBoxIcon,
  archiveBoxCheckIcon,
  arrowCaretDownIcon,
  arrowCaretLeftIcon,
  arrowCaretRightIcon,
  arrowCaretUpIcon,
  arrowChevronSingleDownIcon,
  arrowChevronSingleLeftIcon,
  arrowChevronSingleRightIcon,
  arrowChevronSingleUpIcon,
  arrowCircleCheckIcon,
  arrowCircleLoopForwardIcon,
  arrowStraightDownIcon,
  arrowStraightLeftIcon,
  arrowStraightRightIcon,
  arrowStraightUpIcon,
  bellIcon,
  bellSlashIcon,
  bookIcon,
  bookmarkIcon,
  briefcaseIcon,
  clockIcon,
  ellipsisIcon,
  ellipsisVerticalIcon,
  envelopeIcon,
  envelopeOpenIcon,
  eyeIcon,
  eyeSlashIcon,
  filterIcon,
  flagIcon,
  folderIcon,
  gearIcon,
  globeIcon,
  heartIcon,
  homeIcon,
  inboxIcon,
  infoCircleIcon,
  keyIcon,
  layoutIcon,
  linkIcon,
  listBulletIcon,
  listNumberIcon,
  lockIcon,
  lockOpenIcon,
  magicWandIcon,
  magnifyingGlassIcon,
  mailIcon,
  mapIcon,
  mapPinIcon,
  mediaPlayIcon,
  mediaPauseIcon,
  menuIcon,
  microphoneIcon,
  pageIcon,
  pencilIcon,
  personIcon,
  pinIcon,
  plusIcon,
  starIcon,
  trashIcon,
  filterCircleIcon,
  bookClosedIcon,
  lightBulbBrightIcon,
  lightningIcon,
  linkBadgePlusIcon,
  leafIcon,
  medalIcon,
  megaphoneIcon,
  newspaperIcon,
  keyboardIcon,
  globeAmericasIcon,
  figureRunIcon,
  graduationCapIcon,
  handbagIcon,
  handWaveIcon,
  hourglassIcon,
} from "notion-shadcn/icons";

const icons = [
  { name: "addSquareRounded", variant: "default", icon: addSquareRoundedIcon },
  { name: "addSquareRounded", variant: "fill", icon: addSquareRoundedFillIcon },
  { name: "addSquareRounded", variant: "fillSmall", icon: addSquareRoundedFillSmallIcon },
  { name: "addSquareRounded", variant: "small", icon: addSquareRoundedSmallIcon },
  { name: "airplane", variant: "default", icon: airplaneIcon },
  { name: "alarm", variant: "default", icon: alarmIcon },
  { name: "alignCenter", variant: "default", icon: alignCenterIcon },
  { name: "alignLeft", variant: "default", icon: alignLeftIcon },
  { name: "alignRight", variant: "default", icon: alignRightIcon },
  { name: "archiveBox", variant: "default", icon: archiveBoxIcon },
  { name: "archiveBoxCheck", variant: "default", icon: archiveBoxCheckIcon },
  { name: "arrowCaretDown", variant: "default", icon: arrowCaretDownIcon },
  { name: "arrowCaretLeft", variant: "default", icon: arrowCaretLeftIcon },
  { name: "arrowCaretRight", variant: "default", icon: arrowCaretRightIcon },
  { name: "arrowCaretUp", variant: "default", icon: arrowCaretUpIcon },
  { name: "arrowChevronDown", variant: "default", icon: arrowChevronSingleDownIcon },
  { name: "arrowChevronLeft", variant: "default", icon: arrowChevronSingleLeftIcon },
  { name: "arrowChevronRight", variant: "default", icon: arrowChevronSingleRightIcon },
  { name: "arrowChevronUp", variant: "default", icon: arrowChevronSingleUpIcon },
  { name: "arrowCircleCheck", variant: "default", icon: arrowCircleCheckIcon },
  { name: "arrowCircleLoop", variant: "default", icon: arrowCircleLoopForwardIcon },
  { name: "arrowDown", variant: "default", icon: arrowStraightDownIcon },
  { name: "arrowLeft", variant: "default", icon: arrowStraightLeftIcon },
  { name: "arrowRight", variant: "default", icon: arrowStraightRightIcon },
  { name: "arrowUp", variant: "default", icon: arrowStraightUpIcon },
  { name: "bell", variant: "default", icon: bellIcon },
  { name: "bellSlash", variant: "default", icon: bellSlashIcon },
  { name: "book", variant: "default", icon: bookIcon },
  { name: "bookClosed", variant: "default", icon: bookClosedIcon },
  { name: "bookmark", variant: "default", icon: bookmarkIcon },
  { name: "briefcase", variant: "default", icon: briefcaseIcon },
  { name: "clock", variant: "default", icon: clockIcon },
  { name: "ellipsis", variant: "default", icon: ellipsisIcon },
  { name: "ellipsisVertical", variant: "default", icon: ellipsisVerticalIcon },
  { name: "envelope", variant: "default", icon: envelopeIcon },
  { name: "envelopeOpen", variant: "default", icon: envelopeOpenIcon },
  { name: "eye", variant: "default", icon: eyeIcon },
  { name: "eyeSlash", variant: "default", icon: eyeSlashIcon },
  { name: "figureRun", variant: "default", icon: figureRunIcon },
  { name: "filter", variant: "default", icon: filterIcon },
  { name: "filterCircle", variant: "default", icon: filterCircleIcon },
  { name: "flag", variant: "default", icon: flagIcon },
  { name: "folder", variant: "default", icon: folderIcon },
  { name: "gear", variant: "default", icon: gearIcon },
  { name: "globe", variant: "default", icon: globeIcon },
  { name: "globeAmericas", variant: "default", icon: globeAmericasIcon },
  { name: "graduationCap", variant: "default", icon: graduationCapIcon },
  { name: "handbag", variant: "default", icon: handbagIcon },
  { name: "handWave", variant: "default", icon: handWaveIcon },
  { name: "heart", variant: "default", icon: heartIcon },
  { name: "home", variant: "default", icon: homeIcon },
  { name: "hourglass", variant: "default", icon: hourglassIcon },
  { name: "inbox", variant: "default", icon: inboxIcon },
  { name: "infoCircle", variant: "default", icon: infoCircleIcon },
  { name: "key", variant: "default", icon: keyIcon },
  { name: "keyboard", variant: "default", icon: keyboardIcon },
  { name: "layout", variant: "default", icon: layoutIcon },
  { name: "leaf", variant: "default", icon: leafIcon },
  { name: "lightBulb", variant: "default", icon: lightBulbBrightIcon },
  { name: "lightning", variant: "default", icon: lightningIcon },
  { name: "link", variant: "default", icon: linkIcon },
  { name: "linkBadgePlus", variant: "default", icon: linkBadgePlusIcon },
  { name: "listBullet", variant: "default", icon: listBulletIcon },
  { name: "listNumber", variant: "default", icon: listNumberIcon },
  { name: "lock", variant: "default", icon: lockIcon },
  { name: "lockOpen", variant: "default", icon: lockOpenIcon },
  { name: "magicWand", variant: "default", icon: magicWandIcon },
  { name: "magnifyingGlass", variant: "default", icon: magnifyingGlassIcon },
  { name: "mail", variant: "default", icon: mailIcon },
  { name: "map", variant: "default", icon: mapIcon },
  { name: "mapPin", variant: "default", icon: mapPinIcon },
  { name: "medal", variant: "default", icon: medalIcon },
  { name: "mediaPlay", variant: "default", icon: mediaPlayIcon },
  { name: "mediaPause", variant: "default", icon: mediaPauseIcon },
  { name: "megaphone", variant: "default", icon: megaphoneIcon },
  { name: "menu", variant: "default", icon: menuIcon },
  { name: "microphone", variant: "default", icon: microphoneIcon },
  { name: "newspaper", variant: "default", icon: newspaperIcon },
  { name: "page", variant: "default", icon: pageIcon },
  { name: "pencil", variant: "default", icon: pencilIcon },
  { name: "person", variant: "default", icon: personIcon },
  { name: "pin", variant: "default", icon: pinIcon },
  { name: "plus", variant: "default", icon: plusIcon },
  { name: "star", variant: "default", icon: starIcon },
  { name: "trash", variant: "default", icon: trashIcon },
];

export default function IconsPage() {
  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-xl font-semibold">Icons</h1>
        <p className="text-sm text-muted-foreground mt-1">
          NDS icon library — 415 icons × 4 variants. Curated set shown below.
        </p>
      </div>
      <IconGrid icons={icons} />
    </div>
  );
}
