/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "1.57 1.57 16.86 16.86",
	svg: (
		<path d="M9.595 1.724a.624.624 0 0 1 .81 0l2.234 1.904 2.926.233a.625.625 0 0 1 .573.574l.234 2.926 1.904 2.234a.624.624 0 0 1 0 .81l-1.904 2.234-.234 2.926a.625.625 0 0 1-.573.573l-2.926.234-2.234 1.904a.624.624 0 0 1-.81 0L7.36 16.372l-2.926-.234a.625.625 0 0 1-.573-.573l-.234-2.926-1.904-2.234a.625.625 0 0 1 0-.81L3.628 7.36l.233-2.926a.625.625 0 0 1 .574-.573l2.926-.234zm3.21 6.35a.625.625 0 1 0-1.071-.643l-2.512 4.185-1.407-1.642a.625.625 0 1 0-.95.814l1.973 2.3a.625.625 0 0 0 1.01-.085z" />
	),
}

export const badgeCheckFillIcon: LoadedIconFunction<"fill"> = createIcon(
	"badgeCheckFill",
	iconDefinition,
	"fill",
)
