/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "3.45 2.2 9.91 12.62",
	svg: (
		<>
			<path d="M7.804 2.2H5.125c-.925 0-1.675.75-1.675 1.675v8.25c0 .925.75 1.675 1.675 1.675h1.09c.078-.288.23-.56.455-.787l2.012-2.012a1.756 1.756 0 0 1 .627-3.395h3.241v-.7H9.504a1.7 1.7 0 0 1-1.7-1.7z" />
			<path d="M12.404 5.906a1.7 1.7 0 0 0-.345-.5L9.343 2.692a1.7 1.7 0 0 0-.54-.362v2.877a.7.7 0 0 0 .7.7zm.4 7.501a.55.55 0 0 0 .55-.55V9.36a.55.55 0 0 0-.55-.55H9.31a.55.55 0 1 0 0 1.1h2.167l-3.954 3.955a.55.55 0 1 0 .778.777l3.954-3.954v2.168c0 .303.247.55.55.55" />
		</>
	),
}

export const docSendFillSmallIcon: LoadedIconFunction<"fillSmall"> = createIcon(
	"docSendFillSmall",
	iconDefinition,
	"fillSmall",
)
