/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "8 8 4 4",
	svg: <path d="M10 12a2 2 0 1 0 0-4 2 2 0 0 0 0 4" />,
}

export const dotIcon: LoadedIconFunction<"default"> = createIcon(
	"dot",
	iconDefinition,
	"default",
)
