/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "1.97 2.85 12.06 9.98",
	svg: (
		<path d="M5.678 3.038a.625.625 0 1 1 .884.884L4.109 6.375H12.2c1.008 0 1.825.817 1.825 1.825v4a.625.625 0 1 1-1.25 0v-4a.575.575 0 0 0-.575-.575H4.11l2.452 2.453a.625.625 0 0 1-.884.884l-3.52-3.52a.625.625 0 0 1 0-.884z" />
	),
}

export const arrowTurnUpLeftSmallIcon: LoadedIconFunction<"small"> = createIcon(
	"arrowTurnUpLeftSmall",
	iconDefinition,
	"small",
)
