/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "4.04 1.45 7.93 13.11",
	svg: (
		<path d="M4.042 5.36c0-2.166 1.779-3.908 3.957-3.91h.004c2.178.001 3.958 1.743 3.958 3.91 0 .763-.184 1.49-.55 2.11q-.154.26-.3.496c-.18.289-.348.56-.498.856-.222.436-.355.837-.354 1.24a.55.55 0 0 1-.55.55H8.5V8.919a1.5 1.5 0 0 1 .214-.772l.806-1.343a.5.5 0 1 0-.858-.515L8 7.392l-.662-1.104a.5.5 0 0 0-.858.515l.806 1.343c.14.233.214.5.214.772v1.695H6.294a.55.55 0 0 1-.55-.551c0-.403-.132-.804-.354-1.24-.15-.295-.318-.567-.498-.856-.097-.158-.198-.32-.301-.495a4.15 4.15 0 0 1-.55-2.112M6.65 14a.55.55 0 0 1 .55-.55h1.6a.55.55 0 1 1 0 1.1H7.2a.55.55 0 0 1-.55-.55m-.25-2.35a.55.55 0 0 0 0 1.1h3.2a.55.55 0 1 0 0-1.1z" />
	),
}

export const lightBulbBrightFillSmallIcon: LoadedIconFunction<"fillSmall"> =
	createIcon("lightBulbBrightFillSmall", iconDefinition, "fillSmall")
