/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "2.46 2.46 11.08 11.08",
	svg: (
		<path d="M8.912 2.463a.625.625 0 1 0 0 1.25h2.491L8.358 6.758a.625.625 0 1 0 .884.884l3.045-3.045v2.49a.625.625 0 1 0 1.25 0v-4a.625.625 0 0 0-.625-.624zM7.64 8.36a.625.625 0 0 0-.885 0l-3.042 3.043V8.912a.625.625 0 1 0-1.25 0v4c0 .345.28.625.625.625h4a.625.625 0 0 0 0-1.25H4.597l3.042-3.043a.625.625 0 0 0 0-.883" />
	),
}

export const arrowExpandDiagonalBottomLeftToTopRightSmallIcon: LoadedIconFunction<"small"> =
	createIcon(
		"arrowExpandDiagonalBottomLeftToTopRightSmall",
		iconDefinition,
		"small",
	)
