/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "3.8 2.12 15.7 17.38",
	svg: (
		<>
			<path d="M16 12.5a3.5 3.5 0 1 1 0 7 3.5 3.5 0 0 1 0-7m-.031.906a.625.625 0 0 0-.625.625v1.375h-1.375a.625.625 0 0 0 0 1.25h1.375v1.375a.625.625 0 1 0 1.25 0v-1.375h1.375a.625.625 0 0 0 0-1.25h-1.375v-1.375a.625.625 0 0 0-.625-.625" />
			<path d="M10 2.125a6.19 6.19 0 0 1 6.19 6.19v.13a6.3 6.3 0 0 1-.754 2.99 4.6 4.6 0 0 0-3.982 5.273l-.96 1.238a.626.626 0 0 1-.987 0l-4.37-5.627A6.32 6.32 0 0 1 3.81 8.444v-.129A6.19 6.19 0 0 1 10 2.125m0 4.202a2.15 2.15 0 1 0 0 4.3 2.15 2.15 0 0 0 0-4.3" />
		</>
	),
}

export const mapPinPlusFillIcon: LoadedIconFunction<"fill"> = createIcon(
	"mapPinPlusFill",
	iconDefinition,
	"fill",
)
