/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "2.16 3.25 11.84 9.5",
	svg: (
		<path d="M11.25 3.25a.75.75 0 0 0 0 1.5h2a.75.75 0 0 0 0-1.5zm-8.336 8a.75.75 0 0 0 0 1.5H13.25a.75.75 0 0 0 0-1.5zm-.75-1.917a.75.75 0 0 1 .75-.75H13.25a.75.75 0 0 1 0 1.5H2.914a.75.75 0 0 1-.75-.75m9.086-3.416a.75.75 0 0 0 0 1.5h2a.75.75 0 0 0 0-1.5zM2.514 5.6a2.2 2.2 0 0 1 2.2-2.2h.258a.4.4 0 0 1 0 .8h-.258a1.4 1.4 0 0 0-1.397 1.31 1.429 1.429 0 1 1 1.14 2.29 1.943 1.943 0 0 1-1.943-1.943zm4.115 0a2.2 2.2 0 0 1 2.2-2.2h.257a.4.4 0 1 1 0 .8h-.257A1.4 1.4 0 0 0 7.43 5.51 1.429 1.429 0 1 1 8.57 7.8a1.943 1.943 0 0 1-1.94-1.943z" />
	),
}

export const quoteTextFillSmallIcon: LoadedIconFunction<"fillSmall"> =
	createIcon("quoteTextFillSmall", iconDefinition, "fillSmall")
