/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "0.44 5.57 19.12 8.86",
	svg: (
		<path d="M6.473 10.875H1.317a.875.875 0 0 1 0-1.75h5.156L4.432 7.083a.875.875 0 1 1 1.237-1.237L9.205 9.38a.875.875 0 0 1 0 1.238l-3.536 3.535a.875.875 0 1 1-1.237-1.237zm7.058 0 2.042 2.042a.875.875 0 1 1-1.237 1.237L10.8 10.62a.875.875 0 0 1 0-1.238l3.536-3.535a.875.875 0 1 1 1.237 1.237l-2.042 2.042h5.152a.875.875 0 1 1 0 1.75z" />
	),
}

export const arrowCollapseLeftRightFillIcon: LoadedIconFunction<"fill"> =
	createIcon("arrowCollapseLeftRightFill", iconDefinition, "fill")
