/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "4.12 2.37 11.75 15.25",
	svg: (
		<>
			<path d="M10 2.375H6.25A2.125 2.125 0 0 0 4.125 4.5v11c0 1.174.951 2.125 2.125 2.125h7.5a2.125 2.125 0 0 0 2.125-2.125V8.25H12a2 2 0 0 1-2-2zm2.841 9.978a.5.5 0 0 1-.707 0L10.5 10.72v3.767a.5.5 0 1 1-1 0V10.72l-1.634 1.633a.5.5 0 1 1-.707-.707L9.646 9.16a.5.5 0 0 1 .708 0l2.487 2.487a.5.5 0 0 1 0 .707" />
			<path d="M15.688 7.25a2.1 2.1 0 0 0-.435-.631L11.63 2.997a2.1 2.1 0 0 0-.63-.435V6.25a1 1 0 0 0 1 1z" />
		</>
	),
}

export const arrowPageUpFillIcon: LoadedIconFunction<"fill"> = createIcon(
	"arrowPageUpFill",
	iconDefinition,
	"fill",
)
