/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "1.94 3.32 16.21 13.33",
	svg: (
		<path d="M10.064 14.15a1.25 1.25 0 1 1 0 2.5 1.25 1.25 0 0 1 0-2.5M4.607 3.458a.55.55 0 0 1 .776.06l.23.267.004.007 8.769 10.23a.55.55 0 0 1-.839.712l-2.63-3.067a3.82 3.82 0 0 0-3.561 1.026.626.626 0 0 1-.885-.885 5.07 5.07 0 0 1 3.299-1.48L8.385 8.712a6.9 6.9 0 0 0-3.194 1.816.626.626 0 0 1-.885-.885 8.16 8.16 0 0 1 3.188-1.97L6.237 6.206A10 10 0 0 0 2.987 8.4a.626.626 0 0 1-.888-.879 11.3 11.3 0 0 1 3.29-2.305l-.842-.982a.55.55 0 0 1 .06-.776m5.456 3.797c2.246 0 4.283.915 5.756 2.388a.626.626 0 0 1-.883.885 6.9 6.9 0 0 0-3.748-1.93l-1.152-1.343zm0-3.063c3.09 0 5.894 1.258 7.922 3.286a.626.626 0 0 1-.884.884 9.93 9.93 0 0 0-8.523-2.808l-.94-1.095a11 11 0 0 1 2.425-.267" />
	),
}

export const wifiSlashIcon: LoadedIconFunction<"default"> = createIcon(
	"wifiSlash",
	iconDefinition,
	"default",
)
