/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "0.39 2.8 13.36 12.8",
	svg: (
		<>
			<path d="M3.6 9.2a3.2 3.2 0 1 1 0 6.4 3.2 3.2 0 0 1 0-6.4m-.073 4.374a.37.37 0 1 0 0 .741.37.37 0 0 0 0-.74m.063-3.009c-.54 0-1.054.312-1.178.808a.265.265 0 0 0 .514.128c.05-.198.296-.407.664-.407.432 0 .677.27.677.49 0 .132-.082.276-.254.38l-.006.005-.353.241a.93.93 0 0 0-.409.755.265.265 0 0 0 .53 0c0-.116.06-.238.178-.32l.34-.232c.286-.176.502-.47.502-.829 0-.615-.596-1.019-1.205-1.019" />
			<path d="M13.758 10.5a2.05 2.05 0 0 1-2.05 2.05H7.677l.004-.15A4.08 4.08 0 0 0 2.2 8.565V7.25h11.557zm-8-7.694c.316 0 .615.142.814.386l.767.942h4.369a2.05 2.05 0 0 1 2.05 2.05v.066H2.2V3.855c0-.58.47-1.05 1.05-1.05z" />
		</>
	),
}

export const folderQuestionMarkFillSmallIcon: LoadedIconFunction<"fillSmall"> =
	createIcon("folderQuestionMarkFillSmall", iconDefinition, "fillSmall")
