/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 17 16",
	fittedViewBox: "0 3.84 16 8.3",
	svg: (
		<path d="M5.35 3.85C7.398 3.85 8.8 5.784 8.8 8c0 2.219-1.403 4.148-3.45 4.148-2.046 0-3.45-1.93-3.45-4.148s1.403-4.15 3.45-4.15m0 1.5c-.933 0-1.95.946-1.95 2.65s1.015 2.648 1.95 2.648c.936 0 1.95-.944 1.95-2.648S6.286 5.351 5.35 5.35m7.2-1.5C14.597 3.85 16 5.783 16 8s-1.404 4.148-3.45 4.148S9.1 10.22 9.1 8.001s1.403-4.151 3.45-4.151m0 1.5c-.935 0-1.95.946-1.95 2.651s1.014 2.648 1.95 2.648 1.95-.944 1.95-2.648-1.015-2.651-1.95-2.651M1.05 9.982a1.05 1.05 0 1 1 0 2.1 1.05 1.05 0 0 1 0-2.1" />
	),
}

export const decimalFillSmallIcon: LoadedIconFunction<"fillSmall"> = createIcon(
	"decimalFillSmall",
	iconDefinition,
	"fillSmall",
)
