/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "2.27 1.37 11.46 13.26",
	svg: (
		<>
			<path d="M11.9 6.976c1.008 0 1.826.817 1.826 1.825v4a1.826 1.826 0 0 1-1.826 1.825H9.1a1.826 1.826 0 0 1-1.825-1.825v-4c0-1.008.818-1.825 1.826-1.825zm-2.8 1.25a.575.575 0 0 0-.575.575v4c0 .317.258.575.576.575h2.8a.576.576 0 0 0 .575-.575v-4a.576.576 0 0 0-.576-.575z" />
			<path d="M10.1 1.375c1.008 0 1.826.817 1.826 1.825v2.525h-1.25V3.2a.576.576 0 0 0-.575-.575h-6a.575.575 0 0 0-.576.575V12c0 .318.258.575.576.575h1.924v.226c0 .36.066.703.18 1.024H4.1A1.825 1.825 0 0 1 2.275 12V3.2c0-1.008.818-1.825 1.826-1.825z" />
			<path d="M6.01 7.661a.55.55 0 0 1 0 1.078l-.11.011H5a.55.55 0 0 1 0-1.1h.9zm1.3-2a.55.55 0 0 1 0 1.078l-.11.011H5a.55.55 0 0 1 0-1.1h2.2zm2.2-2a.55.55 0 0 1 0 1.078l-.11.011H5a.55.55 0 0 1 0-1.1h4.4z" />
		</>
	),
}

export const rectangleOnRectangleTallLinesSmallIcon: LoadedIconFunction<"small"> =
	createIcon("rectangleOnRectangleTallLinesSmall", iconDefinition, "small")
