/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import type { IconGroup } from "../../iconUtils"
import { createIconGroup } from "../../iconUtils"

export const bubbleEllipsesIconGroup: IconGroup<
	"default" | "small" | "fill" | "fillSmall"
> = createIconGroup(
	"bubbleEllipses",
	{
		default: {
			loader: () =>
				import(
					/* webpackChunkName: "icon-bubbleEllipses" */
					"./default.icon"
				),
		},
		small: {
			loader: () =>
				import(
					/* webpackChunkName: "icon-bubbleEllipses" */
					"./small.icon"
				),
		},
		fill: {
			loader: () =>
				import(
					/* webpackChunkName: "icon-bubbleEllipses" */
					"./fill.icon"
				),
		},
		fillSmall: {
			loader: () =>
				import(
					/* webpackChunkName: "icon-bubbleEllipses" */
					"./fillSmall.icon"
				),
		},
	},
	[
		"speech",
		"bubble",
		"typing",
		"type",
		"reply",
		"replying",
		"waiting",
		"message",
		"comment",
	],
)
