/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import type { IconGroup } from "../../iconUtils"
import { createIconGroup } from "../../iconUtils"

export const textH2ToggleIconGroup: IconGroup<
	"default" | "small" | "fill" | "fillSmall"
> = createIconGroup(
	"textH2Toggle",
	{
		default: {
			loader: () =>
				import(
					/* webpackChunkName: "icon-textH2Toggle" */
					"./default.icon"
				),
		},
		small: {
			loader: () =>
				import(
					/* webpackChunkName: "icon-textH2Toggle" */
					"./small.icon"
				),
		},
		fill: {
			loader: () =>
				import(
					/* webpackChunkName: "icon-textH2Toggle" */
					"./fill.icon"
				),
		},
		fillSmall: {
			loader: () =>
				import(
					/* webpackChunkName: "icon-textH2Toggle" */
					"./fillSmall.icon"
				),
		},
	},
	[
		"format",
		"text",
		"heading",
		"subhead",
		"title",
		"headline",
		"large",
		"medium",
	],
)
