/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "1.32 1.7 13.36 12.32",
	svg: (
		<>
			<path d="M8 4.505c.345 0 .625.28.625.625v1.625h1.625a.625.625 0 1 1 0 1.25H8.625V9.63a.625.625 0 1 1-1.25 0V8.005H5.75a.625.625 0 1 1 0-1.25h1.625V5.13c0-.345.28-.625.625-.625" />
			<path d="M8.357 1.707c3.661.147 6.318 2.557 6.318 5.682l-.008.3c-.164 2.979-2.767 5.24-6.31 5.383L8 13.08a8.3 8.3 0 0 1-1.962-.23c-1.09.811-2.412 1.287-3.9 1.132a.625.625 0 0 1-.406-1.032c.538-.617.835-1.31.987-1.996a5.26 5.26 0 0 1-1.388-3.29l-.007-.274C1.324 4.163 4.156 1.7 8 1.7zM8 2.95c-3.335 0-5.426 2.072-5.426 4.44l.005.207c.053 1.033.497 1.975 1.251 2.71a.63.63 0 0 1 .18.546 6 6 0 0 1-.602 1.841c.763-.138 1.466-.494 2.095-1.01l.062-.044a.63.63 0 0 1 .506-.073A7 7 0 0 0 8 11.83l.309-.006c3.154-.124 5.116-2.14 5.116-4.434s-1.962-4.31-5.116-4.433z" />
		</>
	),
}

export const chatBubblePlusSmallIcon: LoadedIconFunction<"small"> = createIcon(
	"chatBubblePlusSmall",
	iconDefinition,
	"small",
)
