/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "1.6 2.28 12.15 12.15",
	svg: (
		<path d="m13.049 2.284-.008.003-11.08 4.288a.55.55 0 0 0-.065.996L5.69 9.643zM6.397 10.35l2.072 3.794a.55.55 0 0 0 .996-.066l4.288-11.08.002-.006z" />
	),
}

export const paperPlaneFillSmallIcon: LoadedIconFunction<"fillSmall"> =
	createIcon("paperPlaneFillSmall", iconDefinition, "fillSmall")
