/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "5.87 2.37 8.25 15.26",
	svg: (
		<path d="M5.875 4a1.625 1.625 0 1 0 3.25 0 1.625 1.625 0 0 0-3.25 0m5 0a1.625 1.625 0 1 0 3.25 0 1.625 1.625 0 0 0-3.25 0m1.625 7.625a1.625 1.625 0 1 1 0-3.25 1.625 1.625 0 0 1 0 3.25M5.875 10a1.625 1.625 0 1 0 3.25 0 1.625 1.625 0 0 0-3.25 0m6.625 7.625a1.625 1.625 0 1 1 0-3.25 1.625 1.625 0 0 1 0 3.25M5.875 16a1.625 1.625 0 1 0 3.25 0 1.625 1.625 0 0 0-3.25 0" />
	),
}

export const dragHandleFillIcon: LoadedIconFunction<"fill"> = createIcon(
	"dragHandleFill",
	iconDefinition,
	"fill",
)
