/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "1.67 3.6 12.65 8.8",
	svg: (
		<>
			<path d="M8.608 11.555c-.536.536-.803.803-1.03.837a.7.7 0 0 1-.663-.274c-.136-.184-.136-.563-.136-1.32V5.202c0-.757 0-1.136.136-1.32a.7.7 0 0 1 .663-.274c.227.034.494.301 1.03.837l2.797 2.798c.248.247.372.371.425.511.06.159.06.333 0 .492-.053.14-.177.264-.425.511z" />
			<path d="M11.888 4.424c0-.252 0-.378.045-.476a.5.5 0 0 1 .25-.25c.098-.044.223-.044.475-.044h.894c.252 0 .378 0 .476.044a.5.5 0 0 1 .25.25c.044.098.044.224.044.476v7.152c0 .252 0 .378-.044.476a.5.5 0 0 1-.25.25c-.098.044-.224.044-.476.044h-.894c-.252 0-.377 0-.476-.044a.5.5 0 0 1-.25-.25c-.044-.098-.044-.224-.044-.476zm-9.411 7.968c.226-.034.494-.301 1.029-.837l2.798-2.798c.248-.247.371-.371.424-.511a.7.7 0 0 0 0-.492c-.053-.14-.176-.264-.424-.511L3.506 4.445c-.535-.536-.803-.803-1.03-.837a.7.7 0 0 0-.662.274c-.136.184-.136.563-.136 1.32v5.596c0 .757 0 1.136.136 1.32a.7.7 0 0 0 .663.274" />
		</>
	),
}

export const mediaFastForwardFillSmallIcon: LoadedIconFunction<"fillSmall"> =
	createIcon("mediaFastForwardFillSmall", iconDefinition, "fillSmall")
