/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "3.27 2.15 13.45 15.7",
	svg: (
		<path d="M10 2.15c.483 0 .875.392.875.875v9.362l2.906-2.906a.875.875 0 1 1 1.238 1.238l-4.4 4.4a.875.875 0 0 1-1.238 0l-4.4-4.4A.875.875 0 0 1 6.22 9.48l2.906 2.906V3.025c0-.483.392-.875.875-.875M4.15 16.1a.875.875 0 1 0 0 1.75h11.7a.875.875 0 1 0 0-1.75z" />
	),
}

export const arrowLineDownFillIcon: LoadedIconFunction<"fill"> = createIcon(
	"arrowLineDownFill",
	iconDefinition,
	"fill",
)
