/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "1.27 3.52 17.42 12.96",
	svg: (
		<>
			<path d="M10.225 6.813c.345 0 .625.28.625.625v4.528l1.408-1.408a.626.626 0 0 1 .885.884l-2.5 2.5a.626.626 0 0 1-.787.08l-.098-.08-2.5-2.5a.626.626 0 0 1 .885-.884L9.6 12.015V7.437c0-.345.28-.624.625-.625" />
			<path d="M10.45 3.525a6.474 6.474 0 0 1 6.474 6.42 3.495 3.495 0 0 1-1.763 6.53H4.928a1 1 0 0 1-.174-.02 3.854 3.854 0 0 1-.687-7.54 6.476 6.476 0 0 1 6.383-5.39m4.799 12.942h.006l.008-.001zM10.45 4.775a5.226 5.226 0 0 0-5.2 4.715l-.047.483-.478.074a2.606 2.606 0 0 0-2.2 2.574l.012.253a2.605 2.605 0 0 0 2.372 2.34l.075.008.012.004H15.12l.026-.002h.059a2.244 2.244 0 0 0 .848-4.318l-.411-.169.024-.443q.01-.155.01-.294a5.226 5.226 0 0 0-5.226-5.225" />
		</>
	),
}

export const cloudArrowDownIcon: LoadedIconFunction<"default"> = createIcon(
	"cloudArrowDown",
	iconDefinition,
	"default",
)
