/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "1.15 2.9 13.68 10.2",
	svg: (
		<>
			<path d="M8.18 5.25a.5.5 0 0 1 .5.5v3.623l1.127-1.127a.5.5 0 0 1 .707.707l-2 2a.5.5 0 0 1-.63.065l-.077-.065-2-2a.5.5 0 0 1 .707-.707L7.68 9.412V5.75a.5.5 0 0 1 .5-.5" />
			<path d="M8.35 2.9c2.79 0 5.054 2.24 5.097 5.019a2.779 2.779 0 0 1-1.434 5.18H3.988l-.01-.01a3.06 3.06 0 0 1-2.824-2.894l-.004-.157a3.06 3.06 0 0 1 2.178-2.927 5.1 5.1 0 0 1 5.023-4.21m3.771 10.186h.002l.005-.002zm.085-.024-.008.003.015-.005.008-.004zM8.18 4.25a1.5 1.5 0 0 0-1.5 1.5v1.444A1.499 1.499 0 0 0 5.1 9.66l2 2 .114.104a1.5 1.5 0 0 0 2.007-.104l2-2A1.5 1.5 0 0 0 9.68 7.18V5.75a1.5 1.5 0 0 0-1.5-1.5" />
		</>
	),
}

export const cloudArrowDownFillSmallIcon: LoadedIconFunction<"fillSmall"> =
	createIcon("cloudArrowDownFillSmall", iconDefinition, "fillSmall")
