/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "2.46 2 11.08 11.89",
	svg: (
		<path d="M5.4 2.5a.5.5 0 0 1 .5-.5h4.2a.5.5 0 0 1 0 1H5.9a.5.5 0 0 1-.5-.5m-.9 1.25a.5.5 0 0 0 0 1h7a.5.5 0 0 0 0-1zm-.237 1.7a1.8 1.8 0 0 0-1.8 1.8v4.85c0 .927.7 1.69 1.6 1.79.061-.99.926-1.775 1.983-1.775.975 0 1.786.667 1.954 1.547.168-.88.979-1.547 1.954-1.547 1.057 0 1.922.785 1.982 1.774a1.8 1.8 0 0 0 1.602-1.789V7.25a1.8 1.8 0 0 0-1.8-1.8zm3.103 3.714c0 .85-.47 1.54-1.32 1.54s-1.319-.69-1.319-1.54.47-1.539 1.32-1.539 1.319.69 1.319 1.54m3.907 0c0 .85-.47 1.54-1.32 1.54s-1.318-.69-1.318-1.54.469-1.539 1.319-1.539 1.32.69 1.32 1.54" />
	),
}

export const peopleStackFillSmallIcon: LoadedIconFunction<"fillSmall"> =
	createIcon("peopleStackFillSmall", iconDefinition, "fillSmall")
