/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "2.37 2.37 11.25 11.25",
	svg: (
		<>
			<path
				fillRule="evenodd"
				d="M13.625 11.8a1.825 1.825 0 0 1-1.825 1.825H4.2A1.825 1.825 0 0 1 2.375 11.8V6.15h11.25z"
				clipRule="evenodd"
			/>
			<path d="M11.8 2.375c1.008 0 1.825.817 1.825 1.825v.85H2.375V4.2c0-1.008.817-1.825 1.825-1.825z" />
		</>
	),
}

export const calendarAltEmptyFillSmallIcon: LoadedIconFunction<"fillSmall"> =
	createIcon("calendarAltEmptyFillSmall", iconDefinition, "fillSmall")
