/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "1.15 2.87 13.68 11.76",
	svg: (
		<path d="m4.779 3.157-.054-.064a.625.625 0 1 0-.95.814l.683.797a5.1 5.1 0 0 0-1.13 2.402 3.063 3.063 0 0 0 .884 5.994h7.443l1.12 1.307a.625.625 0 0 0 1.086-.539L4.902 3.416a.55.55 0 0 1-.123-.26m9.201 9.16a2.78 2.78 0 0 0-.53-4.398 5.1 5.1 0 0 0-7.167-4.582z" />
	),
}

export const cloudSlashFillSmallIcon: LoadedIconFunction<"fillSmall"> =
	createIcon("cloudSlashFillSmall", iconDefinition, "fillSmall")
