/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "1.07 2.82 13.83 11.81",
	svg: (
		<path d="m4.779 3.157-.054-.064a.625.625 0 1 0-.95.814l.634.739a5.16 5.16 0 0 0-1.147 2.402 3.138 3.138 0 0 0 .95 6.127h7.508l1.055 1.232a.625.625 0 0 0 1.086-.539L4.902 3.416a.55.55 0 0 1-.123-.26m3.599 8.768H4.212a1.887 1.887 0 0 1-.294-3.75l.479-.076.046-.482c.073-.75.357-1.44.793-2.006l5.412 6.314zm5.651.449a2.854 2.854 0 0 0-.505-4.498 5.175 5.175 0 0 0-7.292-4.598l.86 1.004a3.925 3.925 0 0 1 5.177 3.94l-.025.443.411.169a1.607 1.607 0 0 1 .558 2.588z" />
	),
}

export const cloudSlashSmallIcon: LoadedIconFunction<"small"> = createIcon(
	"cloudSlashSmall",
	iconDefinition,
	"small",
)
