/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "0.25 2.25 15.5 11.51",
	svg: (
		<path d="M5.18 2.25a.75.75 0 0 0 0 1.5h6.38a.69.69 0 0 1 .69.69v4.242l-.7-.7a.75.75 0 0 0-1.06 1.06l1.98 1.98a.75.75 0 0 0 1.06 0l1.98-1.98a.75.75 0 1 0-1.06-1.06l-.7.7V4.44c0-1.21-.98-2.19-2.19-2.19zm5.64 11.5a.75.75 0 0 0 0-1.5H4.44a.69.69 0 0 1-.69-.69V7.318l.7.7a.75.75 0 0 0 1.06-1.06l-1.98-1.98a.75.75 0 0 0-1.06 0L.49 6.957a.75.75 0 1 0 1.06 1.06l.7-.7v4.242c0 1.21.98 2.19 2.19 2.19z" />
	),
}

export const arrowSquarePathUpDownFillSmallIcon: LoadedIconFunction<"fillSmall"> =
	createIcon("arrowSquarePathUpDownFillSmall", iconDefinition, "fillSmall")
