/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import type { IconGroup } from "../../iconUtils"
import { createIconGroup } from "../../iconUtils"

export const arrowSquarePathUpDownIconGroup: IconGroup<
	"default" | "small" | "fill" | "fillSmall"
> = createIconGroup(
	"arrowSquarePathUpDown",
	{
		default: {
			loader: () =>
				import(
					/* webpackChunkName: "icon-arrowSquarePathUpDown" */
					"./default.icon"
				),
		},
		small: {
			loader: () =>
				import(
					/* webpackChunkName: "icon-arrowSquarePathUpDown" */
					"./small.icon"
				),
		},
		fill: {
			loader: () =>
				import(
					/* webpackChunkName: "icon-arrowSquarePathUpDown" */
					"./fill.icon"
				),
		},
		fillSmall: {
			loader: () =>
				import(
					/* webpackChunkName: "icon-arrowSquarePathUpDown" */
					"./fillSmall.icon"
				),
		},
	},
	["turn into", "refresh", "reload", "update", "sync", "circular"],
)
