/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "1.52 1.9 12.77 12.77",
	svg: (
		<path d="M12.457 1.963c1.113-.335 2.162.763 1.733 1.88l-3.814 9.908c-.455 1.183-2.093 1.215-2.616.104l-.046-.111-1.293-3.409a.97.97 0 0 0-.565-.565L2.443 8.473C1.22 8.01 1.215 6.28 2.436 5.811l9.913-3.81z" />
	),
}

export const pointerFillSmallIcon: LoadedIconFunction<"fillSmall"> = createIcon(
	"pointerFillSmall",
	iconDefinition,
	"fillSmall",
)
