/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "1.15 1.15 13.69 13.69",
	svg: (
		<path d="M6.71 1.69a1.825 1.825 0 0 1 2.58 0l5.021 5.02a1.826 1.826 0 0 1 0 2.58l-5.02 5.021a1.826 1.826 0 0 1-2.581 0l-5.02-5.02a1.825 1.825 0 0 1 0-2.581zm1.157 8.665a.675.675 0 1 0 .001 1.351.675.675 0 0 0-.001-1.35m.114-5.489c-1.04 0-2.055.602-2.303 1.592a.626.626 0 0 0 1.213.303c.073-.287.459-.645 1.09-.645.75 0 1.108.463 1.109.764 0 .184-.113.41-.4.585l-.015.008-.013.01-.64.436-.003.002a1.84 1.84 0 0 0-.81 1.504.626.626 0 0 0 1.25 0 .59.59 0 0 1 .271-.476v-.001l.636-.434h-.001c.547-.344.975-.92.975-1.634 0-1.235-1.191-2.014-2.359-2.014" />
	),
}

export const questionDiamondFillSmallIcon: LoadedIconFunction<"fillSmall"> =
	createIcon("questionDiamondFillSmall", iconDefinition, "fillSmall")
