/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "1.15 1.15 13.69 13.69",
	svg: (
		<>
			<path d="M7.867 10.355a.676.676 0 1 1 0 1.352.676.676 0 0 1 0-1.352m.114-5.489c1.168 0 2.358.779 2.359 2.014 0 .713-.428 1.29-.975 1.633l.001.001-.637.434.001.001a.59.59 0 0 0-.271.476.625.625 0 0 1-1.25 0c0-.61.318-1.164.81-1.504l.003-.002.64-.437.013-.009.014-.008c.288-.175.4-.401.4-.585 0-.301-.359-.764-1.108-.764-.631 0-1.017.358-1.09.645a.625.625 0 0 1-1.213-.303c.248-.99 1.264-1.592 2.303-1.592" />
			<path d="M6.71 1.69a1.825 1.825 0 0 1 2.58 0l5.021 5.02a1.826 1.826 0 0 1 0 2.58l-5.02 5.021a1.826 1.826 0 0 1-2.581 0l-5.02-5.02a1.825 1.825 0 0 1 0-2.581zm1.697.883a.576.576 0 0 0-.813 0l-5.021 5.02a.576.576 0 0 0 0 .814l5.02 5.02c.225.225.59.225.814 0l5.02-5.02a.576.576 0 0 0 0-.813z" />
		</>
	),
}

export const questionDiamondSmallIcon: LoadedIconFunction<"small"> = createIcon(
	"questionDiamondSmall",
	iconDefinition,
	"small",
)
