/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "0.12 2.09 19.76 15.81",
	svg: (
		<path d="M12.841 3.24a.875.875 0 1 0-1.682-.48l-4 14a.875.875 0 1 0 1.682.48zM6.019 4.981a.875.875 0 0 1 0 1.238L2.237 10l3.782 3.781A.875.875 0 1 1 4.78 15.02l-4.4-4.4a.875.875 0 0 1 0-1.238l4.4-4.4a.875.875 0 0 1 1.238 0m7.963-.001a.875.875 0 0 1 1.238 0l4.4 4.4a.875.875 0 0 1 0 1.238l-4.4 4.4a.875.875 0 1 1-1.238-1.238L17.763 10 13.98 6.219a.875.875 0 0 1 0-1.238" />
	),
}

export const codeFillIcon: LoadedIconFunction<"fill"> = createIcon(
	"codeFill",
	iconDefinition,
	"fill",
)
