/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "1.59 1.59 16.81 16.81",
	svg: (
		<path d="M11.503 2.222a2.125 2.125 0 0 0-3.006 0L2.222 8.497c-.83.83-.83 2.176 0 3.005l6.275 6.276c.83.83 2.176.83 3.005 0l6.276-6.275c.83-.83.83-2.176 0-3.006zM10 5.875c.345 0 .625.28.625.625v2.875H13.5a.625.625 0 1 1 0 1.25h-2.875V13.5a.625.625 0 1 1-1.25 0v-2.875H6.5a.625.625 0 1 1 0-1.25h2.875V6.5c0-.345.28-.625.625-.625" />
	),
}

export const plusDiamondFillIcon: LoadedIconFunction<"fill"> = createIcon(
	"plusDiamondFill",
	iconDefinition,
	"fill",
)
