/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "1.57 2.85 12.86 9.98",
	directional: true,
	svg: (
		<path d="M6.162 3.038a.625.625 0 0 0-.884 0l-3.52 3.52a.625.625 0 0 0 0 .884l3.52 3.52a.625.625 0 1 0 .884-.884L3.71 7.625h7.49a1.975 1.975 0 0 1 0 3.95h-1.136a.625.625 0 0 0 0 1.25H11.2a3.225 3.225 0 1 0 0-6.45H3.71l2.453-2.453a.625.625 0 0 0 0-.884" />
	),
}

export const arrowUTurnUpLeftSmallIcon: LoadedIconFunction<"small"> =
	createIcon("arrowUTurnUpLeftSmall", iconDefinition, "small")
