/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "2.46 3.3 11.08 10.16",
	svg: (
		<path d="M11.737 11.75a1.8 1.8 0 0 0 1.8-1.8V5.1a1.8 1.8 0 0 0-1.8-1.8H4.262a1.8 1.8 0 0 0-1.8 1.8v4.85a1.8 1.8 0 0 0 1.8 1.8zM6.47 8.288c.234-.175.515-.258.773-.285q.106-.012.217-.01V5.684c0-.275.222-.522.496-.552l1.442-.155a.45.45 0 0 1 .353.11.45.45 0 0 1 .146.338v.706c0 .275-.22.521-.494.552l-.949.107v1.966l-.002.049.002.068c0 .356-.185.65-.438.84a1.57 1.57 0 0 1-.773.284c-.258.028-.54.004-.773-.122a.82.82 0 0 1-.439-.748c0-.356.185-.65.439-.84M12 12.95a.5.5 0 0 1-.5.5h-7a.5.5 0 0 1 0-1h7a.5.5 0 0 1 .5.5" />
	),
}

export const musicNoteTvFillSmallIcon: LoadedIconFunction<"fillSmall"> =
	createIcon("musicNoteTvFillSmall", iconDefinition, "fillSmall")
