/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "2.96 1.99 14.08 15.13",
	svg: (
		<>
			<path d="M10 9.146c.345 0 .625.28.625.625v1.374H12a.625.625 0 1 1 0 1.25h-1.375v1.376a.625.625 0 0 1-1.25 0v-1.376H8a.626.626 0 0 1 0-1.25h1.375V9.772c0-.346.28-.625.625-.625" />
			<path d="M14.913 6.42c1.174 0 2.125.951 2.125 2.125v6.45a2.125 2.125 0 0 1-2.125 2.125H5.088a2.125 2.125 0 0 1-2.125-2.125v-6.45c0-1.174.951-2.125 2.125-2.125zM5.088 7.67a.875.875 0 0 0-.875.875v6.45c0 .483.392.875.875.875h9.825a.875.875 0 0 0 .875-.875v-6.45a.875.875 0 0 0-.875-.875zm9.523-3.414a.55.55 0 0 1 0 1.078l-.111.01h-9a.55.55 0 1 1 0-1.099h9zm-1.801-2.25a.55.55 0 0 1 0 1.078l-.11.01H7.3a.55.55 0 1 1 0-1.099h5.4z" />
		</>
	),
}

export const plusStackIcon: LoadedIconFunction<"default"> = createIcon(
	"plusStack",
	iconDefinition,
	"default",
)
