/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "2.57 1.62 10.86 12",
	svg: (
		<>
			<path d="M12.8 9.575c.345 0 .625.28.625.625v1.6a1.825 1.825 0 0 1-1.824 1.825H4.4A1.825 1.825 0 0 1 2.574 11.8v-1.6a.625.625 0 0 1 1.25 0v1.6c0 .317.258.575.575.575h7.2a.575.575 0 0 0 .575-.575v-1.6c0-.345.28-.625.625-.625" />
			<path d="M7.636 1.727a.63.63 0 0 1 .786.08l2.8 2.801a.625.625 0 0 1-.884.884L8.625 3.779v6.42a.625.625 0 0 1-1.25 0v-6.46L5.622 5.492a.626.626 0 0 1-.885-.884l2.801-2.8z" />
		</>
	),
}

export const arrowTrayUpSmallIcon: LoadedIconFunction<"small"> = createIcon(
	"arrowTrayUpSmall",
	iconDefinition,
	"small",
)
