/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "1.52 1.99 12.96 12.01",
	svg: (
		<>
			<path d="m12.121 6.903.891 1.543a.83.83 0 0 0 .316-.649V2.828A.83.83 0 0 0 12.5 2H7.324a.83.83 0 0 0-.828.828v4.977c0 .448.364.82.82.82h.668l.994-1.722a1 1 0 0 1 .096-.138 1.81 1.81 0 0 1 3.045.134z" />
			<path d="M7.42 9.603h-.104a1.8 1.8 0 0 1-1.798-1.798V4.697q-.135-.01-.27-.01a3.729 3.729 0 1 0 .748 7.383zm2.405-2.212-3.097 5.367A.828.828 0 0 0 7.448 14h6.203a.83.83 0 0 0 .72-1.242L11.275 7.39a.832.832 0 0 0-1.44 0z" />
		</>
	),
}

export const templatesFillSmallIcon: LoadedIconFunction<"fillSmall"> =
	createIcon("templatesFillSmall", iconDefinition, "fillSmall")
