/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "2.37 1.59 12.03 12.03",
	svg: (
		<>
			<path d="m14.2 2.781-.517.518-.977-.976.525-.524a.69.69 0 0 1 .97 0 .69.69 0 0 1 0 .97zM7.052 9.93l5.998-5.998-.977-.977L6.07 8.948a1 1 0 0 0-.208.347l-.254.82c-.046.173.116.335.277.277l.82-.254a.8.8 0 0 0 .347-.208" />
			<path d="M5 2.375h5.885l-5.699 5.69a2.2 2.2 0 0 0-.499.803l-.01.028-.27.873-.007.024c-.265.993.642 2.2 1.873 1.787l.787-.243c.349-.1.642-.29.876-.523l5.689-5.69V11A2.625 2.625 0 0 1 11 13.625H5A2.625 2.625 0 0 1 2.375 11V5A2.625 2.625 0 0 1 5 2.375" />
		</>
	),
}

export const composeFillSmallIcon: LoadedIconFunction<"fillSmall"> = createIcon(
	"composeFillSmall",
	iconDefinition,
	"fillSmall",
)
