/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "2.46 2 11.08 11.91",
	svg: (
		<path d="M5.4 2.5a.5.5 0 0 1 .5-.5h4.2a.5.5 0 0 1 0 1H5.9a.5.5 0 0 1-.5-.5m-.9 1.25a.5.5 0 0 0 0 1h7a.5.5 0 0 0 0-1zm-.237 1.7a1.8 1.8 0 0 0-1.8 1.8v4.85a1.8 1.8 0 0 0 1.8 1.8h1.64c.058-.994.974-1.785 2.097-1.785s2.04.79 2.098 1.785h1.64a1.8 1.8 0 0 0 1.8-1.8V7.25a1.8 1.8 0 0 0-1.8-1.8zm5.056 3.714c0 .85-.469 1.54-1.319 1.54s-1.32-.69-1.32-1.54S7.15 7.625 8 7.625s1.32.69 1.32 1.54" />
	),
}

export const personCropRectangleStackFillSmallIcon: LoadedIconFunction<"fillSmall"> =
	createIcon("personCropRectangleStackFillSmall", iconDefinition, "fillSmall")
