/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "2.12 2.97 11.75 11.7",
	svg: (
		<path d="M13.875 4.85c0-1.035-.84-1.875-1.875-1.875H4c-1.036 0-1.875.84-1.875 1.875v5.5c0 1.036.84 1.875 1.875 1.875h.466v1.822a.625.625 0 0 0 1.019.485l2.84-2.307H12c1.036 0 1.875-.84 1.875-1.875zM7.269 6.788h.73a.5.5 0 0 1 .5.5v1.937h.232a.5.5 0 0 1 0 1H7.27a.5.5 0 0 1 0-1h.23V7.788h-.23a.5.5 0 0 1 0-1M8.7 5.55a.7.7 0 1 1-1.4 0 .7.7 0 0 1 1.4 0" />
	),
}

export const commentInfoFillSmallIcon: LoadedIconFunction<"fillSmall"> =
	createIcon("commentInfoFillSmall", iconDefinition, "fillSmall")
