/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "0.39 3.55 13.45 12.05",
	svg: (
		<path d="M6.407 10.05c-.483-.57-1.125-1-1.857-1.223V4.5a.95.95 0 0 1 .95-.95h7.4a.95.95 0 0 1 .95.95v4.6a.95.95 0 0 1-.95.95zM3.45 8.657V5.95H3.1a.95.95 0 0 0-.95.95v1.96a4 4 0 0 1 1.3-.203m7.05 3.793H7.34a3.9 3.9 0 0 0-.272-1.3h4.382v.35a.95.95 0 0 1-.95.95M3.4 15.6a3 3 0 1 1 0-6 3 3 0 0 1 0 6m-1.667-3.5a.5.5 0 1 0 0 1H2.9v1.167a.5.5 0 0 0 1 0V13.1h1.166a.5.5 0 0 0 0-1H3.9v-1.166a.5.5 0 1 0-1 0V12.1z" />
	),
}

export const rectangleOnRectanglePlusFillSmallIcon: LoadedIconFunction<"fillSmall"> =
	createIcon("rectangleOnRectanglePlusFillSmall", iconDefinition, "fillSmall")
