/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "2.12 3.37 11.75 9.25",
	svg: (
		<path d="M4 3.375c-1.036 0-1.875.84-1.875 1.875v5.5c0 1.036.84 1.875 1.875 1.875h8c1.036 0 1.875-.84 1.875-1.875v-5.5c0-1.036-.84-1.875-1.875-1.875zM3.375 5.25c0-.345.28-.625.625-.625h3.375v1.417h-4zm5.25.792V4.625H12c.345 0 .625.28.625.625v.792zm0 2.666V7.292h4v1.416zm-5.25 0V7.292h4v1.416zm0 2.042v-.792h4v1.417H4a.625.625 0 0 1-.625-.625m5.25.625V9.958h4v.792c0 .345-.28.625-.625.625z" />
	),
}

export const viewTableSmallIcon: LoadedIconFunction<"small"> = createIcon(
	"viewTableSmall",
	iconDefinition,
	"small",
)
