/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "1.08 3.72 13.82 8.61",
	svg: (
		<path d="M8.333 8.03a4.304 4.304 0 0 1 4.304-4.303h.508a.75.75 0 0 1 0 1.5h-.508a2.804 2.804 0 0 0-2.803 2.757 2.78 2.78 0 1 1 2.296 4.35 3.796 3.796 0 0 1-3.797-3.796zM5.394 3.727A4.304 4.304 0 0 0 1.09 8.03v.507c0 2.097 1.7 3.797 3.796 3.797a2.78 2.78 0 0 0 2.781-2.781V9.55q0-.07-.004-.14A2.78 2.78 0 0 0 2.59 7.985a2.804 2.804 0 0 1 2.804-2.757h.508a.75.75 0 0 0 0-1.5z" />
	),
}

export const quoteFillSmallIcon: LoadedIconFunction<"fillSmall"> = createIcon(
	"quoteFillSmall",
	iconDefinition,
	"fillSmall",
)
