/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "2.82 1.77 12.31 13.96",
	svg: (
		<path d="M8 1.775c-.947 0-1.717.392-2.237 1.04-.508.633-.747 1.47-.747 2.338s.239 1.704.747 2.337c.52.648 1.29 1.04 2.237 1.04s1.717-.392 2.237-1.04c.508-.633.748-1.47.748-2.337 0-.869-.24-1.705-.748-2.338-.52-.648-1.29-1.04-2.237-1.04m0 7.403c-2.197 0-4.166 1.07-5.007 2.713a1.48 1.48 0 0 0 .2 1.676c.356.414.91.658 1.487.658h6.053v-1.44a3.42 3.42 0 0 1-1.115-3.407A6.6 6.6 0 0 0 8 9.178m7.125.997c0 .854-.492 1.593-1.208 1.949v1.072l-.725.846.725.845-.967.846-.967-.846v-2.763a2.175 2.175 0 1 1 3.142-1.949m-1.617-.483a.558.558 0 1 0-1.116 0 .558.558 0 0 0 1.116 0" />
	),
}

export const personKeyFillSmallIcon: LoadedIconFunction<"fillSmall"> =
	createIcon("personKeyFillSmall", iconDefinition, "fillSmall")
