/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "2.06 2.53 15.65 15.64",
	svg: (
		<path d="M6.421 3.657a.55.55 0 0 1 .776.06l.222.258.012.017 8.777 10.241a.55.55 0 0 1-.846.7l-1.167-1.361-1.37 3.56c-.537 1.392-2.507 1.387-3.036-.007l-1.616-4.261c-.14-.368-.43-.66-.797-.799l-4.268-1.62c-1.394-.529-1.398-2.5-.006-3.035l4.37-1.68-1.11-1.297a.55.55 0 0 1 .06-.776m9.07-1.011c1.314-.504 2.605.787 2.1 2.1l-2.5 6.492-5.44-6.348z" />
	),
}

export const pointerSlashFillIcon: LoadedIconFunction<"fill"> = createIcon(
	"pointerSlashFill",
	iconDefinition,
	"fill",
)
