/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "1.52 1.9 12.77 12.77",
	svg: (
		<path d="M5.126 2.786a.626.626 0 0 1 .882.067l.116.136q.032.091.098.169l7.089 8.27a.624.624 0 0 1-1.052.639l-.852-.994-1.03 2.678c-.47 1.22-2.199 1.216-2.663-.007l-1.293-3.408a.98.98 0 0 0-.565-.567L2.443 8.473C1.22 8.01 1.215 6.281 2.436 5.811l3.354-1.29-.731-.853a.626.626 0 0 1 .067-.882M2.884 6.978a.175.175 0 0 0 .001.326L6.3 8.6a2.23 2.23 0 0 1 1.29 1.292L8.882 13.3c.057.15.27.151.327.001l1.273-3.307-3.828-4.466zM12.35 2c1.151-.442 2.283.69 1.84 1.842l-1.84 4.775-.924-1.078 1.597-4.146a.176.176 0 0 0-.227-.226l-3.85 1.478-.863-1.007z" />
	),
}

export const pointerSlashSmallIcon: LoadedIconFunction<"small"> = createIcon(
	"pointerSlashSmall",
	iconDefinition,
	"small",
)
