/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "4.12 2.37 11.76 15.26",
	svg: (
		<path d="M6.25 2.375h.816v10.13H6.48a3.53 3.53 0 0 0-2.356.897V4.5c0-1.174.951-2.125 2.125-2.125M4.188 16.016a2.126 2.126 0 0 0 2.062 1.609h9a.625.625 0 0 0 .4-1.106l-.161-.133a1.706 1.706 0 0 1 .009-2.631H6.48a2.294 2.294 0 0 0-2.293 2.26m11.688-3.51V4.5a2.125 2.125 0 0 0-2.125-2.125H8.19v10.13z" />
	),
}

export const bookClosedFillIcon: LoadedIconFunction<"fill"> = createIcon(
	"bookClosedFill",
	iconDefinition,
	"fill",
)
