/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "3.37 2.12 9.12 11.75",
	svg: (
		<path d="M5.25 2.125c-1.036 0-1.875.84-1.875 1.875v7.87c0 1.107.898 2.005 2.005 2.005h6.484a.625.625 0 0 0 .414-1.093c-.361-.32-.502-.636-.502-.912 0-.277.14-.592.502-.912a.63.63 0 0 0 .21-.468V3.5c0-.76-.615-1.375-1.374-1.375zM4.625 4c0-.345.28-.625.625-.625h.324v6.49H5.38a2 2 0 0 0-.755.147zm2.099 5.865v-6.49h4.39c.069 0 .125.056.125.125v6.365zM4.625 11.87c0-.417.338-.755.755-.755h5.285a2.13 2.13 0 0 0 0 1.51H5.38a.755.755 0 0 1-.755-.755" />
	),
}

export const bookClosedSmallIcon: LoadedIconFunction<"small"> = createIcon(
	"bookClosedSmall",
	iconDefinition,
	"small",
)
