/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import type { IconGroup } from "../../iconUtils"
import { createIconGroup } from "../../iconUtils"

export const calendarBadgeXIconGroup: IconGroup<
	"default" | "small" | "fill" | "fillSmall"
> = createIconGroup(
	"calendarBadgeX",
	{
		default: {
			loader: () =>
				import(
					/* webpackChunkName: "icon-calendarBadgeX" */
					"./default.icon"
				),
		},
		small: {
			loader: () =>
				import(
					/* webpackChunkName: "icon-calendarBadgeX" */
					"./small.icon"
				),
		},
		fill: {
			loader: () =>
				import(
					/* webpackChunkName: "icon-calendarBadgeX" */
					"./fill.icon"
				),
		},
		fillSmall: {
			loader: () =>
				import(
					/* webpackChunkName: "icon-calendarBadgeX" */
					"./fillSmall.icon"
				),
		},
	},
	[
		"annually",
		"badge",
		"calendar",
		"clock",
		"date",
		"daily",
		"monthly",
		"recurring",
		"schedule",
		"time",
		"clear",
	],
)
