/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "2.2 2.19 11.6 12.39",
	svg: (
		<path d="m4.145 2.657-.227-.265a.55.55 0 1 0-.836.716L5.794 6.27H2.75a.55.55 0 0 0-.323.995L5.348 9.39l-1.116 3.434a.55.55 0 0 0 .847.615L8 11.315l2.921 2.123a.55.55 0 0 0 .826-.221l.992 1.156a.55.55 0 1 0 .835-.715l-.414-.483-.008-.009-9-10.5zM11.09 9.07l2.483-1.804a.55.55 0 0 0-.323-.995H9.639L8.523 2.837a.55.55 0 0 0-1.046 0L7.002 4.3z" />
	),
}

export const starSlashFillSmallIcon: LoadedIconFunction<"fillSmall"> =
	createIcon("starSlashFillSmall", iconDefinition, "fillSmall")
