/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "3.97 6.37 12.06 6.66",
	svg: (
		<path d="M10.442 6.558a.625.625 0 0 0-.884 0l-5.4 5.4a.625.625 0 1 0 .884.884L10 7.884l4.958 4.958a.625.625 0 1 0 .884-.884z" />
	),
}

export const arrowChevronSingleUpIcon: LoadedIconFunction<"default"> =
	createIcon("arrowChevronSingleUp", iconDefinition, "default")
