/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "0.12 2.12 19.76 15.75",
	svg: (
		<>
			<path d="M17.002 6.465c.232 0 .454.093.618.258l2.02 2.03a.875.875 0 0 1-1.24 1.234l-.525-.527V10a7.875 7.875 0 0 1-13.234 5.77.875.875 0 0 1 1.191-1.281A6.125 6.125 0 0 0 16.125 10v-.556l-.538.535a.875.875 0 0 1-1.234-1.24l2.03-2.02a.88.88 0 0 1 .62-.255" />
			<path d="M10 4.55a.875.875 0 0 0-.875.875V9.7c0 .483.392.875.875.875h2.6a.875.875 0 1 0 0-1.75h-1.725v-3.4A.875.875 0 0 0 10 4.55" />
			<path d="m2.125 10.54-.525-.527a.875.875 0 0 0-1.24 1.234l2.02 2.03a.875.875 0 0 0 1.237.003l2.03-2.02a.875.875 0 1 0-1.234-1.24l-.538.535V10a6.125 6.125 0 0 1 10.293-4.489.875.875 0 1 0 1.19-1.282A7.875 7.875 0 0 0 2.125 10z" />
		</>
	),
}

export const clockArrow2CirclePathFillIcon: LoadedIconFunction<"fill"> =
	createIcon("clockArrow2CirclePathFill", iconDefinition, "fill")
