/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "2.37 0.12 15.26 17.51",
	svg: (
		<>
			<path d="M6.898 2.558a.625.625 0 0 0 0 .884l2.254 2.254a.625.625 0 0 0 .884-.884L8.849 3.625H10A6.375 6.375 0 1 1 5.435 5.55a.625.625 0 0 0-.895-.872A7.625 7.625 0 1 0 10 2.375H8.849l1.187-1.187a.625.625 0 1 0-.884-.884z" />
			<path d="M12.662 7.12a.625.625 0 0 1 .214.858l-3 5a.625.625 0 0 1-1.01.085l-2-2.334a.625.625 0 1 1 .949-.813l1.435 1.675 2.554-4.256a.625.625 0 0 1 .857-.215" />
		</>
	),
}

export const arrowCircleCheckIcon: LoadedIconFunction<"default"> = createIcon(
	"arrowCircleCheck",
	iconDefinition,
	"default",
)
