/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "1.73 2.19 12.54 11.57",
	directional: true,
	svg: (
		<path d="M14.05 4.418a.75.75 0 0 1 0 1.06l-1.98 1.98a.75.75 0 0 1-1.06-1.06l.697-.698h-.778a2.45 2.45 0 0 0-2.093 1.177L8.153 8l.683 1.123a2.45 2.45 0 0 0 2.093 1.177h.778l-.697-.698a.75.75 0 1 1 1.06-1.06l1.98 1.98a.75.75 0 0 1 0 1.06l-1.98 1.98a.75.75 0 0 1-1.06-1.06l.702-.703h-.783a3.95 3.95 0 0 1-3.375-1.897l-.28-.46-.28.463a3.95 3.95 0 0 1-3.375 1.897H2.48a.75.75 0 0 1 0-1.5h1.14a2.45 2.45 0 0 0 2.093-1.177L6.397 8l-.685-1.125A2.45 2.45 0 0 0 3.62 5.698H2.48a.75.75 0 1 1 0-1.5h1.14a3.95 3.95 0 0 1 3.375 1.897l.28.462.28-.46A3.95 3.95 0 0 1 10.93 4.2h.783l-.702-.702a.75.75 0 1 1 1.06-1.06z" />
	),
}

export const arrowIntersectRightFillSmallIcon: LoadedIconFunction<"fillSmall"> =
	createIcon("arrowIntersectRightFillSmall", iconDefinition, "fillSmall")
