/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "1.67 2.33 16.65 14.32",
	svg: (
		<path d="M5.775 5.375v-.913c0-1.173.951-2.125 2.125-2.125h4.2c1.174 0 2.125.952 2.125 2.125v.913H15.9A2.425 2.425 0 0 1 18.325 7.8v6.43a2.425 2.425 0 0 1-2.425 2.424H4.1a2.425 2.425 0 0 1-2.425-2.425V7.8A2.425 2.425 0 0 1 4.1 5.376zm1.25-.913v.913h5.95v-.913a.875.875 0 0 0-.875-.875H7.9a.875.875 0 0 0-.875.875M4.1 6.625c-.649 0-1.175.526-1.175 1.175v1.337h14.15V7.8c0-.65-.526-1.175-1.175-1.175zm12.975 3.612H11.5v.688a.45.45 0 0 1-.45.45h-2.1a.45.45 0 0 1-.45-.45v-.688H2.925v3.992c0 .65.526 1.175 1.175 1.175h11.8c.649 0 1.175-.526 1.175-1.175z" />
	),
}

export const briefcaseIcon: LoadedIconFunction<"default"> = createIcon(
	"briefcase",
	iconDefinition,
	"default",
)
