/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "1.21 1.74 13.57 11.71",
	svg: (
		<path d="M4.495 4.175V3.57c0-1.008.817-1.825 1.825-1.825h3.36c1.008 0 1.825.817 1.825 1.825v.605h1.215c1.14 0 2.065.925 2.065 2.065v.96H1.215v-.96c0-1.14.924-2.065 2.065-2.065zm1.25-.605v.605h4.51V3.57a.575.575 0 0 0-.575-.575H6.32a.575.575 0 0 0-.575.575M1.215 8.3v3.084c0 1.14.924 2.065 2.065 2.065h9.44c1.14 0 2.065-.925 2.065-2.065V8.3H9.2v.44a.36.36 0 0 1-.36.36H7.16a.36.36 0 0 1-.36-.36V8.3z" />
	),
}

export const briefcaseFillSmallIcon: LoadedIconFunction<"fillSmall"> =
	createIcon("briefcaseFillSmall", iconDefinition, "fillSmall")
