/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "2.92 1.57 10.16 13.1",
	svg: (
		<>
			<path d="M8 4.436a2.345 2.345 0 1 0 0 4.69 2.345 2.345 0 0 0 0-4.69M6.905 6.781a1.095 1.095 0 1 1 2.19 0 1.095 1.095 0 0 1-2.19 0" />
			<path d="M8 1.575a5.077 5.077 0 0 0-5.078 5.077v.103a5.18 5.18 0 0 0 1.09 3.177l3.494 4.501a.625.625 0 0 0 .987 0l3.496-4.5a5.18 5.18 0 0 0 1.088-3.178v-.103A5.077 5.077 0 0 0 8 1.575M4.172 6.652a3.827 3.827 0 0 1 7.655 0v.103a3.93 3.93 0 0 1-.826 2.41L8 13.032 4.998 9.166a3.93 3.93 0 0 1-.826-2.41z" />
		</>
	),
}

export const mapPinSmallIcon: LoadedIconFunction<"small"> = createIcon(
	"mapPinSmall",
	iconDefinition,
	"small",
)
