/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "1.66 2.72 16.75 14.18",
	svg: (
		<path d="M10.875 3.597a.875.875 0 0 0-1.75 0v8a.875.875 0 0 0 1.75 0zM1.92 7.345A11.45 11.45 0 0 1 8 4.128v1.784a9.7 9.7 0 0 0-4.835 2.664.875.875 0 1 1-1.244-1.231M4.13 9.467A8.4 8.4 0 0 1 8 7.262v1.82a6.66 6.66 0 0 0-2.633 1.622.875.875 0 0 1-1.238-1.238M12 7.231v1.812c1.053.322 1.997.9 2.758 1.66a.875.875 0 0 0 1.238-1.237A8.4 8.4 0 0 0 12 7.231m-5.705 4.401A5.4 5.4 0 0 1 8 10.484v1.113c0 .274.055.536.155.774q-.34.215-.623.498a.875.875 0 1 1-1.237-1.237M12 11.597q-.002.378-.13.712.397.235.724.56a.875.875 0 0 0 1.237-1.237A5.35 5.35 0 0 0 12 10.433zm0-7.491v1.78c1.9.386 3.6 1.33 4.924 2.653A.875.875 0 1 0 18.161 7.3 11.44 11.44 0 0 0 12 4.106M10.063 13.9a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3" />
	),
}

export const wifiExclamationMarkFillIcon: LoadedIconFunction<"fill"> =
	createIcon("wifiExclamationMarkFill", iconDefinition, "fill")
