/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "0.95 1.41 14.1 13.17",
	svg: (
		<path d="M9.934 1.417c.903 0 1.635.733 1.635 1.636v3.23h2.23a1.25 1.25 0 0 1 .885 2.134l-5.8 5.8a1.25 1.25 0 0 1-1.768 0l-5.8-5.8A1.25 1.25 0 0 1 2.2 6.284h2.23v-3.23c0-.904.733-1.637 1.636-1.637z" />
	),
}

export const arrowShapeDownFillSmallIcon: LoadedIconFunction<"fillSmall"> =
	createIcon("arrowShapeDownFillSmall", iconDefinition, "fillSmall")
