/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 21 20",
	fittedViewBox: "0.02 2.12 20.21 15.75",
	svg: (
		<>
			<path d="M16.51 6.722a.875.875 0 0 1 1.237 0l2.254 2.253a.876.876 0 0 1-1.237 1.238l-.76-.76V10A7.875 7.875 0 0 1 4.77 15.77a.875.875 0 1 1 1.191-1.282A6.125 6.125 0 0 0 16.253 10v-.548l-.76.76a.875.875 0 0 1-1.237-1.237z" />
			<path d="M10.003 12a.875.875 0 1 1 0 1.75.875.875 0 0 1 0-1.75m.125-9.875c2.07 0 3.955.8 5.36 2.104a.875.875 0 0 1-1.192 1.283A6.125 6.125 0 0 0 4.003 10v.548l.761-.76a.875.875 0 0 1 1.237 1.237l-2.254 2.253a.875.875 0 0 1-1.237 0L.256 11.025a.876.876 0 0 1 1.238-1.238l.76.76V10a7.875 7.875 0 0 1 7.874-7.875" />
			<path d="M10.003 6.125a.75.75 0 0 1 .75.75v3.5a.75.75 0 0 1-1.5 0v-3.5a.75.75 0 0 1 .75-.75" />
		</>
	),
}

export const arrowCircleLoopExclamationFillIcon: LoadedIconFunction<"fill"> =
	createIcon("arrowCircleLoopExclamationFill", iconDefinition, "fill")
