/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "0.98 0.97 13.45 13.46",
	svg: (
		<path d="M6.4.975a5.425 5.425 0 0 1 5.175 3.8h1.026c1.007 0 1.825.818 1.825 1.826v6a1.826 1.826 0 0 1-1.825 1.825h-6A1.826 1.826 0 0 1 4.775 12.6v-1.028A5.424 5.424 0 0 1 6.4.975m.2 5.05a.575.575 0 0 0-.575.576v6c0 .317.258.575.576.575h6a.576.576 0 0 0 .575-.575v-6a.576.576 0 0 0-.575-.576zm-.2-3.8a4.173 4.173 0 0 0-1.625 8.019V6.6c0-1.008.818-1.826 1.826-1.826h3.643A4.17 4.17 0 0 0 6.4 2.225" />
	),
}

export const squareOnCircleSmallIcon: LoadedIconFunction<"small"> = createIcon(
	"squareOnCircleSmall",
	iconDefinition,
	"small",
)
