/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "0 0 16 16",
	svg: (
		<>
			<g clipPath="url(#clip0_10073_12430)">
				<path d="M4.625 1.6a.625.625 0 0 0-1.25 0v1.775H1.6a.625.625 0 1 0 0 1.25h1.775V10.8c0 1.008.817 1.825 1.825 1.825h6.175V14.4a.625.625 0 1 0 1.25 0v-1.775H14.4a.625.625 0 1 0 0-1.25h-1.775V5.2A1.825 1.825 0 0 0 10.8 3.375H4.625zm0 3.025H10.8c.318 0 .575.258.575.575v6.175H5.2a.575.575 0 0 1-.575-.575z" />
			</g>
			<defs>
				<clipPath id="clip0_10073_12430">
					<path d="M0 0h16v16H0z" />
				</clipPath>
			</defs>
		</>
	),
}

export const cropSmallIcon: LoadedIconFunction<"small"> = createIcon(
	"cropSmall",
	iconDefinition,
	"small",
)
