/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "0.24 2.73 19.27 14.53",
	directional: true,
	svg: (
		<>
			<path d="M13.29 6.49c3.44 0 5.497 3.296 6.01 6.564.14.877.21 1.868.21 2.946a.75.75 0 0 1-.217.527.75.75 0 0 1-1.193-.145c-1.766-3.078-4.723-2.899-4.851-2.884h-.02v3.012a.75.75 0 0 1-1.246.562l-7.3-6.44a.75.75 0 0 1-.006-1.119l7.3-6.59a.752.752 0 0 1 1.252.557v3.01z" />
			<path d="m2.127 10.073 6.923 6.098v.339a.75.75 0 0 1-1.246.562l-7.3-6.429a.75.75 0 0 1-.006-1.12l7.3-6.59a.751.751 0 0 1 1.252.557v.333z" />
		</>
	),
}

export const arrowShapeDoubleUpLeftFillIcon: LoadedIconFunction<"fill"> =
	createIcon("arrowShapeDoubleUpLeftFill", iconDefinition, "fill")
