/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "0.37 2.23 15.26 11.53",
	directional: true,
	svg: (
		<path d="M15.46 10.405c-.49-3.111-2.407-5.202-4.772-5.202l-.013-2.339A.626.626 0 0 0 9.63 2.4L7.379 4.433v-1.56a.626.626 0 0 0-1.044-.465L.581 7.603a.625.625 0 0 0 .006.933l5.754 5.069a.624.624 0 0 0 1.038-.47v-1.522l2.258 1.992a.624.624 0 0 0 1.038-.47v-2.341c.228-.01 2.44-.071 3.775 2.258a.622.622 0 0 0 .994.12.63.63 0 0 0 .181-.439c0-.854-.056-1.638-.165-2.328m-9.33 1.347L1.938 8.06l4.19-3.783V5.56L3.876 7.595a.626.626 0 0 0 .005.933L6.13 10.51zm4.48-2.205h-.56a.626.626 0 0 0-.625.625v1.579L5.233 8.054 9.425 4.27v1.558c0 .345.28.625.625.625h.638c1.993 0 3.212 2.083 3.538 4.148l.038.261c-1.685-1.463-3.593-1.32-3.655-1.315" />
	),
}

export const arrowShapeDoubleUpLeftSmallIcon: LoadedIconFunction<"small"> =
	createIcon("arrowShapeDoubleUpLeftSmall", iconDefinition, "small")
