/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "2.87 2.12 10.97 11.76",
	svg: (
		<path d="M4.75 2.125c-1.036 0-1.875.84-1.875 1.875v3.5c0 1.036.84 1.875 1.875 1.875h5.5c1.036 0 1.875-.84 1.875-1.875V4c0-1.036-.84-1.875-1.875-1.875zM4.125 4c0-.345.28-.625.625-.625h5.5c.345 0 .625.28.625.625v3.5c0 .345-.28.625-.625.625h-5.5a.625.625 0 0 1-.625-.625zM3.5 10.375a.625.625 0 1 0 0 1.25h9.72a.625.625 0 1 0 0-1.25zm0 2.25a.625.625 0 1 0 0 1.25h6.84a.625.625 0 1 0 0-1.25z" />
	),
}

export const captionSmallIcon: LoadedIconFunction<"small"> = createIcon(
	"captionSmall",
	iconDefinition,
	"small",
)
