/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "3.17 1.77 9.66 12.46",
	svg: (
		<path d="M12.825 12.4A1.825 1.825 0 0 1 11 14.225H5a1.825 1.825 0 0 1-1.826-1.824V3.6c0-1.008.818-1.826 1.826-1.826h6c1.007 0 1.824.817 1.825 1.825z" />
	),
}

export const rectangleTallFillSmallIcon: LoadedIconFunction<"fillSmall"> =
	createIcon("rectangleTallFillSmall", iconDefinition, "fillSmall")
