/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "3.17 1.77 9.65 12.45",
	svg: (
		<path d="M11.575 3.6A.575.575 0 0 0 11 3.025H5a.575.575 0 0 0-.575.575v8.8c0 .317.257.575.575.575h6a.575.575 0 0 0 .575-.575zm1.25 8.8A1.826 1.826 0 0 1 11 14.225H5A1.825 1.825 0 0 1 3.175 12.4V3.6c0-1.008.817-1.825 1.825-1.825h6c1.008 0 1.825.817 1.825 1.825z" />
	),
}

export const rectangleTallSmallIcon: LoadedIconFunction<"small"> = createIcon(
	"rectangleTallSmall",
	iconDefinition,
	"small",
)
