/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "2.38 2.37 17.12 17.13",
	svg: (
		<>
			<path d="M10 2.375a7.625 7.625 0 1 0 1.633 15.075 4.6 4.6 0 0 1-.228-1.23 6.375 6.375 0 1 1 4.815-4.814q.643.032 1.23.227A7.625 7.625 0 0 0 10 2.375" />
			<path d="M7.365 9.665c.49 0 .88-.46.88-1.02s-.39-1.02-.88-1.02-.88.46-.88 1.02.39 1.02.88 1.02m-.187 1.872a.625.625 0 0 1 .867.169 2.36 2.36 0 0 0 1.96 1.044c.812 0 1.536-.416 1.96-1.044a.625.625 0 0 1 1.036.698A3.62 3.62 0 0 1 10.005 14a3.6 3.6 0 0 1-2.996-1.596.625.625 0 0 1 .169-.867m5.457-1.872c.49 0 .88-.46.88-1.02s-.39-1.02-.88-1.02-.88.46-.88 1.02.39 1.02.88 1.02M16 19.5a3.5 3.5 0 1 1 0-7 3.5 3.5 0 0 1 0 7m1.969-4.094h-1.375v-1.375a.625.625 0 0 0-1.25 0v1.375h-1.375a.625.625 0 0 0 0 1.25h1.375v1.375a.625.625 0 1 0 1.25 0v-1.375h1.375a.625.625 0 0 0 0-1.25" />
		</>
	),
}

export const emojiFacePlusIcon: LoadedIconFunction<"default"> = createIcon(
	"emojiFacePlus",
	iconDefinition,
	"default",
)
