/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "2.37 2.38 17.13 17.12",
	svg: (
		<>
			<path d="M2.375 10a7.625 7.625 0 1 1 15.075 1.633 4.6 4.6 0 0 0-5.817 5.817A7.625 7.625 0 0 1 2.375 10m5.67 1.706a.625.625 0 0 0-1.036.698A3.6 3.6 0 0 0 10.005 14c1.245 0 2.35-.637 2.996-1.596a.625.625 0 1 0-1.036-.698 2.37 2.37 0 0 1-1.96 1.044 2.36 2.36 0 0 1-1.96-1.044m-.68-2.041c.49 0 .88-.46.88-1.02s-.39-1.02-.88-1.02-.88.46-.88 1.02.39 1.02.88 1.02m6.15-1.02c0-.56-.39-1.02-.88-1.02s-.88.46-.88 1.02.39 1.02.88 1.02.88-.46.88-1.02" />
			<path d="M16 19.5a3.5 3.5 0 1 1 0-7 3.5 3.5 0 0 1 0 7m1.969-2.844a.625.625 0 0 0 0-1.25h-1.375v-1.375a.625.625 0 0 0-1.25 0v1.375h-1.375a.625.625 0 0 0 0 1.25h1.375v1.375a.625.625 0 1 0 1.25 0v-1.375z" />
		</>
	),
}

export const emojiFacePlusFillIcon: LoadedIconFunction<"fill"> = createIcon(
	"emojiFacePlusFill",
	iconDefinition,
	"fill",
)
