/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "2.37 4.12 15.25 11.75",
	svg: (
		<path d="M2.375 6.25c0-1.174.951-2.125 2.125-2.125h11c1.174 0 2.125.951 2.125 2.125V7.5H2.375zm2.883-.441a.625.625 0 1 0-1.25 0 .625.625 0 0 0 1.25 0m1.375.625a.625.625 0 1 0 0-1.25.625.625 0 0 0 0 1.25m2.625-.625a.625.625 0 1 0-1.25 0 .625.625 0 0 0 1.25 0M2.375 8.6v5.15c0 1.174.951 2.125 2.125 2.125h11a2.125 2.125 0 0 0 2.125-2.125V8.6z" />
	),
}

export const browserFillIcon: LoadedIconFunction<"fill"> = createIcon(
	"browserFill",
	iconDefinition,
	"fill",
)
