/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "2.12 3.37 11.75 9.25",
	svg: (
		<path d="M4 3.375c-1.036 0-1.875.84-1.875 1.875v5.5c0 1.036.84 1.875 1.875 1.875h8c1.036 0 1.875-.84 1.875-1.875v-5.5c0-1.036-.84-1.875-1.875-1.875zm-.281 1.323a.425.425 0 1 1 .85 0 .425.425 0 0 1-.85 0m1.6 0a.425.425 0 1 1 .85 0 .425.425 0 0 1-.85 0m1.6 0a.425.425 0 1 1 .85 0 .425.425 0 0 1-.85 0M3.375 10.75V6.022h9.25v4.728c0 .345-.28.625-.625.625H4a.625.625 0 0 1-.625-.625" />
	),
}

export const browserSmallIcon: LoadedIconFunction<"small"> = createIcon(
	"browserSmall",
	iconDefinition,
	"small",
)
