/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "5.82 3.53 8.36 12.78",
	svg: (
		<path d="M7.551 6.77c.184-.738 1.091-1.489 2.413-1.489 1.552 0 2.459.973 2.459 1.797 0 .495-.303 1.023-.928 1.403l-.02.012-1.248.852-.004.003c-.866.599-1.417 1.568-1.417 2.623a.875.875 0 0 0 1.75 0c0-.434.228-.883.66-1.182l1.21-.825c.996-.615 1.747-1.641 1.747-2.886 0-2.132-2.072-3.547-4.209-3.547-1.893 0-3.68 1.093-4.11 2.814a.875.875 0 1 0 1.697.425m3.443 8.289a1.25 1.25 0 1 1-2.5 0 1.25 1.25 0 0 1 2.5 0" />
	),
}

export const questionMarkFillIcon: LoadedIconFunction<"fill"> = createIcon(
	"questionMarkFill",
	iconDefinition,
	"fill",
)
