/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "2.05 1.29 11.9 12.66",
	svg: (
		<path d="M3.575 3.628c0-1.474 1.35-2.58 2.795-2.291l.056.01a2.73 2.73 0 0 1 1.585.956c.399-.484.96-.835 1.61-.964 1.44-.289 2.804.81 2.804 2.29 0 .392-.097.761-.268 1.086h.403c.765 0 1.385.62 1.385 1.385v1.52c0 .432-.198.817-.507 1.071H8.55V4.845h-1.1v3.846H2.562a1.38 1.38 0 0 1-.507-1.07V6.1c0-.766.62-1.386 1.385-1.386h.403a2.3 2.3 0 0 1-.268-1.087m6.523 1.087a1.087 1.087 0 0 0 1.077-1.087c0-.68-.632-1.2-1.31-1.064a1.54 1.54 0 0 0-1.24 1.505v.646zM6.125 2.562a1.087 1.087 0 1 0-.213 2.153h1.463V4.03c0-.708-.5-1.318-1.194-1.456zM2.744 9.791v2.77c0 .764.62 1.384 1.385 1.384H7.45V9.791zm5.806 0v4.154h3.321c.765 0 1.385-.62 1.385-1.385V9.791z" />
	),
}

export const presentFillSmallIcon: LoadedIconFunction<"fillSmall"> = createIcon(
	"presentFillSmall",
	iconDefinition,
	"fillSmall",
)
