/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "1.6 2.85 12.83 10.29",
	svg: (
		<path d="M6.85 8a.75.75 0 0 1 .75-.75h6.08a.75.75 0 1 1 0 1.5H7.6A.75.75 0 0 1 6.85 8m-1.6-4A.75.75 0 0 1 6 3.25h7.6a.75.75 0 0 1 0 1.5H6A.75.75 0 0 1 5.25 4m3.95 7.25a.75.75 0 0 0 0 1.5h4.48a.75.75 0 0 0 0-1.5zM2.035 2.857c-.317 0-.547.333-.369.62l.916 1.464a.44.44 0 0 0 .738 0l.915-1.465c.179-.286-.051-.619-.369-.619zm1.6 4c-.317 0-.547.333-.369.62l.916 1.464a.44.44 0 0 0 .738 0l.915-1.465c.179-.286-.052-.619-.369-.619zm1.6 4c-.317 0-.547.333-.369.62l.916 1.464a.44.44 0 0 0 .738 0l.915-1.465c.179-.286-.051-.619-.369-.619z" />
	),
}

export const listToggleIndentFillSmallIcon: LoadedIconFunction<"fillSmall"> =
	createIcon("listToggleIndentFillSmall", iconDefinition, "fillSmall")
