/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "2.03 3.6 15.94 12.8",
	svg: (
		<path d="M8.626 10c0-.484.392-.876.875-.876h7.6a.875.875 0 1 1 0 1.75H9.5A.875.875 0 0 1 8.626 10m-2-5c0-.484.392-.876.875-.876H17a.875.875 0 0 1 0 1.75H7.5A.875.875 0 0 1 6.626 5m4.874 9.124a.875.875 0 1 0 0 1.75h5.6a.875.875 0 1 0 0-1.75zM2.544 3.603c-.376 0-.643.393-.435.726L3.253 6.16a.52.52 0 0 0 .87 0l1.144-1.83c.208-.333-.058-.726-.435-.726zm2 5c-.376 0-.643.393-.435.726l1.144 1.831a.52.52 0 0 0 .87 0l1.144-1.83c.208-.333-.058-.726-.435-.726zm2 5c-.376 0-.643.393-.435.726l1.144 1.831a.52.52 0 0 0 .87 0l1.144-1.831c.208-.333-.058-.726-.435-.726z" />
	),
}

export const listToggleIndentFillIcon: LoadedIconFunction<"fill"> = createIcon(
	"listToggleIndentFill",
	iconDefinition,
	"fill",
)
