/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "3.09 4.78 13.78 10.46",
	svg: (
		<>
			<path d="M15.276 5.18a.876.876 0 0 1 1.5.9l-5.243 8.74a.876.876 0 0 1-1.415.12l-3.496-4.08A.875.875 0 1 1 7.95 9.723l2.706 3.157zM3.405 9.627a.875.875 0 0 1 1.233.095l2.706 3.157.008-.015 1.2 1.4-.332.556a.876.876 0 0 1-1.414.12L3.31 10.86a.875.875 0 0 1 .095-1.233" />
			<path d="M11.963 5.18a.876.876 0 0 1 1.501.9l-3.15 5.248-1.2-1.401z" />
		</>
	),
}

export const checkmarkDoubleFillIcon: LoadedIconFunction<"fill"> = createIcon(
	"checkmarkDoubleFill",
	iconDefinition,
	"fill",
)
