/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "1.38 1.37 13.25 13.25",
	svg: (
		<>
			<path d="M9.63 1.38H2.88a1.5 1.5 0 0 0-1.5 1.5v6.75a1.5 1.5 0 0 0 1.5 1.5h.9V6.38a2.6 2.6 0 0 1 2.6-2.6h4.75v-.9a1.5 1.5 0 0 0-1.5-1.5" />
			<path d="M6.38 4.88h6.75a1.5 1.5 0 0 1 1.5 1.5v6.75a1.5 1.5 0 0 1-1.5 1.5H6.38a1.5 1.5 0 0 1-1.5-1.5V6.38a1.5 1.5 0 0 1 1.5-1.5" />
		</>
	),
}

export const duplicateFillSmallIcon: LoadedIconFunction<"fillSmall"> =
	createIcon("duplicateFillSmall", iconDefinition, "fillSmall")
