/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "3.11 2.74 12.76 14.52",
	directional: true,
	svg: (
		<path d="M15.875 3.87c0-.868-.942-1.409-1.692-.971L3.676 9.029a1.125 1.125 0 0 0 0 1.943l10.507 6.13a1.125 1.125 0 0 0 1.692-.972z" />
	),
}

export const arrowCaretLeftFillIcon: LoadedIconFunction<"fill"> = createIcon(
	"arrowCaretLeftFill",
	iconDefinition,
	"fill",
)
