/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "2.22 1.95 10.61 12.09",
	directional: true,
	svg: (
		<path d="M12.825 2.835a.875.875 0 0 0-1.316-.756L2.655 7.245a.875.875 0 0 0 0 1.512l8.854 5.165a.875.875 0 0 0 1.316-.756zM3.84 8l7.735-4.512v9.024z" />
	),
}

export const arrowCaretLeftSmallIcon: LoadedIconFunction<"small"> = createIcon(
	"arrowCaretLeftSmall",
	iconDefinition,
	"small",
)
