/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "2.37 2.25 17.13 13.63",
	svg: (
		<>
			<path d="M19.5 4.75a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0" />
			<path d="M13.302 4.125H4.5A2.125 2.125 0 0 0 2.375 6.25v7.5c0 1.174.951 2.125 2.125 2.125h11a2.125 2.125 0 0 0 2.125-2.125V8.448a3.8 3.8 0 0 1-1.25 0v5.293l-3.741-3.74 2.193-2.194a3.8 3.8 0 0 1-.884-.884L10 10.866 4.51 5.375h8.793a3.8 3.8 0 0 1 0-1.25M3.625 6.259l3.741 3.74-3.741 3.742zm11.866 8.366H4.51l3.741-3.741 1.308 1.308c.244.244.64.244.884 0l1.308-1.308z" />
		</>
	),
}

export const envelopeBadgeIcon: LoadedIconFunction<"default"> = createIcon(
	"envelopeBadge",
	iconDefinition,
	"default",
)
