/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "2.19 2.38 12.61 10.17",
	svg: (
		<path d="M12.805 6.387a2 2 0 1 0 0-4 2 2 0 0 0 0 4M4 3.45h5.849a3.1 3.1 0 0 0 .434 2.74L8 8.472 3.177 3.65c.247-.127.526-.199.823-.199m6.03 4.547 1.041-1.041a3.09 3.09 0 0 0 2.729.367v3.426c0 .296-.071.575-.198.821zM2.399 4.427a1.8 1.8 0 0 0-.2.823v5.5c.001.296.072.575.199.821L5.97 7.998zM4 12.55c-.298 0-.578-.072-.826-.2l3.574-3.574.863.863a.55.55 0 0 0 .778 0l.863-.863 3.573 3.574c-.247.128-.527.2-.825.2z" />
	),
}

export const envelopeBadgeFillSmallIcon: LoadedIconFunction<"fillSmall"> =
	createIcon("envelopeBadgeFillSmall", iconDefinition, "fillSmall")
