/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "2.37 2.24 17.13 13.63",
	svg: (
		<path d="M17 7.25a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5M4.5 4.125h8.802a3.73 3.73 0 0 0 .642 2.798L10 10.866 3.505 4.372c.297-.158.636-.247.995-.247M12.634 10l2.193-2.193a3.73 3.73 0 0 0 2.798.641v5.302c0 .36-.09.698-.247.994zM2.622 5.256a2.1 2.1 0 0 0-.247.994v7.5c0 .36.09.698.247.994L7.366 10zM4.5 15.875c-.36 0-.698-.09-.995-.247l4.745-4.744 1.308 1.308c.244.244.64.244.884 0l1.308-1.308 4.745 4.744a2.1 2.1 0 0 1-.995.247z" />
	),
}

export const envelopeBadgeFillIcon: LoadedIconFunction<"fill"> = createIcon(
	"envelopeBadgeFill",
	iconDefinition,
	"fill",
)
