/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "3.67 2.67 12.65 15.64",
	svg: (
		<path d="m4.897 3.086-.122-.143a.625.625 0 0 0-.95.814l3.83 4.468-.003.034-.039.013a4.325 4.325 0 0 0-2.938 4.097V13c0 .18.146.325.325.325h4.13v3.38c0 .158.035.317.1.46l.433.94a.35.35 0 0 0 .565.102l.063-.086.44-.956c.065-.142.1-.3.1-.46v-3.38h1.196l3.199 3.732a.625.625 0 0 0 1.04-.67L4.99 3.229a.6.6 0 0 1-.093-.143m10.321 10.156a.32.32 0 0 0 .107-.242v-.63a4.325 4.325 0 0 0-2.938-4.098l-.039-.013-.19-1.945.402-.359a3.33 3.33 0 0 0 1.112-2.481V3a.325.325 0 0 0-.325-.325H6.653a.325.325 0 0 0-.307.217z" />
	),
}

export const pinSlashFillIcon: LoadedIconFunction<"fill"> = createIcon(
	"pinSlashFill",
	iconDefinition,
	"fill",
)
