/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "2.94 2.14 10.11 12.5",
	svg: (
		<path d="m4.145 2.657-.227-.265a.55.55 0 1 0-.836.716l3.016 3.518-.004.001A3.45 3.45 0 0 0 3.75 9.895v.505c0 .138.112.25.25.25h3.305v2.714c0 .126.027.253.08.368l.345.752a.28.28 0 0 0 .452.082l.05-.07.352-.764a.9.9 0 0 0 .08-.367V10.65h.883l2.535 2.958a.55.55 0 0 0 .843-.707L4.152 2.666zm8.104 7.765.001-.022v-.505a3.45 3.45 0 0 0-2.344-3.268l-.037-.012-.153-1.567.326-.291a2.65 2.65 0 0 0 .886-1.978V2.4a.25.25 0 0 0-.25-.25H5.322a.25.25 0 0 0-.131.037z" />
	),
}

export const pinSlashFillSmallIcon: LoadedIconFunction<"fillSmall"> =
	createIcon("pinSlashFillSmall", iconDefinition, "fillSmall")
