/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "2.37 2.4 15.25 15.19",
	svg: (
		<path d="M3.893 2.876a.626.626 0 0 1 .881.067l.126.147a.6.6 0 0 0 .088.14L16.26 16.38a.622.622 0 0 1-1.034.677l-1.657-1.931H8.702l1.407 1.407a.625.625 0 0 1-.883.884L6.75 14.942a.626.626 0 0 1-.08-.786l.08-.098 2.476-2.475a.626.626 0 0 1 .883.884L8.7 13.876h3.798L5.854 6.125H4.8c-.649 0-1.175.527-1.175 1.175v5.975a.625.625 0 0 1-1.25 0V7.3a2.426 2.426 0 0 1 2.408-2.425l-.958-1.118a.626.626 0 0 1 .068-.881M17 6.1c.345 0 .625.28.625.625V12.7a2.42 2.42 0 0 1-1.122 2.042l-.83-.968c.413-.183.702-.594.702-1.074V6.725c0-.345.28-.625.625-.625M9.89 2.584a.625.625 0 0 1 .884 0l2.476 2.474c.213.214.24.544.08.786l-.08.098-2.31 2.309-.816-.953L11.3 6.125H9.117l-1.071-1.25h3.252L9.89 3.467a.626.626 0 0 1 0-.883" />
	),
}

export const arrowSquareLeftRightSlashIcon: LoadedIconFunction<"default"> =
	createIcon("arrowSquareLeftRightSlash", iconDefinition, "default")
