/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "1.65 1.66 12.7 12.65",
	svg: (
		<path d="M3.012 2.18a.75.75 0 0 1 1.057.082l.182.213q.032.077.087.143l8.835 10.308a.748.748 0 0 1-1.242.812l-1.19-1.388H7.563l.7.7a.75.75 0 0 1-1.06 1.06l-1.98-1.979a.75.75 0 0 1 0-1.062l1.98-1.979a.75.75 0 0 1 .556-.218L4.57 5.151h-.73a.69.69 0 0 0-.69.689v4.78a.75.75 0 0 1-1.5 0V5.84a2.19 2.19 0 0 1 1.685-2.13l-.404-.472a.75.75 0 0 1 .08-1.057m5.463 7.526a.74.74 0 0 1-.21.444l-.7.7h1.89zM13.6 4.63a.75.75 0 0 1 .75.75v4.78c0 .64-.276 1.214-.714 1.614l-.977-1.14a.7.7 0 0 0 .192-.474V5.38a.75.75 0 0 1 .75-.75M7.735 1.89a.75.75 0 0 1 1.062 0l1.98 1.98a.75.75 0 0 1 0 1.06L9.156 6.55l-.98-1.143.258-.255h-.476l-1.286-1.5h1.763l-.7-.7a.75.75 0 0 1 0-1.061" />
	),
}

export const arrowSquareLeftRightSlashFillSmallIcon: LoadedIconFunction<"fillSmall"> =
	createIcon("arrowSquareLeftRightSlashFillSmall", iconDefinition, "fillSmall")
