/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "2.4 2.88 15.21 14.27",
	svg: (
		<>
			<path d="M7.975 5.175a.55.55 0 1 0 0 1.1h4.05a.55.55 0 1 0 0-1.1zm-.55 2.692a.55.55 0 0 1 .55-.55h4.05a.55.55 0 1 1 0 1.1h-4.05a.55.55 0 0 1-.55-.55" />
			<path d="M2.4 4.861c0-1.092.883-1.975 1.975-1.975h8.55c1.092 0 1.975.883 1.975 1.975v7.889h2.075c.345 0 .625.28.625.625v1.8a1.973 1.973 0 0 1-1.975 1.975h-8.55A1.973 1.973 0 0 1 5.1 15.175V7.25H3.025a.625.625 0 0 1-.625-.625zM9.554 15.9h6.07a.723.723 0 0 0 .726-.725V14H9.5v1.175c0 .256-.049.5-.137.725zm-2.025 0c.4-.002.72-.325.72-.725v-1.8c0-.345.28-.625.626-.625h4.775V4.861a.723.723 0 0 0-.725-.725H6.213c.088.224.137.469.137.725v10.314c0 .402.323.725.725.725zM5.1 4.861a.723.723 0 0 0-.724-.725.723.723 0 0 0-.725.725V6H5.1z" />
		</>
	),
}

export const scrollIcon: LoadedIconFunction<"default"> = createIcon(
	"scroll",
	iconDefinition,
	"default",
)
