/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "1.94 2.33 12.11 11.36",
	svg: (
		<>
			<path d="M6.43 5.25h3.15a.58.58 0 0 0 0-1.16H6.43a.58.58 0 0 0 0 1.16m0 1.67h3.15a.58.58 0 0 0 0-1.16H6.43a.58.58 0 0 0 0 1.16" />
			<path d="M11.95 10h1.47c.35 0 .63.28.63.62v1.4c0 .92-.76 1.67-1.68 1.67H5.72c-.93 0-1.68-.75-1.68-1.67V6H2.57c-.34 0-.62-.29-.62-.63V4c0-.92.75-1.67 1.67-1.67h6.66c.92 0 1.67.75 1.67 1.67zm.85 2.03v-.78H7.75v.78c0 .14-.01.28-.05.42h4.68c.23 0 .42-.19.42-.42m-2.52-8.45H5.25c.03.13.05.28.05.42v8.02c0 .23.19.42.42.42h.36c.24 0 .42-.19.42-.42v-1.4c0-.34.28-.62.62-.62h3.58V4c0-.23-.19-.42-.42-.42m-6.66 0c-.23 0-.42.19-.42.42h-.01v.75h.85V4c0-.23-.19-.42-.42-.42" />
		</>
	),
}

export const scrollSmallIcon: LoadedIconFunction<"small"> = createIcon(
	"scrollSmall",
	iconDefinition,
	"small",
)
