/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "2.84 3.79 10.58 8.41",
	svg: (
		<path d="M3.848 10.2a1 1 0 1 1-.001 2.001 1 1 0 0 1 0-2m9.079.387a.625.625 0 0 1 0 1.225l-.126.012h-6a.625.625 0 0 1 0-1.25h6zM3.848 3.8a1 1 0 1 1-.001 2 1 1 0 0 1 0-2m9.079.388a.625.625 0 0 1 0 1.224l-.126.013h-6a.625.625 0 0 1 0-1.25h6z" />
	),
}

export const listBulletSmallIcon: LoadedIconFunction<"small"> = createIcon(
	"listBulletSmall",
	iconDefinition,
	"small",
)
