/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "1.67 3.1 13.02 9.79",
	svg: (
		<path d="M3.17 3.86a.75.75 0 1 0-1.5 0v8.28a.75.75 0 0 0 1.5 0V8.57h4.62v3.57a.75.75 0 0 0 1.5 0V3.86a.75.75 0 1 0-1.5 0v3.21H3.17zm8.064 4.227c.11-.264.438-.518.884-.518.604 0 .935.417.935.74a.62.62 0 0 1-.17.422L9.82 11.59a.75.75 0 0 0 .512 1.299h3.6a.75.75 0 0 0 0-1.5h-1.7l1.693-1.582.034-.033a2.13 2.13 0 0 0 .593-1.466c0-1.318-1.18-2.24-2.435-2.24-.994 0-1.904.567-2.269 1.44a.75.75 0 0 0 1.384.578" />
	),
}

export const textH2FillSmallIcon: LoadedIconFunction<"fillSmall"> = createIcon(
	"textH2FillSmall",
	iconDefinition,
	"fillSmall",
)
