/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "2.4 1.83 15.2 15.32",
	svg: (
		<>
			<path d="m5.824 7.516.484-2.9a3.325 3.325 0 0 1 3.28-2.779h.825a3.325 3.325 0 0 1 3.28 2.779l.483 2.9q.53.06 1.058.137c.402.058.766.23 1.058.483l-.5.761c-2.857 3.687-8.748 3.681-11.596-.016l-.01-.011-.546-.672a2.06 2.06 0 0 1 1.126-.545q.528-.077 1.058-.137M7.541 4.82l-.429 2.57a37 37 0 0 1 5.776 0l-.428-2.57a2.075 2.075 0 0 0-2.047-1.734h-.826c-1.014 0-1.88.734-2.046 1.734" />
			<path d="m16.7 9.519.234-.358q.039.144.057.294l.591 4.989a2.425 2.425 0 0 1-2.408 2.71H4.826a2.425 2.425 0 0 1-2.408-2.71l.591-4.989q.015-.12.042-.238l.278.341c1.45 1.878 3.57 2.93 5.771 3.154v1.455c0 .248.202.45.45.45h.9a.45.45 0 0 0 .45-.45v-1.455c2.203-.225 4.326-1.278 5.776-3.16z" />
		</>
	),
}

export const handbagFillIcon: LoadedIconFunction<"fill"> = createIcon(
	"handbagFill",
	iconDefinition,
	"fill",
)
