/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 17 16",
	fittedViewBox: "1.47 1.38 14.55 14.47",
	svg: (
		<>
			<path d="M14.906 9.936a.626.626 0 0 1 1.013.732l-3.558 4.925a.627.627 0 0 1-.942.083l-2.372-2.299a.625.625 0 1 1 .87-.897l1.853 1.794z" />
			<path d="M13.224 4.882a1.5 1.5 0 0 1 1.5 1.5v2.177a1.87 1.87 0 0 0-.832.645l-2.29 3.17-.816-.792a1.875 1.875 0 0 0-2.61 2.693l.368.357h-2.07a1.5 1.5 0 0 1-1.5-1.5v-6.75a1.5 1.5 0 0 1 1.5-1.5z" />
			<path d="M9.724 1.382a1.5 1.5 0 0 1 1.5 1.5v.8h-4.75a2.7 2.7 0 0 0-2.7 2.7v4.75h-.8a1.5 1.5 0 0 1-1.5-1.5v-6.75a1.5 1.5 0 0 1 1.5-1.5z" />
		</>
	),
}

export const duplicateCheckFillSmallIcon: LoadedIconFunction<"fillSmall"> =
	createIcon("duplicateCheckFillSmall", iconDefinition, "fillSmall")
