/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "3.99 1.37 8.01 13.26",
	svg: (
		<>
			<path d="M8 3.8a.825.825 0 1 0 0 1.65.825.825 0 0 0 0-1.65" />
			<path d="M8 1.375a4 4 0 0 0-2.125 7.39v3.922c0 .18.078.352.213.47l1.5 1.313a.625.625 0 0 0 .824 0l1.5-1.312a.625.625 0 0 0 .063-.877l-.777-.906.777-.906a.63.63 0 0 0 .15-.406V8.764A4 4 0 0 0 8 1.374m-2.75 4a2.75 2.75 0 1 1 3.972 2.464.63.63 0 0 0-.347.56V9.83L7.9 10.968c-.2.234-.2.58 0 .814l.723.842L8 13.17l-.875-.765V8.399a.63.63 0 0 0-.347-.56A2.75 2.75 0 0 1 5.25 5.375" />
		</>
	),
}

export const keySmallIcon: LoadedIconFunction<"small"> = createIcon(
	"keySmall",
	iconDefinition,
	"small",
)
