/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "1.94 2.09 12.07 11.91",
	svg: (
		<path d="M5.472 2.52a1.197 1.197 0 0 0-1.68-.141l-.696.583a3.23 3.23 0 0 0-1.128 2.894 9.376 9.376 0 0 0 8.336 8.114l.128.013a3.28 3.28 0 0 0 2.867-1.177l.447-.542a1.16 1.16 0 0 0-.143-1.618l-2.37-2.014a1.345 1.345 0 0 0-1.822.074l-.888.888-1.996-1.996.888-.888c.496-.496.527-1.29.073-1.823zM3.9 3.92l.656-.55 1.981 2.327a.095.095 0 0 1-.005.13l-1.33 1.33a.625.625 0 0 0 0 .883l2.88 2.88a.625.625 0 0 0 .884 0l1.33-1.33a.095.095 0 0 1 .129-.005l2.3 1.954-.39.473a2.03 2.03 0 0 1-1.774.728l-.128-.014a8.13 8.13 0 0 1-7.225-7.032c-.087-.67.174-1.34.692-1.774" />
	),
}

export const phoneSmallIcon: LoadedIconFunction<"small"> = createIcon(
	"phoneSmall",
	iconDefinition,
	"small",
)
