/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "1.62 1.62 16.75 16.75",
	svg: (
		<path d="M10 15.125c.345 0 .625.28.625.625v2a.625.625 0 1 1-1.25 0v-2c0-.345.28-.625.625-.625m-4.508-1.501a.625.625 0 0 1 .884.884l-1.415 1.415a.626.626 0 0 1-.884-.885zm8.131 0a.625.625 0 0 1 .884 0l1.414 1.414a.626.626 0 0 1-.884.885l-1.414-1.415a.626.626 0 0 1 0-.884M10 6a4 4 0 1 1 0 8 4 4 0 0 1 0-8m0 1.25a2.75 2.75 0 1 0 0 5.5 2.75 2.75 0 0 0 0-5.5M4.25 9.375a.625.625 0 1 1 0 1.25h-2a.625.625 0 1 1 0-1.25zm13.5 0a.625.625 0 1 1 0 1.25h-2a.625.625 0 1 1 0-1.25zM4.077 4.078a.626.626 0 0 1 .885 0l1.414 1.414a.626.626 0 0 1-.884.885L4.077 4.962a.626.626 0 0 1 0-.884m10.96 0a.625.625 0 0 1 .884.884l-1.414 1.415a.626.626 0 0 1-.884-.885zM10 1.625c.345 0 .625.28.625.625v2a.625.625 0 1 1-1.25 0v-2c0-.345.28-.625.625-.625" />
	),
}

export const sunIcon: LoadedIconFunction<"default"> = createIcon(
	"sun",
	iconDefinition,
	"default",
)
