/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "1.37 1.37 13.25 13.25",
	svg: (
		<path d="M3.09 1.375c-.947 0-1.715.768-1.715 1.715v.672a.625.625 0 1 0 1.25 0V3.09c0-.257.208-.465.465-.465h.672a.625.625 0 1 0 0-1.25zm2.488 0a.625.625 0 1 0 0 1.25h1.344a.625.625 0 0 0 0-1.25zm3.16 0a.625.625 0 1 0 0 1.25h.672c.257 0 .465.208.465.465v.672a.625.625 0 1 0 1.25 0V3.09c0-.947-.768-1.715-1.715-1.715zm-1.988 3.5c-1.036 0-1.875.84-1.875 1.875v6c0 1.036.84 1.875 1.875 1.875h6c1.036 0 1.875-.84 1.875-1.875v-6c0-1.036-.84-1.875-1.875-1.875zM6.125 6.75c0-.345.28-.625.625-.625h6c.345 0 .625.28.625.625v6c0 .345-.28.625-.625.625h-6a.625.625 0 0 1-.625-.625zM2 4.953a.625.625 0 0 0-.625.625v1.344a.625.625 0 1 0 1.25 0V5.578A.625.625 0 0 0 2 4.953m0 3.16a.625.625 0 0 0-.625.625v.672c0 .947.768 1.715 1.715 1.715h.672a.625.625 0 1 0 0-1.25H3.09a.465.465 0 0 1-.465-.465v-.672A.625.625 0 0 0 2 8.113" />
	),
}

export const squareOnSquareDashedSmallIcon: LoadedIconFunction<"small"> =
	createIcon("squareOnSquareDashedSmall", iconDefinition, "small")
