/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "1.37 3.06 17.25 14.87",
	svg: (
		<path d="M15.625 7.492V5.188A2.125 2.125 0 0 0 13.5 3.063h-10a2.125 2.125 0 0 0-2.125 2.125v6.5c0 1.173.951 2.124 2.125 2.124h.188v2.045a.625.625 0 0 0 1.006.496l3.231-2.486v.325c0 .905.733 1.638 1.638 1.638h3.262l2.558 1.968a.625.625 0 0 0 1.006-.496V15.83h.599c.904 0 1.637-.733 1.637-1.638V9.13c0-.905-.733-1.638-1.637-1.638zm-1.25-2.304v2.304H9.563c-.905 0-1.638.733-1.638 1.638v3.432h-.142a.63.63 0 0 0-.38.13l-2.465 1.896v-1.4a.625.625 0 0 0-.625-.626H3.5a.875.875 0 0 1-.875-.874v-6.5c0-.484.392-.875.875-.875h10c.483 0 .875.391.875.875M9.563 8.742h7.425c.214 0 .387.174.387.388v5.062a.387.387 0 0 1-.387.388h-1.224a.625.625 0 0 0-.625.625v.828l-1.72-1.324a.63.63 0 0 0-.382-.13H9.563a.39.39 0 0 1-.388-.387V9.13c0-.214.174-.388.388-.388" />
	),
}

export const chatIcon: LoadedIconFunction<"default"> = createIcon(
	"chat",
	iconDefinition,
	"default",
)
