/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "2.98 2.12 9.87 11.75",
	svg: (
		<path d="M11.922 2.546c-2.801-.784-4.793-.452-5.879.834-.883 1.046-.993 2.532-.664 3.994H3.845a.625.625 0 1 0 0 1.25h1.901c.385 1.325.262 2.136-.063 2.668-.37.604-1.107 1.03-2.244 1.357a.625.625 0 0 0 .172 1.226h8.61a.625.625 0 0 0 0-1.25H6.19c.213-.2.402-.425.558-.68.533-.873.624-1.97.291-3.321h3.758a.625.625 0 1 0 0-1.25h-4.13c-.372-1.37-.238-2.513.331-3.188.602-.713 1.94-1.177 4.587-.436a.625.625 0 1 0 .337-1.204" />
	),
}

export const poundSignSmallIcon: LoadedIconFunction<"small"> = createIcon(
	"poundSignSmall",
	iconDefinition,
	"small",
)
