/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "3.44 2.19 9.11 11.61",
	svg: (
		<>
			<path d="M8.459 8.97v-.556a.459.459 0 0 0-.918 0v.556zm-.042 1.362a.417.417 0 1 1-.834 0 .417.417 0 0 1 .834 0" />
			<path d="M5.125 2.2h2.679v3.006a1.7 1.7 0 0 0 1.7 1.7h3.046v5.219c0 .925-.75 1.675-1.675 1.675h-5.75c-.925 0-1.675-.75-1.675-1.675v-8.25c0-.925.75-1.675 1.675-1.675M8 7.205c-.668 0-1.209.541-1.209 1.21v.714a1 1 0 0 0-.459.841v.78a1 1 0 0 0 1 1h1.336a1 1 0 0 0 1-1v-.78a1 1 0 0 0-.46-.84v-.716c0-.668-.54-1.209-1.208-1.209" />
			<path d="M12.06 5.407c.145.145.261.315.344.5h-2.9a.7.7 0 0 1-.7-.7V2.328c.2.083.383.205.54.362z" />
		</>
	),
}

export const lockDocFillSmallIcon: LoadedIconFunction<"fillSmall"> = createIcon(
	"lockDocFillSmall",
	iconDefinition,
	"fillSmall",
)
