/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "3.53 3.53 8.94 8.94",
	directional: true,
	svg: (
		<path d="M4.795 3.734c-.28-.28-.745-.27-1.038.023s-.303.758-.023 1.038l6.168 6.167h-4.3a.75.75 0 0 0 0 1.5h6.11a.75.75 0 0 0 .75-.75v-6.11a.75.75 0 0 0-1.5 0v4.3z" />
	),
}

export const arrowDiagonalDownRightFillSmallIcon: LoadedIconFunction<"fillSmall"> =
	createIcon("arrowDiagonalDownRightFillSmall", iconDefinition, "fillSmall")
