/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "4.16 4.16 11.66 11.66",
	directional: true,
	svg: (
		<path d="M5.637 4.4c-.324-.324-.864-.31-1.205.032s-.356.881-.032 1.205l8.437 8.438H7.313a.875.875 0 0 0 0 1.75h7.637a.875.875 0 0 0 .875-.875V7.313a.875.875 0 1 0-1.75 0v5.524z" />
	),
}

export const arrowDiagonalDownRightFillIcon: LoadedIconFunction<"fill"> =
	createIcon("arrowDiagonalDownRightFill", iconDefinition, "fill")
