/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "1.55 2.54 12.9 10.23",
	svg: (
		<>
			<path d="M8 6.43a1.698 1.698 0 1 1 0 3.396 1.698 1.698 0 0 1 0-3.395" />
			<path d="M9.16 2.555a1.85 1.85 0 0 1 1.51.989l.383.733H13c.8 0 1.45.65 1.45 1.45v5.601l-.008.149a1.45 1.45 0 0 1-1.294 1.293l-.148.007H3a1.45 1.45 0 0 1-1.442-1.3l-.008-.149v-5.6c0-.8.65-1.45 1.45-1.45h1.946l.383-.734a1.85 1.85 0 0 1 1.64-.994H9.03zM8 5.33a2.797 2.797 0 1 0 0 5.594A2.797 2.797 0 0 0 8 5.33m3.938.772a.6.6 0 1 0 0 1.2.6.6 0 0 0 0-1.2" />
		</>
	),
}

export const cameraFillSmallIcon: LoadedIconFunction<"fillSmall"> = createIcon(
	"cameraFillSmall",
	iconDefinition,
	"fillSmall",
)
