/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import type { IconGroup } from "../../iconUtils"
import { createIconGroup } from "../../iconUtils"

export const cameraIconGroup: IconGroup<
	"default" | "small" | "fill" | "fillSmall"
> = createIconGroup(
	"camera",
	{
		default: {
			loader: () =>
				import(
					/* webpackChunkName: "icon-camera" */
					"./default.icon"
				),
		},
		small: {
			loader: () =>
				import(
					/* webpackChunkName: "icon-camera" */
					"./small.icon"
				),
		},
		fill: {
			loader: () =>
				import(
					/* webpackChunkName: "icon-camera" */
					"./fill.icon"
				),
		},
		fillSmall: {
			loader: () =>
				import(
					/* webpackChunkName: "icon-camera" */
					"./fillSmall.icon"
				),
		},
	},
	["photo", "pic", "snap", "capture", "upload", "file"],
)
