/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "4.37 2.12 11.23 15.76",
	svg: (
		<path d="M4.431 17.309c.17.452.675.68 1.128.51a8.2 8.2 0 0 0 4.439-3.992 8.2 8.2 0 0 0 4.445 3.992.875.875 0 0 0 .614-1.638 6.44 6.44 0 0 1-4.182-6.034V5.113l2.256 2.256A.875.875 0 1 0 14.37 6.13l-3.75-3.75a.875.875 0 0 0-1.238 0l-3.75 3.75A.875.875 0 1 0 6.87 7.37l2.256-2.257v5.022a6.46 6.46 0 0 1-4.184 6.047.875.875 0 0 0-.51 1.127" />
	),
}

export const arrowMergeUpFillIcon: LoadedIconFunction<"fill"> = createIcon(
	"arrowMergeUpFill",
	iconDefinition,
	"fill",
)
