/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "5.96 2.05 4.08 11.91",
	svg: (
		<path d="M8.584 2.544a.75.75 0 0 1 1.433.435L7.438 13.382l-.021.074a.75.75 0 0 1-1.434-.434L8.561 2.617z" />
	),
}

export const slashFillSmallIcon: LoadedIconFunction<"fillSmall"> = createIcon(
	"slashFillSmall",
	iconDefinition,
	"fillSmall",
)
