/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "3.9 2.75 12.18 14.49",
	svg: (
		<path d="M12.626 2.768a.625.625 0 0 1 0 1.224l-.126.013h-.125v4.794l3.366 5.159c.893 1.369-.03 3.17-1.623 3.281l-.156.006H6.039c-1.688 0-2.703-1.873-1.78-3.287l3.366-5.157V4.005H7.5a.625.625 0 0 1 0-1.25h5zM8.875 9.173l-.102.156-1.567 2.401h5.589l-1.569-2.403-.101-.156V4.005h-2.25z" />
	),
}

export const beakerIcon: LoadedIconFunction<"default"> = createIcon(
	"beaker",
	iconDefinition,
	"default",
)
