/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "0.94 1.41 14.11 13.17",
	svg: (
		<path d="M11.57 12.947c0 .903-.733 1.636-1.637 1.636H6.066a1.637 1.637 0 0 1-1.636-1.636v-3.23H2.2a1.25 1.25 0 0 1-.884-2.135l5.8-5.8a1.25 1.25 0 0 1 1.768 0l5.8 5.8a1.25 1.25 0 0 1-.884 2.134h-2.23zm-5.89 0c0 .187.133.343.309.379l.077.007h3.867l.079-.008c.15-.03.27-.15.3-.3l.008-.078v-4.4a.08.08 0 0 1 .049-.074l.031-.007h3.4L8 2.666l-5.8 5.8h3.4a.08.08 0 0 1 .08.08z" />
	),
}

export const arrowShapeUpSmallIcon: LoadedIconFunction<"small"> = createIcon(
	"arrowShapeUpSmall",
	iconDefinition,
	"small",
)
