/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "1.95 1.97 12.1 12.08",
	svg: (
		<>
			<path d="M8.5 7.12V1.97a6.04 6.04 0 0 1 4.423 2.513zm.433.906 4.346 2.931A6 6 0 0 0 14.05 8c0-.954-.22-1.856-.614-2.659z" />
			<path d="M7.5 8V1.97a6.05 6.05 0 1 0 5.22 9.816l-5-3.371A.5.5 0 0 1 7.5 8" />
		</>
	),
}

export const viewChartFillSmallIcon: LoadedIconFunction<"fillSmall"> =
	createIcon("viewChartFillSmall", iconDefinition, "fillSmall")
