/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "1.28 3.52 17.42 12.96",
	svg: (
		<path d="M10.45 3.525a6.48 6.48 0 0 0-6.384 5.39 3.856 3.856 0 0 0 1.056 7.56H15.2a3.494 3.494 0 0 0 1.725-6.532 6.475 6.475 0 0 0-6.475-6.418m-.075 3.25c.345 0 .625.28.625.625v3.15a.625.625 0 1 1-1.25 0V7.4c0-.345.28-.625.625-.625m0 6.775a.75.75 0 1 1 0-1.5.75.75 0 0 1 0 1.5" />
	),
}

export const cloudExclamationFillIcon: LoadedIconFunction<"fill"> = createIcon(
	"cloudExclamationFill",
	iconDefinition,
	"fill",
)
