/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "2.24 2.25 15.51 15.51",
	svg: (
		<path d="M2.25 5a2.75 2.75 0 1 1 3.625 2.608V12.5c0 .898.728 1.625 1.625 1.625h4.892a2.751 2.751 0 1 1 0 1.75H7.5A3.375 3.375 0 0 1 4.125 12.5V7.608A2.75 2.75 0 0 1 2.25 5M5 4a1 1 0 1 0 0 2 1 1 0 0 0 0-2m9 11a1 1 0 1 0 2 0 1 1 0 0 0-2 0" />
	),
}

export const nodeTopLeftBottomRightFillIcon: LoadedIconFunction<"fill"> =
	createIcon("nodeTopLeftBottomRightFill", iconDefinition, "fill")
