/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "1.74 1.75 12.5 12.5",
	svg: (
		<path d="M1.75 4a2.25 2.25 0 1 1 3 2.122V10c0 .69.56 1.25 1.25 1.25h3.878a2.25 2.25 0 1 1 0 1.5H6A2.75 2.75 0 0 1 3.25 10V6.122A2.25 2.25 0 0 1 1.75 4M4 3.25a.75.75 0 1 0 0 1.5.75.75 0 0 0 0-1.5M11.25 12a.75.75 0 1 0 1.5 0 .75.75 0 0 0-1.5 0" />
	),
}

export const nodeTopLeftBottomRightFillSmallIcon: LoadedIconFunction<"fillSmall"> =
	createIcon("nodeTopLeftBottomRightFillSmall", iconDefinition, "fillSmall")
