/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "1 0.12 17.94 19.75",
	svg: (
		<>
			<path d="M7.733.203a.626.626 0 0 1 .87.286l2.567 5.583 1.41.777 1.722-2.257a.55.55 0 0 1 .874.668l-1.624 2.125 3.87 2.135c.198.11.322.32.322.547v5.648a.63.63 0 0 1-.323.547l-6.408 3.535a.63.63 0 0 1-.604 0l-6.407-3.535a.63.63 0 0 1-.323-.547V10.58L1.054 4.534a.625.625 0 0 1 .271-.795zM4.929 15.346l5.232 2.887v-4.307L4.93 11.04zm6.332-1.42v4.307l5.233-2.887v-4.307zM5.519 10.11l5.192 2.864 5.192-2.864-3.117-1.72-1.75 2.295a.55.55 0 0 1-.875-.668l1.652-2.164-1.102-.608zM2.426 4.557l2.042 4.705 5.419-2.99-2.14-4.65zm14.706.177 1.364.314a.55.55 0 1 1-.248 1.071l-1.364-.314a.55.55 0 0 1 .248-1.071" />
			<path d="M12.873 1.548a.55.55 0 0 1 .753.192l.684 1.15a.55.55 0 0 1-.946.561l-.683-1.149a.55.55 0 0 1 .192-.754m3.802-.041a.55.55 0 0 1 .889.649l-.871 1.193a.55.55 0 0 1-.89-.649z" />
		</>
	),
}

export const boxOpenSparkleIcon: LoadedIconFunction<"default"> = createIcon(
	"boxOpenSparkle",
	iconDefinition,
	"default",
)
