/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "2.37 2.87 15.25 14.25",
	svg: (
		<>
			<path d="M13.5 12.375a.625.625 0 1 1 0 1.25h-3.25a.625.625 0 1 1 0-1.25zM6.035 6.832a.625.625 0 0 1 .883-.047l2.5 2.25a.626.626 0 0 1 0 .93l-2.5 2.25a.625.625 0 0 1-.836-.93L8.065 9.5 6.082 7.715a.625.625 0 0 1-.047-.883" />
			<path d="M15.5 2.875c1.174 0 2.125.951 2.125 2.125v10a2.125 2.125 0 0 1-2.125 2.125h-11A2.125 2.125 0 0 1 2.375 15V5c0-1.174.951-2.125 2.125-2.125zm-11 1.25A.875.875 0 0 0 3.625 5v10c0 .483.392.875.875.875h11a.875.875 0 0 0 .875-.875V5a.875.875 0 0 0-.875-.875z" />
		</>
	),
}

export const terminalIcon: LoadedIconFunction<"default"> = createIcon(
	"terminal",
	iconDefinition,
	"default",
)
