/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "2.37 2.87 15.25 14.25",
	svg: (
		<path d="M15.5 2.875c1.174 0 2.125.951 2.125 2.125v10a2.125 2.125 0 0 1-2.125 2.125h-11A2.125 2.125 0 0 1 2.375 15V5c0-1.174.951-2.125 2.125-2.125zm-5.25 9.5a.625.625 0 1 0 0 1.25h3.25a.625.625 0 1 0 0-1.25zm-3.332-5.59a.625.625 0 0 0-.836.93L8.065 9.5l-1.983 1.785a.625.625 0 0 0 .836.93l2.5-2.25a.626.626 0 0 0 0-.93z" />
	),
}

export const terminalFillIcon: LoadedIconFunction<"fill"> = createIcon(
	"terminalFill",
	iconDefinition,
	"fill",
)
