/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "1.25 3.3 13.51 9.39",
	svg: (
		<path d="M1.25 5.057c0-.966.784-1.75 1.75-1.75h10c.966 0 1.75.784 1.75 1.75v5.886a1.75 1.75 0 0 1-1.75 1.75H3a1.75 1.75 0 0 1-1.75-1.75zm2.59.343a.52.52 0 1 0 0 1.04.52.52 0 0 0 0-1.04m1.56.52a.52.52 0 1 0 1.04 0 .52.52 0 0 0-1.04 0M8 5.4a.52.52 0 1 0 0 1.04.52.52 0 0 0 0-1.04m1.56.52a.52.52 0 1 0 1.04 0 .52.52 0 0 0-1.04 0m2.6-.52a.52.52 0 1 0 0 1.04.52.52 0 0 0 0-1.04M3.32 8a.52.52 0 1 0 1.04 0 .52.52 0 0 0-1.04 0m2.6-.52a.52.52 0 1 0 0 1.04.52.52 0 0 0 0-1.04M7.48 8a.52.52 0 1 0 1.04 0 .52.52 0 0 0-1.04 0m2.6-.52a.52.52 0 1 0 0 1.04.52.52 0 0 0 0-1.04m1.56.52a.52.52 0 1 0 1.04 0 .52.52 0 0 0-1.04 0m-7.8 1.56a.52.52 0 1 0 0 1.04.52.52 0 0 0 0-1.04m1.493.509c0 .304.247.55.55.55h4.2a.55.55 0 0 0 0-1.1h-4.2a.55.55 0 0 0-.55.55m6.827-.509a.52.52 0 1 0 0 1.04.52.52 0 0 0 0-1.04" />
	),
}

export const keyboardFillSmallIcon: LoadedIconFunction<"fillSmall"> =
	createIcon("keyboardFillSmall", iconDefinition, "fillSmall")
