/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "4.12 2.37 14.01 15.25",
	directional: true,
	svg: (
		<>
			<path d="M6.25 2.375A2.125 2.125 0 0 0 4.125 4.5v11c0 1.174.951 2.125 2.125 2.125h7.5a2.125 2.125 0 0 0 2.125-2.125v-1.366a1.876 1.876 0 0 1-2.652-2.259H10a1.875 1.875 0 0 1 0-3.75h3.24a1.875 1.875 0 0 1 2.635-2.309V4.5a2.125 2.125 0 0 0-2.125-2.125z" />
			<path d="m15.442 7.033 2.5 2.5a.625.625 0 0 1 0 .884l-2.5 2.5a.625.625 0 1 1-.884-.884l1.408-1.408H10a.625.625 0 1 1 0-1.25h6.016l-1.458-1.458a.625.625 0 0 1 .884-.884" />
		</>
	),
}

export const arrowRightFromRectangleFillIcon: LoadedIconFunction<"fill"> =
	createIcon("arrowRightFromRectangleFill", iconDefinition, "fill")
