/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "2.62 2.52 14.76 14.95",
	svg: (
		<path d="M8.65 2.525c.345 0 .625.28.625.625v13.7a.625.625 0 1 1-1.25 0V3.15c0-.345.28-.625.625-.625M6.575 5.45a.625.625 0 1 0-1.25 0v9.1a.625.625 0 1 0 1.25 0zm-2.7 3.2a.625.625 0 0 0-1.25 0v2.7a.625.625 0 1 0 1.25 0zm10.8-2.7a.625.625 0 1 0-1.25 0v8.1a.625.625 0 0 0 1.25 0zm2.075 2.075c.345 0 .625.28.625.625v2.7a.625.625 0 1 1-1.25 0v-2.7c0-.345.28-.625.625-.625m-4.775-.775a.625.625 0 1 0-1.25 0v5.5a.625.625 0 1 0 1.25 0z" />
	),
}

export const waveformIcon: LoadedIconFunction<"default"> = createIcon(
	"waveform",
	iconDefinition,
	"default",
)
