/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "2.37 2.27 15.25 15.45",
	svg: (
		<path d="M8.65 2.275c.483 0 .875.392.875.875v13.7a.875.875 0 1 1-1.75 0V3.15c0-.483.392-.875.875-.875M6.825 5.45a.875.875 0 1 0-1.75 0v9.1a.875.875 0 0 0 1.75 0zm-2.7 3.2a.875.875 0 1 0-1.75 0v2.7a.875.875 0 0 0 1.75 0zm10.8-2.7a.875.875 0 1 0-1.75 0v8.1a.875.875 0 1 0 1.75 0zm1.825 1.825c.483 0 .875.392.875.875v2.7a.875.875 0 0 1-1.75 0v-2.7c0-.483.392-.875.875-.875m-4.525-.525a.875.875 0 0 0-1.75 0v5.5a.875.875 0 1 0 1.75 0z" />
	),
}

export const waveformFillIcon: LoadedIconFunction<"fill"> = createIcon(
	"waveformFill",
	iconDefinition,
	"fill",
)
