/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import type { IconGroup } from "../../iconUtils"
import { createIconGroup } from "../../iconUtils"

export const personCropCircleDashedIconGroup: IconGroup<
	"default" | "small" | "fill" | "fillSmall"
> = createIconGroup(
	"personCropCircleDashed",
	{
		default: {
			loader: () =>
				import(
					/* webpackChunkName: "icon-personCropCircleDashed" */
					"./default.icon"
				),
		},
		small: {
			loader: () =>
				import(
					/* webpackChunkName: "icon-personCropCircleDashed" */
					"./small.icon"
				),
		},
		fill: {
			loader: () =>
				import(
					/* webpackChunkName: "icon-personCropCircleDashed" */
					"./fill.icon"
				),
		},
		fillSmall: {
			loader: () =>
				import(
					/* webpackChunkName: "icon-personCropCircleDashed" */
					"./fillSmall.icon"
				),
		},
	},
	["person", "user", "profile", "account", "avatar", "member", "guest"],
)
