/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "4.12 2.37 11.75 15.25",
	svg: (
		<>
			<path d="m10.312 12.682.208-.99h-1.2l-.208.99z" />
			<path d="M9.95 2.375h-3.7A2.125 2.125 0 0 0 4.125 4.5v11c0 1.174.951 2.125 2.125 2.125h7.5a2.125 2.125 0 0 0 2.125-2.125V8.3H12a2.05 2.05 0 0 1-2.05-2.05zm-3.052 8.818a.5.5 0 0 1 .5-.5h1.11l.234-1.108a.5.5 0 0 1 .978.205l-.19.903h1.2l.233-1.108a.5.5 0 0 1 .98.205l-.19.903h.856a.5.5 0 0 1 0 1h-1.067l-.208.99h.924a.5.5 0 1 1 0 1h-1.134l-.234 1.107a.5.5 0 0 1-.978-.205l.19-.903h-1.2l-.233 1.108a.5.5 0 0 1-.979-.205l.19-.903h-.833a.5.5 0 0 1 0-1H8.09l.208-.99h-.9a.5.5 0 0 1-.5-.5" />
			<path d="M15.665 7.2a2.1 2.1 0 0 0-.412-.581L11.63 2.997c-.17-.17-.367-.31-.581-.412V6.25c0 .525.425.95.95.95z" />
		</>
	),
}

export const docHashtagFillIcon: LoadedIconFunction<"fill"> = createIcon(
	"docHashtagFill",
	iconDefinition,
	"fill",
)
