/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "4.31 2.82 7.37 10.36",
	svg: (
		<path d="M10.305 3.16a.75.75 0 0 1 1.256.82L9.08 7.774h1.853a.626.626 0 0 1 0 1.25H8.75v.75h2.184a.626.626 0 0 1 0 1.25H8.75v1.406a.75.75 0 0 1-1.5 0v-1.406H5.068a.625.625 0 0 1 0-1.25H7.25v-.75H5.068a.625.625 0 0 1 0-1.25h1.85L4.438 3.98a.75.75 0 0 1 1.256-.82L8 6.69z" />
	),
}

export const yenSignFillSmallIcon: LoadedIconFunction<"fillSmall"> = createIcon(
	"yenSignFillSmall",
	iconDefinition,
	"fillSmall",
)
