/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "4.43 2.93 7.13 10.13",
	svg: (
		<path d="M10.41 3.227a.625.625 0 0 1 1.047.684L8.933 7.775h2a.625.625 0 0 1 0 1.25H8.625v.75h2.308a.625.625 0 0 1 0 1.25H8.625v1.406a.625.625 0 0 1-1.25 0v-1.406H5.067a.625.625 0 0 1 0-1.25h2.308v-.75H5.067a.625.625 0 0 1 0-1.25h2.001L4.545 3.911a.625.625 0 1 1 1.046-.684L8 6.917z" />
	),
}

export const yenSignSmallIcon: LoadedIconFunction<"small"> = createIcon(
	"yenSignSmall",
	iconDefinition,
	"small",
)
