/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "1.34 2.01 16.88 16.88",
	svg: (
		<>
			<path d="M5.95 10.45a.675.675 0 1 1-.001 1.35.675.675 0 0 1 .001-1.35m0-2.25a.675.675 0 1 1-.001 1.35.675.675 0 0 1 .001-1.35" />
			<path d="M1.526 2.195a.627.627 0 0 1 .885 0l.782.782q.035.055.083.103l14.842 14.842a.626.626 0 0 1-.967.783l-1.33-1.33H2.575a.626.626 0 0 1-.625-.625V5.724c0-.617.233-1.179.613-1.607L1.526 3.08a.627.627 0 0 1 0-.885M3.45 5.003c-.155.199-.249.45-.249.721v10.4h1.976V13.6a.55.55 0 0 1 .55-.55h3.599c.303.001.55.247.55.55v2.526h1.975v-2.72l-2.102-2.103a.673.673 0 1 1-.825-.826zm2.826 11.122h2.5v-1.976h-2.5zm6.825 0h1.471l-1.47-1.47zM10.675 3.3A2.427 2.427 0 0 1 13.1 5.724v3.2h2.526a2.426 2.426 0 0 1 2.425 2.425v4.736l-1.25-1.25v-3.486c0-.648-.527-1.174-1.175-1.174H13.1v.96l-1.25-1.25v-4.16c0-.649-.527-1.175-1.175-1.175h-4.16L5.265 3.3z" />
			<path d="M14.838 11.35a.676.676 0 0 1 0 1.35.676.676 0 0 1 0-1.35M9.1 5.95a.675.675 0 0 1 .148 1.332l-.806-.806A.675.675 0 0 1 9.1 5.95" />
		</>
	),
}

export const teamspaceSlashIcon: LoadedIconFunction<"default"> = createIcon(
	"teamspaceSlash",
	iconDefinition,
	"default",
)
