/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "0 0 20 20",
	svg: (
		<>
			<g clipPath="url(#clip0_14275_138)">
				<path d="M15.241 7.125H3.015a.625.625 0 0 0-.625.625v4.5c0 .345.28.624.625.625h13.97c.345 0 .624-.28.624-.625V9.622l1.25-1.25v3.878c0 1.035-.84 1.875-1.875 1.875H3.014A1.875 1.875 0 0 1 1.14 12.25v-4.5c0-1.036.84-1.875 1.875-1.875h13.48z" />
				<path d="M5.063 9.2a.875.875 0 1 1-.001 1.75.875.875 0 0 1 0-1.75m3.251 0a.875.875 0 1 1-.001 1.75.875.875 0 0 1 0-1.75m3.251 0a.875.875 0 1 1-.001 1.75.875.875 0 0 1 0-1.75m7.391-4.224a.617.617 0 0 1 .868 0 .617.617 0 0 1 0 .868v.011l-4.52 4.52a.7.7 0 0 1-.31.187l-.735.228c-.145.05-.29-.094-.248-.25l.227-.733a.9.9 0 0 1 .187-.31z" />
			</g>
			<defs>
				<clipPath id="clip0_14275_138">
					<path d="M0 0h20v20H0z" />
				</clipPath>
			</defs>
		</>
	),
}

export const passwordFieldIcon: LoadedIconFunction<"default"> = createIcon(
	"passwordField",
	iconDefinition,
	"default",
)
