/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "2.37 4.12 15.25 11.75",
	svg: (
		<>
			<path d="M11.889 7.054a.626.626 0 0 1 1.072.642l-3 5a.625.625 0 0 1-1.01.086l-2-2.334a.625.625 0 0 1 .948-.813l1.436 1.675z" />
			<path d="M15.5 4.125c1.174 0 2.125.951 2.125 2.125v7.5a2.125 2.125 0 0 1-2.125 2.125h-11a2.125 2.125 0 0 1-2.125-2.125v-7.5c0-1.174.951-2.125 2.125-2.125zm-11 1.25a.875.875 0 0 0-.875.875v7.5c0 .483.392.875.875.875h11a.875.875 0 0 0 .875-.875v-7.5a.875.875 0 0 0-.875-.875z" />
		</>
	),
}

export const rectangleCheckIcon: LoadedIconFunction<"default"> = createIcon(
	"rectangleCheck",
	iconDefinition,
	"default",
)
