/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "1.77 3.17 12.46 9.66",
	svg: (
		<>
			<path d="M9.313 5.554a.626.626 0 0 1 1.073.642l-2.4 4a.625.625 0 0 1-1.01.086L5.375 8.415a.625.625 0 0 1 .95-.813L7.36 8.81z" />
			<path d="M12.4 3.175c1.008 0 1.826.817 1.826 1.825v6a1.826 1.826 0 0 1-1.826 1.825H3.6A1.826 1.826 0 0 1 1.776 11V5c0-1.008.817-1.825 1.825-1.825zm-8.8 1.25A.576.576 0 0 0 3.026 5v6c0 .318.258.575.576.575h8.8a.576.576 0 0 0 .575-.575V5a.576.576 0 0 0-.576-.575z" />
		</>
	),
}

export const rectangleCheckSmallIcon: LoadedIconFunction<"small"> = createIcon(
	"rectangleCheckSmall",
	iconDefinition,
	"small",
)
