/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "0.78 4.52 18.08 10.95",
	svg: (
		<path d="M7.383 5.4a.875.875 0 0 0-1.75 0v9.2a.875.875 0 1 0 1.75 0v-3.925h5.05V14.6a.875.875 0 1 0 1.75 0V5.4a.875.875 0 1 0-1.75 0v3.525h-5.05zm11.384 3.129c.072.132.1.277.089.417l.002.054v5.6a.75.75 0 0 1-1.5 0v-4.448l-1.09.594a.75.75 0 0 1-.719-1.316l2.2-1.2a.75.75 0 0 1 1.018.299M.788 11.14c0 .59.643.953 1.148.65l1.9-1.14a.758.758 0 0 0 0-1.3l-1.9-1.14a.758.758 0 0 0-1.148.65z" />
	),
}

export const textH1ToggleFillIcon: LoadedIconFunction<"fill"> = createIcon(
	"textH1ToggleFill",
	iconDefinition,
	"fill",
)
