/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "1.6 2.52 16.8 14.96",
	svg: (
		<path d="M8.256 3.424a2.86 2.86 0 0 1 4.107-.062l2.985 2.985a2.86 2.86 0 0 1 .06 3.984L9.86 16.226h2.84a.625.625 0 1 1 0 1.25H7.625q-.03 0-.058-.002a2.85 2.85 0 0 1-2.143-.836L2.44 13.653a2.86 2.86 0 0 1-.06-3.984zm3.223.822a1.61 1.61 0 0 0-2.313.035L4.794 8.926l5.384 5.139 4.32-4.59a1.61 1.61 0 0 0-.034-2.244zm-2.055 10.62L4.04 9.727l-.751.799a1.61 1.61 0 0 0 .034 2.243l2.985 2.985a1.61 1.61 0 0 0 2.312-.035zm5.813 1.36a.625.625 0 1 0 0 1.25h2.537a.625.625 0 1 0 0-1.25z" />
	),
}

export const eraserLineDashedIcon: LoadedIconFunction<"default"> = createIcon(
	"eraserLineDashed",
	iconDefinition,
	"default",
)
