/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "3.37 1.37 13.26 16.26",
	svg: (
		<path d="M10.809 1.478a.625.625 0 0 0-.864.867l.08.099 1.942 1.932H10A6.625 6.625 0 1 0 16.625 11a.625.625 0 1 0-1.25 0A5.375 5.375 0 1 1 10 5.626h1.963L10.038 7.56l-.08.098a.626.626 0 0 0 .966.783l2.993-3.007.077-.096a.625.625 0 0 0-.08-.788l-3.007-2.993z" />
	),
}

export const arrowCircleSpinClockwiseIcon: LoadedIconFunction<"default"> =
	createIcon("arrowCircleSpinClockwise", iconDefinition, "default")
