/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "3.17 3.72 12.66 12.56",
	directional: true,
	svg: (
		<>
			<path d="M3.431 10.619a.875.875 0 0 1 0-1.238l5.4-5.4A.875.875 0 0 1 10.07 5.22L5.287 10l4.782 4.781A.875.875 0 1 1 8.83 16.02z" />
			<path d="m14.331 3.981-5.4 5.4a.875.875 0 0 0 0 1.238l5.4 5.4a.875.875 0 0 0 1.238-1.238l-4.782-4.78 4.782-4.782A.875.875 0 1 0 14.33 3.98" />
		</>
	),
}

export const arrowChevronDoubleBackwardFillIcon: LoadedIconFunction<"fill"> =
	createIcon("arrowChevronDoubleBackwardFill", iconDefinition, "fill")
