/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "0.73 3.36 18.53 13.28",
	svg: (
		<>
			<path d="M13.004 6.123a3.588 3.588 0 0 1 6.175.032.624.624 0 1 1-1.079.63 2.338 2.338 0 0 0-4.024-.02L9.264 14.8l3.682.596a.626.626 0 0 1-.2 1.235l-4.591-.744a.625.625 0 0 1-.436-.939zm-8.269 6.688a.625.625 0 1 1 0 1.25H1.36a.625.625 0 0 1 0-1.25zM6.079 9.53a.625.625 0 0 1 0 1.25H1.36a.625.625 0 0 1 0-1.25z" />
			<path d="M14.146 8.918a1.061 1.061 0 1 1 2.095.34 1.061 1.061 0 0 1-2.095-.34m-5.59-.906a1.061 1.061 0 1 1 2.095.34 1.061 1.061 0 0 1-2.095-.34M5.235 6.249a.625.625 0 1 1 0 1.25H1.36a.625.625 0 0 1 0-1.25zm2.188-1.974a3.59 3.59 0 0 1 5.104.325.625.625 0 0 1-.944.82 2.34 2.34 0 0 0-3.326-.213.625.625 0 0 1-.834-.932" />
		</>
	),
}

export const aiDescriptionIcon: LoadedIconFunction<"default"> = createIcon(
	"aiDescription",
	iconDefinition,
	"default",
)
