/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "2.25 2.19 11.5 11.56",
	svg: (
		<path d="M3 2.192a.75.75 0 0 1 .75.75v5.171L5.376 6.69l.118-.084a.75.75 0 0 1 .906.119l1.982 1.981 3.677-3.677a.75.75 0 0 1 1.06 1.06l-4.207 4.208a.75.75 0 0 1-1.06 0L5.836 8.28 3.75 10.106v1.644a.5.5 0 0 0 .5.5H13l.077.003a.751.751 0 0 1 0 1.493L13 13.75H4.25a2 2 0 0 1-2-2V2.942a.75.75 0 0 1 .75-.75" />
	),
}

export const chartLineFillSmallIcon: LoadedIconFunction<"fillSmall"> =
	createIcon("chartLineFillSmall", iconDefinition, "fillSmall")
