/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "1.68 2.37 17.29 15.26",
	svg: (
		<path d="M5.326 3.617C5.946 2.844 6.863 2.375 8 2.375s2.055.47 2.675 1.242c.608.757.9 1.765.9 2.824s-.292 2.066-.9 2.824c-.62.772-1.538 1.241-2.675 1.241s-2.054-.469-2.674-1.241c-.608-.758-.9-1.766-.9-2.824 0-1.059.292-2.067.9-2.824M1.88 14.935C2.899 12.945 5.3 11.63 8 11.63s5.101 1.316 6.12 3.306c.361.706.199 1.421-.23 1.923-.412.48-1.06.767-1.74.767h-8.3c-.68 0-1.328-.287-1.74-.767-.429-.502-.591-1.217-.23-1.923m16.996-7.958a.625.625 0 0 0-1.072-.643L15.25 10.59l-1.435-1.675a.625.625 0 1 0-.95.814l2 2.333a.625.625 0 0 0 1.011-.085z" />
	),
}

export const personCheckmarkFillIcon: LoadedIconFunction<"fill"> = createIcon(
	"personCheckmarkFill",
	iconDefinition,
	"fill",
)
