/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "2.12 0.12 15.76 17.75",
	directional: true,
	svg: (
		<>
			<path d="M13.277 2.38a.875.875 0 0 1 .003 1.237l-2.02 2.03a.875.875 0 0 1-1.24-1.234l.535-.538H10a6.125 6.125 0 1 0 4.386 1.85.875.875 0 0 1 1.253-1.222A7.875 7.875 0 1 1 10 2.125h.541l-.527-.525A.875.875 0 0 1 11.247.36z" />
			<path d="M10.875 7.5a.875.875 0 0 0-1.75 0v1.625H7.5a.875.875 0 1 0 0 1.75h1.625V12.5a.875.875 0 0 0 1.75 0v-1.625H12.5a.875.875 0 0 0 0-1.75h-1.625z" />
		</>
	),
}

export const goForwardPlusFillIcon: LoadedIconFunction<"fill"> = createIcon(
	"goForwardPlusFill",
	iconDefinition,
	"fill",
)
