/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "2.37 2.57 11.25 12.45",
	svg: (
		<path d="M3.8 2.575c-.787 0-1.425.638-1.425 1.425v.8c0 .787.638 1.425 1.425 1.425h3.575v.95H3.8c-.787 0-1.425.638-1.425 1.425v.8c0 .787.638 1.425 1.425 1.425h3.575v2.046l-.913-.913a.625.625 0 1 0-.884.884l2 2c.244.244.64.244.884 0l2-2a.625.625 0 1 0-.884-.884l-.953.953v-2.086H12.2c.787 0 1.425-.638 1.425-1.425v-.8c0-.787-.638-1.425-1.425-1.425H8.625v-.95H12.2c.787 0 1.425-.638 1.425-1.425V4c0-.787-.638-1.425-1.425-1.425zM3.625 4c0-.097.078-.175.175-.175h8.4c.097 0 .175.078.175.175v.8a.175.175 0 0 1-.175.175H3.8a.175.175 0 0 1-.175-.175zm0 4.6c0-.097.078-.175.175-.175h8.4c.097 0 .175.078.175.175v.8a.175.175 0 0 1-.175.175H3.8a.175.175 0 0 1-.175-.175z" />
	),
}

export const flowchartSmallIcon: LoadedIconFunction<"small"> = createIcon(
	"flowchartSmall",
	iconDefinition,
	"small",
)
