/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "1.45 3.05 12.3 10.24",
	directional: true,
	svg: (
		<path d="M12.25 3.8a.75.75 0 0 1 1.5 0v4a1.95 1.95 0 0 1-1.95 1.95H4.01l2.24 2.24a.75.75 0 1 1-1.06 1.06L1.67 9.53a.75.75 0 0 1 0-1.06l3.52-3.52a.75.75 0 0 1 1.06 1.06L4.01 8.25h7.79a.45.45 0 0 0 .45-.45z" />
	),
}

export const arrowTurnDownLeftFillSmallIcon: LoadedIconFunction<"fillSmall"> =
	createIcon("arrowTurnDownLeftFillSmall", iconDefinition, "fillSmall")
