/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import type { IconGroup } from "../../iconUtils"
import { createIconGroup } from "../../iconUtils"

export const arrowTurnDownLeftIconGroup: IconGroup<
	"default" | "small" | "fill" | "fillSmall"
> = createIconGroup(
	"arrowTurnDownLeft",
	{
		default: {
			loader: () =>
				import(
					/* webpackChunkName: "icon-arrowTurnDownLeft" */
					"./default.icon"
				),
		},
		small: {
			loader: () =>
				import(
					/* webpackChunkName: "icon-arrowTurnDownLeft" */
					"./small.icon"
				),
		},
		fill: {
			loader: () =>
				import(
					/* webpackChunkName: "icon-arrowTurnDownLeft" */
					"./fill.icon"
				),
		},
		fillSmall: {
			loader: () =>
				import(
					/* webpackChunkName: "icon-arrowTurnDownLeft" */
					"./fillSmall.icon"
				),
		},
	},
	[
		"turn",
		"90degree",
		"downleft",
		"direction",
		"rotate",
		"return",
		"carriage",
		"enter",
	],
)
