/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "0.76 2.69 14.48 10.56",
	directional: true,
	svg: (
		<path d="M2.42 2.695a1.66 1.66 0 0 0-1.66 1.66v7.29a1.661 1.661 0 0 0 3.32 0v-7.29a1.66 1.66 0 0 0-1.66-1.66m0 1.25a.41.41 0 0 1 .41.41v7.29a.411.411 0 0 1-.82 0v-7.29a.41.41 0 0 1 .41-.41m6.977.093a.625.625 0 0 0-.883 0l-3.52 3.52a.625.625 0 0 0 0 .884l3.52 3.52a.625.625 0 0 0 .883-.884L6.943 8.625h7.672a.625.625 0 0 0 0-1.25h-7.67l2.452-2.453a.626.626 0 0 0 0-.884" />
	),
}

export const arrowRectangleLeftSmallIcon: LoadedIconFunction<"small"> =
	createIcon("arrowRectangleLeftSmall", iconDefinition, "small")
