/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "3.12 1.12 13.76 16.76",
	svg: (
		<path d="M8.983 1.32a.875.875 0 0 1 1.228 1.234l-.06.066L8.64 4.125H10l.354.01A6.875 6.875 0 1 1 3.125 11a.875.875 0 1 1 1.75 0 5.125 5.125 0 1 0 5.389-5.118L10 5.875H8.639l1.5 1.508.06.067a.875.875 0 0 1-1.3 1.167L5.905 5.61l-.057-.064a.876.876 0 0 1 .06-1.174L8.917 1.38z" />
	),
}

export const arrowCircleSpinCounterClockwiseFillIcon: LoadedIconFunction<"fill"> =
	createIcon("arrowCircleSpinCounterClockwiseFill", iconDefinition, "fill")
