/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "4.12 2.37 15.02 16.77",
	svg: (
		<>
			<path d="M6.25 2.375A2.125 2.125 0 0 0 4.125 4.5v11c0 1.174.951 2.125 2.125 2.125h4.923a4.8 4.8 0 0 1-.789-1.25H6.25a.875.875 0 0 1-.875-.875v-11c0-.483.392-.875.875-.875h7.5c.483 0 .875.392.875.875v5.252a5 5 0 0 1 1.25.132V4.5a2.125 2.125 0 0 0-2.125-2.125z" />
			<path d="M7.25 5.2a.55.55 0 0 0 0 1.1h5.5a.55.55 0 0 0 0-1.1zM6.7 8.25a.55.55 0 0 1 .55-.55h5.5a.55.55 0 0 1 0 1.1h-5.5a.55.55 0 0 1-.55-.55m11 8.357a3.625 3.625 0 1 0-.893.878l1.223 1.427a.625.625 0 1 0 .94-.823zM12.376 14.5a2.375 2.375 0 1 1 4.75 0 2.375 2.375 0 0 1-4.75 0" />
		</>
	),
}

export const docTextMagnifyingGlassIcon: LoadedIconFunction<"default"> =
	createIcon("docTextMagnifyingGlass", iconDefinition, "default")
