/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "1.67 2.57 12.66 10.86",
	directional: true,
	svg: (
		<path d="M13.58 2.57a.75.75 0 0 1 .75.75v9.36a.75.75 0 0 1-1.5 0V3.32a.75.75 0 0 1 .75-.75M7.55 3.95a.75.75 0 0 1 1.06 0l3.52 3.52a.75.75 0 0 1 0 1.06l-3.52 3.52a.75.75 0 0 1-1.06-1.06l2.24-2.24H2.42a.75.75 0 0 1 0-1.5h7.37L7.55 5.01a.75.75 0 0 1 0-1.06" />
	),
}

export const arrowLineRightFillSmallIcon: LoadedIconFunction<"fillSmall"> =
	createIcon("arrowLineRightFillSmall", iconDefinition, "fillSmall")
