/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "3.37 2.12 9.25 11.75",
	svg: (
		<>
			<path d="M5.75 4.175a.575.575 0 1 0 0 1.15h4.5a.575.575 0 1 0 0-1.15zm0 2a.575.575 0 1 0 0 1.15h4.5a.575.575 0 1 0 0-1.15zm0 2a.575.575 0 1 0 0 1.15H8a.575.575 0 0 0 0-1.15z" />
			<path d="M5.25 2.125c-1.036 0-1.875.84-1.875 1.875v8c0 1.036.84 1.875 1.875 1.875h5.5c1.036 0 1.875-.84 1.875-1.875V4c0-1.036-.84-1.875-1.875-1.875zM4.625 4c0-.345.28-.625.625-.625h5.5c.345 0 .625.28.625.625v8c0 .345-.28.625-.625.625h-5.5A.625.625 0 0 1 4.625 12z" />
		</>
	),
}

export const docPlainTextSmallIcon: LoadedIconFunction<"small"> = createIcon(
	"docPlainTextSmall",
	iconDefinition,
	"small",
)
