/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "4.65 2.91 5.84 10.18",
	directional: true,
	svg: (
		<path d="M4.87 7.47a.75.75 0 0 0 0 1.06l4.32 4.32a.75.75 0 1 0 1.06-1.06L6.46 8l3.79-3.79a.75.75 0 1 0-1.06-1.06z" />
	),
}

export const arrowChevronSingleLeftFillSmallIcon: LoadedIconFunction<"fillSmall"> =
	createIcon("arrowChevronSingleLeftFillSmall", iconDefinition, "fillSmall")
