/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "2.2 3.45 11.61 9.11",
	svg: (
		<path d="M6.4 3.45h-1v9.1h1zm1.1 9.1h1v-9.1h-1zm3.1 0h-1v-9.1h1zm1.1 0h.3a1.8 1.8 0 0 0 1.8-1.8v-5.5a1.8 1.8 0 0 0-1.8-1.8h-.3zM4 3.45h.3v9.1H4a1.8 1.8 0 0 1-1.8-1.8v-5.5A1.8 1.8 0 0 1 4 3.45" />
	),
}

export const rectangleSplit5FillSmallIcon: LoadedIconFunction<"fillSmall"> =
	createIcon("rectangleSplit5FillSmall", iconDefinition, "fillSmall")
