/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "1.37 2.57 16.08 13.68",
	svg: (
		<>
			<path d="M3.5 2.575A2.125 2.125 0 0 0 1.375 4.7v6.5c0 1.174.951 2.125 2.125 2.125h4.45V11.05A2.05 2.05 0 0 1 10 9h5.625V4.7A2.125 2.125 0 0 0 13.5 2.575zM7.328 5.15a.55.55 0 0 1 .55.55v2.828a.55.55 0 0 1-.55.55H4.5a.55.55 0 0 1 0-1.1H6L4.134 6.111a.55.55 0 0 1 .778-.778L6.778 7.2V5.7a.55.55 0 0 1 .55-.55" />
			<path d="M10 10.1a.95.95 0 0 0-.95.95v4.25c0 .525.425.95.95.95h6.5a.95.95 0 0 0 .95-.95v-4.25a.95.95 0 0 0-.95-.95z" />
		</>
	),
}

export const pipEnterFillIcon: LoadedIconFunction<"fill"> = createIcon(
	"pipEnterFill",
	iconDefinition,
	"fill",
)
