/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "3.07 2.17 13.85 15.65",
	svg: (
		<>
			<path d="M10 5.607c1.173 0 2.124.951 2.124 2.125v1.093c.525.194.9.697.9 1.29v2.291c0 .76-.615 1.375-1.375 1.375h-3.3a1.374 1.374 0 0 1-1.373-1.375v-2.292c0-.592.374-1.095.899-1.289V7.732c0-1.174.951-2.125 2.125-2.125m0 4.846a.756.756 0 1 0 0 1.512.756.756 0 0 0 0-1.512m0-3.622a.9.9 0 0 0-.9.9V8.74h1.8V7.732a.9.9 0 0 0-.9-.9" />
			<path d="M9.788 2.212a.63.63 0 0 1 .491.03l1.89.944a7.5 7.5 0 0 0 3.344.789h.787c.345 0 .625.28.625.625v6.933a5.13 5.13 0 0 1-3.106 4.71l-3.573 1.532a.63.63 0 0 1-.492 0l-3.572-1.532a5.13 5.13 0 0 1-3.107-4.71V4.6c0-.345.28-.625.625-.625h.788c1.16 0 2.305-.27 3.343-.79l1.89-.944zM8.39 4.304a8.7 8.7 0 0 1-3.902.92h-.163v6.309c0 1.55.924 2.95 2.349 3.561L10 16.519l3.326-1.425a3.88 3.88 0 0 0 2.349-3.561V5.225h-.162a8.7 8.7 0 0 1-3.903-.921L10 3.498z" />
		</>
	),
}

export const shieldLockIcon: LoadedIconFunction<"default"> = createIcon(
	"shieldLock",
	iconDefinition,
	"default",
)
