/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "2.85 2.2 10.29 11.61",
	svg: (
		<>
			<path d="M8 8.362a.605.605 0 1 1 0 1.21.605.605 0 0 1 0-1.21m0-2.896a.72.72 0 0 1 .72.72v.806H7.28v-.806a.72.72 0 0 1 .72-.72" />
			<path d="M7.874 2.215a.55.55 0 0 1 .372.043l.962.481a7.3 7.3 0 0 0 3.277.774h.109a.55.55 0 0 1 .55.55v4.333c0 1.97-1.174 3.75-2.985 4.527l-1.942.833a.55.55 0 0 1-.434 0l-1.942-.833a4.93 4.93 0 0 1-2.984-4.527V4.062a.55.55 0 0 1 .55-.55h.109c1.137 0 2.26-.264 3.276-.773l.962-.481zM8 4.485a1.7 1.7 0 0 0-1.7 1.7v.876a1.1 1.1 0 0 0-.72 1.03v1.834a1.1 1.1 0 0 0 1.1 1.1h2.64a1.1 1.1 0 0 0 1.1-1.1V8.092a1.1 1.1 0 0 0-.72-1.03v-.876A1.7 1.7 0 0 0 8 4.484" />
		</>
	),
}

export const shieldLockFillSmallIcon: LoadedIconFunction<"fillSmall"> =
	createIcon("shieldLockFillSmall", iconDefinition, "fillSmall")
