/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "3.07 2.17 13.85 15.65",
	svg: (
		<>
			<path d="M10 10.453a.756.756 0 1 1 0 1.513.756.756 0 0 1 0-1.513m0-3.622a.9.9 0 0 1 .9.9v1.01H9.1V7.73a.9.9 0 0 1 .9-.9" />
			<path d="M9.788 2.212a.63.63 0 0 1 .491.03l1.89.944a7.5 7.5 0 0 0 3.344.789h.787c.345 0 .625.28.625.625v6.933a5.13 5.13 0 0 1-3.106 4.71l-3.573 1.532a.63.63 0 0 1-.492 0l-3.572-1.532a5.13 5.13 0 0 1-3.107-4.71V4.6c0-.345.28-.625.625-.625h.788c1.16 0 2.305-.27 3.343-.79l1.89-.944zM10 5.607a2.125 2.125 0 0 0-2.125 2.125v1.093c-.525.194-.9.698-.9 1.29v2.291c0 .76.616 1.375 1.375 1.375h3.3c.759 0 1.374-.615 1.374-1.375v-2.29c0-.593-.375-1.097-.9-1.29V7.731c0-1.174-.95-2.125-2.124-2.125" />
		</>
	),
}

export const shieldLockFillIcon: LoadedIconFunction<"fill"> = createIcon(
	"shieldLockFill",
	iconDefinition,
	"fill",
)
