/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "3.12 3.12 13.75 13.75",
	svg: (
		<path d="M5.25 3.125A2.125 2.125 0 0 0 3.125 5.25v9.5c0 1.174.951 2.125 2.125 2.125h9.5a2.125 2.125 0 0 0 2.125-2.125v-9.5a2.125 2.125 0 0 0-2.125-2.125zM9.875 6.25c.345 0 .625.28.625.625v3.5a.625.625 0 1 1-1.25 0v-3.5c0-.345.28-.625.625-.625m0 7.375a.75.75 0 1 1 0-1.5.75.75 0 0 1 0 1.5" />
	),
}

export const exclamationMarkSquareFillIcon: LoadedIconFunction<"fill"> =
	createIcon("exclamationMarkSquareFill", iconDefinition, "fill")
