/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "2.45 2.45 11.11 11.11",
	svg: (
		<path d="M4.25 2.45a1.8 1.8 0 0 0-1.8 1.8v7.5a1.8 1.8 0 0 0 1.8 1.8h7.5a1.8 1.8 0 0 0 1.8-1.8v-7.5a1.8 1.8 0 0 0-1.8-1.8zm3.65 2.5a.55.55 0 0 1 .55.55V8a.55.55 0 0 1-1.1 0V5.5a.55.55 0 0 1 .55-.55m0 6a.65.65 0 1 1 0-1.3.65.65 0 0 1 0 1.3" />
	),
}

export const exclamationMarkSquareFillSmallIcon: LoadedIconFunction<"fillSmall"> =
	createIcon("exclamationMarkSquareFillSmall", iconDefinition, "fillSmall")
