/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "4.75 3.52 11.53 12.95",
	svg: (
		<path d="m7.006 16.267 8.523-4.971a1.5 1.5 0 0 0 0-2.592L7.006 3.733A1.5 1.5 0 0 0 4.75 5.028v9.944a1.5 1.5 0 0 0 2.256 1.295" />
	),
}

export const mediaPlayFillIcon: LoadedIconFunction<"fill"> = createIcon(
	"mediaPlayFill",
	iconDefinition,
	"fill",
)
