/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "3.17 2.19 10.47 11.62",
	svg: (
		<path d="M5.92 2.446c-1.217-.71-2.745.168-2.745 1.577v7.954c0 1.409 1.528 2.287 2.745 1.577l6.818-3.978c1.207-.704 1.207-2.448 0-3.152zM4.425 4.023c0-.444.481-.72.865-.497l6.818 3.977c.38.222.38.772 0 .994L5.29 12.474a.575.575 0 0 1-.865-.497z" />
	),
}

export const mediaPlaySmallIcon: LoadedIconFunction<"small"> = createIcon(
	"mediaPlaySmall",
	iconDefinition,
	"small",
)
