/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "1.57 1.57 16.86 16.86",
	svg: (
		<path d="M10.405 1.724a.625.625 0 0 0-.81 0L7.36 3.628l-2.926.234a.625.625 0 0 0-.573.573L3.628 7.36 1.724 9.595a.624.624 0 0 0 0 .81l1.904 2.234.233 2.926a.625.625 0 0 0 .574.574l2.926.233 2.234 1.904a.624.624 0 0 0 .81 0l2.234-1.904 2.926-.233a.625.625 0 0 0 .573-.574l.234-2.926 1.904-2.234a.624.624 0 0 0 0-.81L16.372 7.36l-.234-2.926a.625.625 0 0 0-.573-.573l-2.926-.234zm2.412 5.46a.625.625 0 0 1 0 .883L10.884 10l1.933 1.933a.625.625 0 0 1-.884.884L10 10.884l-1.933 1.933a.625.625 0 0 1-.884-.884L9.116 10 7.183 8.067a.625.625 0 0 1 .884-.884L10 9.116l1.933-1.933a.625.625 0 0 1 .884 0" />
	),
}

export const xMarkSealFillIcon: LoadedIconFunction<"fill"> = createIcon(
	"xMarkSealFill",
	iconDefinition,
	"fill",
)
