/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "1.2 1.2 13.59 13.59",
	svg: (
		<path d="M8.357 1.341a.55.55 0 0 0-.714 0L5.868 2.854l-2.324.185a.55.55 0 0 0-.505.505l-.185 2.324L1.34 7.643a.55.55 0 0 0 0 .714l1.513 1.775.185 2.324a.55.55 0 0 0 .505.505l2.324.185 1.775 1.513a.55.55 0 0 0 .714 0l1.775-1.513 2.324-.185a.55.55 0 0 0 .505-.505l.185-2.324 1.513-1.775a.55.55 0 0 0 0-.714l-1.513-1.775-.185-2.324a.55.55 0 0 0-.505-.505l-2.324-.185zm1.932 4.37a.55.55 0 0 1 0 .778L8.778 8l1.511 1.511a.55.55 0 0 1-.778.778l-1.51-1.511-1.512 1.51a.55.55 0 1 1-.778-.777L7.222 8l-1.51-1.511a.55.55 0 1 1 .777-.778L8 7.222l1.511-1.51a.55.55 0 0 1 .778 0" />
	),
}

export const xMarkSealFillSmallIcon: LoadedIconFunction<"fillSmall"> =
	createIcon("xMarkSealFillSmall", iconDefinition, "fillSmall")
