/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "2.89 1.85 12.7 13.72",
	svg: (
		<>
			<path d="M5.821 2.862c.506-.63 1.255-1.012 2.18-1.012.924 0 1.672.382 2.178 1.012.495.617.73 1.435.73 2.29 0 .856-.235 1.674-.73 2.291-.506.63-1.254 1.012-2.179 1.012s-1.673-.382-2.179-1.012c-.495-.617-.73-1.435-.73-2.29 0-.856.235-1.674.73-2.291M3.06 11.925C3.885 10.313 5.825 9.253 8 9.253c.723 0 1.42.117 2.058.333A3.93 3.93 0 0 0 8.657 12.6c0 .55.113 1.074.316 1.55H4.68c-.557 0-1.09-.235-1.43-.631a1.405 1.405 0 0 1-.19-1.594" />
			<path d="M9.664 13.22a3 3 0 1 1 5.871-1.24 3 3 0 0 1-5.87 1.24m5.102-.62a.5.5 0 0 0-.5-.5H13.1v-1.166a.5.5 0 0 0-1 0V12.1h-1.167a.5.5 0 1 0 0 1H12.1v1.167a.5.5 0 1 0 1 0V13.1h1.166a.5.5 0 0 0 .5-.5" />
		</>
	),
}

export const inviteMemberFillSmallIcon: LoadedIconFunction<"fillSmall"> =
	createIcon("inviteMemberFillSmall", iconDefinition, "fillSmall")
