/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "4.12 2.37 14.88 15.25",
	svg: (
		<>
			<path d="M13.75 2.375c1.174 0 2.125.951 2.125 2.125v1.324l-1.25 1.248V4.5a.875.875 0 0 0-.875-.875h-7.5a.875.875 0 0 0-.875.875v11c0 .483.392.875.875.875h7.5a.875.875 0 0 0 .875-.875v-2.894l1.25-1.25V15.5a2.125 2.125 0 0 1-2.125 2.125h-7.5A2.125 2.125 0 0 1 4.125 15.5v-11c0-1.174.951-2.125 2.125-2.125z" />
			<path d="m17.62 7.847-6.136 6.13a.8.8 0 0 1-.354.213l-.838.26c-.165.06-.331-.106-.284-.283l.26-.839a1 1 0 0 1 .212-.353l6.14-6.127zm-7.295.202a.55.55 0 0 1 0 1.078l-.11.01H7.5a.55.55 0 0 1 0-1.099h2.715zm7.479-2.383a.706.706 0 0 1 .992 0 .706.706 0 0 1 0 .992v.012l-.53.53-.998-.999zM12.5 5.538a.55.55 0 1 1 0 1.1h-5a.55.55 0 0 1 0-1.1z" />
		</>
	),
}

export const formIcon: LoadedIconFunction<"default"> = createIcon(
	"form",
	iconDefinition,
	"default",
)
