/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "3.17 1.77 12.03 12.46",
	svg: (
		<>
			<path d="M11 1.774c1.008 0 1.825.819 1.825 1.827v.934l-.235.236-4.912 4.9a1.8 1.8 0 0 0-.404.65l-.007.023-.007.023-.208.67-.012.04c-.212.794.509 1.753 1.488 1.436l.001.003.671-.208v-.001c.276-.082.508-.231.695-.417l2.93-2.931V12.4A1.826 1.826 0 0 1 11 14.226H5A1.826 1.826 0 0 1 3.175 12.4V3.6c0-1.007.817-1.825 1.825-1.826zM6 6.32a.55.55 0 1 0 0 1.1h2.172l.11-.01a.55.55 0 0 0 0-1.079l-.11-.01zm0-2a.55.55 0 1 0 0 1.1h4a.55.55 0 1 0 0-1.1z" />
			<path d="m14.095 6.277-4.908 4.906a.64.64 0 0 1-.283.17l-.67.207c-.133.048-.265-.084-.227-.226l.208-.67a.8.8 0 0 1 .17-.284l4.91-4.901zm.148-1.744a.565.565 0 0 1 .794 0 .564.564 0 0 1 0 .793v.01l-.424.424-.798-.8z" />
		</>
	),
}

export const formFillSmallIcon: LoadedIconFunction<"fillSmall"> = createIcon(
	"formFillSmall",
	iconDefinition,
	"fillSmall",
)
