/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "1.18 1.25 13.68 12.91",
	svg: (
		<path d="M7.53 1.418a.75.75 0 0 1 1.003.052l2.117 2.117.051.057a.75.75 0 0 1-1.054 1.054l-.058-.05-.836-.836v4.811l4.167 2.405-.305-1.141-.017-.075a.751.751 0 0 1 1.441-.387l.025.073.774 2.892a.75.75 0 0 1-.53.919l-2.892.774-.075.017a.75.75 0 0 1-.313-1.465l1.14-.307-4.16-2.403-4.133 2.456 1.149.292.073.022a.75.75 0 0 1-.367 1.447l-.075-.015-2.902-.738a.75.75 0 0 1-.542-.912l.738-2.9.022-.074a.75.75 0 0 1 1.432.442l-.292 1.146 4.142-2.463V3.81l-.837.837a.75.75 0 0 1-1.06-1.06L7.473 1.47z" />
	),
}

export const arrow3DFillSmallIcon: LoadedIconFunction<"fillSmall"> = createIcon(
	"arrow3DFillSmall",
	iconDefinition,
	"fillSmall",
)
