/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "4.44 0.38 7.16 15.23",
	svg: (
		<path d="M11.359 4.491a.75.75 0 0 1-1.06 0L8.75 2.943V6.87a.75.75 0 0 1-1.5 0V2.943L5.702 4.491a.75.75 0 0 1-1.06-1.06L7.47.602a.75.75 0 0 1 1.06 0l2.829 2.829a.75.75 0 0 1 0 1.06M8.75 9.135a.75.75 0 0 0-1.5 0v3.915l-1.548-1.548a.75.75 0 0 0-1.06 1.06l2.828 2.829a.75.75 0 0 0 1.06 0l2.829-2.829a.75.75 0 1 0-1.06-1.06L8.75 13.05z" />
	),
}

export const arrowUpDownStackedFillSmallIcon: LoadedIconFunction<"fillSmall"> =
	createIcon("arrowUpDownStackedFillSmall", iconDefinition, "fillSmall")
