/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "2.37 2.37 11.25 11.25",
	svg: (
		<path d="M3.4 2.375c-.566 0-1.025.46-1.025 1.025v1.2c0 .566.459 1.025 1.025 1.025h7.2c.566 0 1.025-.459 1.025-1.025V3.4c0-.566-.459-1.025-1.025-1.025zm.225 2v-.75h6.75v.75zm-.225 2c-.566 0-1.025.46-1.025 1.025v1.2c0 .566.459 1.025 1.025 1.025h4c.566 0 1.025-.459 1.025-1.025V7.4c0-.566-.459-1.025-1.025-1.025zm.225 2v-.75h3.55v.75zm-.225 2c-.566 0-1.025.46-1.025 1.025v1.2c0 .566.459 1.025 1.025 1.025h9.2c.566 0 1.025-.459 1.025-1.025v-1.2c0-.566-.459-1.025-1.025-1.025zm.225 2v-.75h8.75v.75z" />
	),
}

export const chartBarYAxisSmallIcon: LoadedIconFunction<"small"> = createIcon(
	"chartBarYAxisSmall",
	iconDefinition,
	"small",
)
