/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "2.39 2.87 15.21 14.76",
	svg: (
		<path d="M10.016 17.634a.6.6 0 0 1-.142-.017.5.5 0 0 1-.177-.054C9.399 17.41 2.4 13.721 2.4 7.73c0-2.27 1.251-4.16 3.114-4.704 1.587-.462 3.246.161 4.486 1.64 1.24-1.478 2.9-2.101 4.485-1.64C16.348 3.569 17.6 5.46 17.6 7.73c0 5.992-6.999 9.681-7.297 9.834a.6.6 0 0 1-.287.07m-3.45-13.51q-.353 0-.702.101C4.54 4.611 3.65 6.019 3.65 7.729c0 4.613 5.104 7.851 6.35 8.573 1.246-.722 6.35-3.96 6.35-8.573 0-1.71-.89-3.118-2.214-3.504-1.287-.375-2.637.31-3.61 1.833-.229.36-.823.36-1.053 0-.796-1.248-1.846-1.934-2.908-1.934" />
	),
}

export const heartIcon: LoadedIconFunction<"default"> = createIcon(
	"heart",
	iconDefinition,
	"default",
)
