/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "1.79 2.17 12.42 12.06",
	svg: (
		<path d="M7.875 14.217q.067.015.138.015a.6.6 0 0 0 .287-.07c.241-.124 5.905-3.11 5.905-7.979 0-1.872-1.037-3.433-2.581-3.883C10.597 2 9.174 2.206 8 3.537 6.826 2.206 5.403 2 4.376 2.3c-1.543.45-2.581 2.011-2.581 3.883 0 4.869 5.664 7.855 5.905 7.98q.083.042.175.054" />
	),
}

export const heartFillSmallIcon: LoadedIconFunction<"fillSmall"> = createIcon(
	"heartFillSmall",
	iconDefinition,
	"fillSmall",
)
