/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "1.79 2.17 12.41 12.06",
	svg: (
		<path d="M8.013 14.232a.6.6 0 0 1-.138-.015.5.5 0 0 1-.175-.055c-.241-.124-5.905-3.11-5.905-7.979 0-1.872 1.038-3.433 2.581-3.883C5.403 2 6.826 2.206 8 3.537 9.175 2.206 10.597 2 11.624 2.3c1.544.45 2.581 2.011 2.581 3.883 0 4.869-5.664 7.855-5.905 7.98a.6.6 0 0 1-.287.07M5.25 3.425q-.263 0-.523.075c-1.006.293-1.682 1.372-1.682 2.683 0 3.552 3.877 6.08 4.955 6.714 1.078-.634 4.955-3.162 4.955-6.714 0-1.311-.676-2.39-1.682-2.683-.973-.283-2 .245-2.746 1.414a.625.625 0 0 1-1.054 0c-.613-.961-1.415-1.49-2.223-1.49" />
	),
}

export const heartSmallIcon: LoadedIconFunction<"small"> = createIcon(
	"heartSmall",
	iconDefinition,
	"small",
)
