/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "0.83 1.85 11.91 13.52",
	svg: (
		<>
			<path d="M7.492 9.725c.268 0 .485.216.485.484v2.632c0 .705-.573 1.277-1.278 1.277H4.342l.441.442a.485.485 0 0 1-.685.685l-1.269-1.268a.49.49 0 0 1-.06-.612l.06-.074 1.269-1.268a.485.485 0 0 1 .685.685l-.441.441h2.357a.31.31 0 0 0 .309-.308v-2.632c0-.268.217-.484.484-.484" />
			<path d="M7.9 5a1.7 1.7 0 0 0 1.7 1.7h3.15v5.7A1.75 1.75 0 0 1 11 14.15H8.521c.266-.369.425-.82.425-1.31v-2.632a1.455 1.455 0 0 0-2.073-1.315 1.5 1.5 0 0 0-.2-.251L5.408 7.373a1.454 1.454 0 0 0-2.157.112V3.601c0-.967.784-1.75 1.75-1.75h2.9z" />
			<path d="M4.036 8.058a.485.485 0 0 1 .686 0l1.266 1.268a.486.486 0 0 1 .063.61l-.063.075-1.266 1.27a.485.485 0 0 1-.686-.686l.442-.442h-2.36a.31.31 0 0 0-.308.309v2.632a.484.484 0 0 1-.97 0v-2.632c0-.706.573-1.277 1.278-1.277h2.36l-.442-.443a.484.484 0 0 1 0-.684M8.9 2.044q.243.124.44.32l2.897 2.896c.13.13.237.28.32.44H9.6a.7.7 0 0 1-.7-.7z" />
		</>
	),
}

export const docSwapFillSmallIcon: LoadedIconFunction<"fillSmall"> = createIcon(
	"docSwapFillSmall",
	iconDefinition,
	"fillSmall",
)
