/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "2.87 2.87 14.25 14.25",
	svg: (
		<path d="M6.25 2.875a.875.875 0 1 1 0 1.75h-1a.625.625 0 0 0-.625.625v9.5c0 .345.28.625.625.625h1a.875.875 0 0 1 0 1.75h-1a2.375 2.375 0 0 1-2.375-2.375v-9.5A2.375 2.375 0 0 1 5.25 2.875zm8.5 0a2.375 2.375 0 0 1 2.375 2.375v9.5a2.375 2.375 0 0 1-2.375 2.375h-1a.875.875 0 0 1 0-1.75h1c.345 0 .625-.28.625-.625v-9.5a.625.625 0 0 0-.625-.625h-1a.875.875 0 0 1 0-1.75z" />
	),
}

export const bracketFillIcon: LoadedIconFunction<"fill"> = createIcon(
	"bracketFill",
	iconDefinition,
	"fill",
)
