/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "2.37 4.12 16.79 14.42",
	svg: (
		<>
			<path d="M18.507 11.112c.362 0 .655.293.655.656v4.369a.656.656 0 0 1-1.311 0V13.35l-4.997 4.997a.655.655 0 1 1-.927-.928l4.997-4.997h-2.786a.655.655 0 1 1 0-1.31zM9.45 15.875H4.5a2.125 2.125 0 0 1-2.125-2.125V12.3H9.45z" />
			<path d="M12.309 12.3c.21.725.84 1.272 1.61 1.36l-2.214 2.215H10.55V12.3zM9.45 11.2H2.375V8.8H9.45zm8.175-1.338h-3.487c-.855 0-1.577.563-1.819 1.338h-1.77V8.8h7.076zM9.45 7.7H2.375V6.25c0-1.174.951-2.125 2.125-2.125h4.95zm6.05-3.575c1.174 0 2.125.951 2.125 2.125V7.7H10.55V4.125z" />
		</>
	),
}

export const collectionArrowFillIcon: LoadedIconFunction<"fill"> = createIcon(
	"collectionArrowFill",
	iconDefinition,
	"fill",
)
