/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "1.77 3.17 13.66 11.76",
	svg: (
		<>
			<path d="M14.806 8.79c.344 0 .624.28.624.624v3.495a.625.625 0 0 1-1.25 0v-1.987l-3.826 3.827a.625.625 0 0 1-.786.08l-.097-.08a.624.624 0 0 1 0-.883l3.827-3.827H11.31a.626.626 0 0 1 0-1.249zM7.45 12.825H3.6A1.826 1.826 0 0 1 1.775 11V9.95H7.45z" />
			<path d="M9.618 9.95c.16.506.542.914 1.03 1.11l-1.763 1.765H8.55V9.95zM7.45 8.85H1.774v-1.7H7.45zm6.776-1.21H11.31c-.782 0-1.445.507-1.681 1.21h-1.08v-1.7h5.677zM7.45 6.05H1.774V5c0-1.008.819-1.825 1.827-1.825h3.85zm4.95-2.875c1.008 0 1.826.817 1.826 1.825v1.05H8.55V3.176z" />
		</>
	),
}

export const collectionArrowFillSmallIcon: LoadedIconFunction<"fillSmall"> =
	createIcon("collectionArrowFillSmall", iconDefinition, "fillSmall")
