/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "1.77 1.77 12.46 12.46",
	svg: (
		<>
			<path d="M6.47 4.278a.333.333 0 0 1 .431.431 3.393 3.393 0 0 0 4.39 4.389.333.333 0 0 1 .43.43 4.06 4.06 0 0 1-3.464 2.581l-.32.013a4.06 4.06 0 0 1-4.053-3.85l-.006-.209A4.06 4.06 0 0 1 6.47 4.278" />
			<path d="M8 1.775a6.226 6.226 0 1 1 0 12.452A6.226 6.226 0 0 1 8 1.775m0 1.25a4.975 4.975 0 1 0 0 9.95 4.975 4.975 0 0 0 0-9.95" />
		</>
	),
}

export const moonCircleSmallIcon: LoadedIconFunction<"small"> = createIcon(
	"moonCircleSmall",
	iconDefinition,
	"small",
)
