/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 20 20",
	fittedViewBox: "2.37 4.12 15.25 11.75",
	svg: (
		<>
			<path d="M6.93 11.625a.5.5 0 0 0-.5.5v1.25a.5.5 0 0 0 .5.5h6.145a.5.5 0 0 0 .5-.5v-1.25a.5.5 0 0 0-.5-.5z" />
			<path d="M4.5 4.125A2.125 2.125 0 0 0 2.375 6.25v7.5c0 1.174.951 2.125 2.125 2.125h11a2.125 2.125 0 0 0 2.125-2.125v-7.5A2.125 2.125 0 0 0 15.5 4.125zM3.625 6.25c0-.483.392-.875.875-.875h11c.483 0 .875.392.875.875v7.5a.875.875 0 0 1-.875.875h-11a.875.875 0 0 1-.875-.875z" />
		</>
	),
}

export const peekBottomIcon: LoadedIconFunction<"default"> = createIcon(
	"peekBottom",
	iconDefinition,
	"default",
)
