/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "0.84 2.88 13.86 10.68",
	svg: (
		<>
			<path d="m13.931 4.706.581-.581v-.012a.74.74 0 0 0-.029-1.012.74.74 0 0 0-1.042 0l-.558.557zm-6.085 6.086 5.639-5.64-1.048-1.048-5.644 5.635c-.1.1-.17.232-.217.358l-.237.766-.001.004c-.06.226.15.46.385.378l.758-.235a.8.8 0 0 0 .365-.218" />
			<path d="M6.026 4.21c-.283 0-.562.065-.815.192l-.517.259a.55.55 0 1 0 .492.983l.517-.258q.152-.076.323-.077h.071a.65.65 0 0 1 .275 1.24L2.417 8.395a2.71 2.71 0 0 0 1.146 5.168h.063c.735 0 1.44-.292 1.96-.812l.136-.135a.55.55 0 1 0-.778-.778l-.135.135c-.314.314-.74.49-1.183.49h-.063a1.61 1.61 0 0 1-.68-3.07l3.955-1.847a1.75 1.75 0 0 0-.74-3.337z" />
		</>
	),
}

export const pencilScribbleFillSmallIcon: LoadedIconFunction<"fillSmall"> =
	createIcon("pencilScribbleFillSmall", iconDefinition, "fillSmall")
