/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react"

import {
	createIcon,
	type IconDefinition,
	type LoadedIconFunction,
} from "../../iconUtils"

export const iconDefinition: IconDefinition = {
	viewBox: "0 0 16 16",
	fittedViewBox: "2.5 2.5 11.01 11.01",
	svg: (
		<path d="M2.5 3.4a.9.9 0 0 1 .9-.9h9.2a.9.9 0 0 1 .9.9v1.2a.9.9 0 0 1-.9.9H3.4a.9.9 0 0 1-.9-.9zm.8 3.1h9.4v6.1a.9.9 0 0 1-.9.9H4.2a.9.9 0 0 1-.9-.9zM6.4 8a.5.5 0 0 0 0 1h3.2a.5.5 0 1 0 0-1z" />
	),
}

export const archiveBoxFillSmallIcon: LoadedIconFunction<"fillSmall"> =
	createIcon("archiveBoxFillSmall", iconDefinition, "fillSmall")
